### ISSUE TITLE
Greyscale turns off on refresh in 0.7.7

### ISSUE THREAD

**Issue by Zamrod** [dev7355608/perfect-vision#1]
The first time a player logs in they don't get the greyscale filter applied. If a new scene is activated it works there but if the player refreshes their browser the filter goes away again.

**Comment by dev7355608** [comment]
Please confirm whether the issue has been resolved in v1.1.0.

**Comment by Zamrod** [comment]
It works now but it seems like greyscale doesn’t work at all while the module FX Master is enabled.

**Comment by dev7355608** [comment]
Fixed it in v1.1.1.
