### ISSUE TITLE
Large Performance dip in a scene with many tokens with Token Auras enabled

### ISSUE THREAD

**Issue by MAClavell** [dev7355608/perfect-vision#102]
Since I updated from 2.0 I've noticed a large dip in performance in one of my scenes when Token Auras and Perfect Vision are both enabled. I have a scene that houses all the tokens for the NPCs in my game (199+). The scene has no background image, Token Vision and Fog Exploration disabled, Darkness set to 0, all of the tokens have vision disabled, every token image is a webp, etc. The only things in the scene are the tokens and some drawings to help me organize them.

I have a GTX 1080. With Perfect Vision disabled, Task Manager says I'm getting around 9% GPU Usage in the "3D" section. With Perfect Vision enabled, I'm getting 100% GPU usage in the "3D" section, which also causes my GPU to whine very loudly. The same happens when Token Auras is toggled.
![NoPerfectVisionGPU](https://user-images.githubusercontent.com/25129246/127810236-52412501-185e-49b0-a5b0-d74604f34ee5.jpg)
![PerfectVisionGPU](https://user-images.githubusercontent.com/25129246/127810250-7f7ddbcf-145b-4e3b-88f7-dcb13412ed7b.jpg)

Scene's health report: { "Walls": 0, "Lights": 0, "Tokens": 199, "Dimensions": { "x": 6000, "y": 6000 } }

**Comment by dev7355608** [comment]
Thanks for the report. I'm already working to fix the problem you describing. I'll let you know when it's ready.

**Comment by dev7355608** [comment]
Try v2.3.0, and let me know if the lag is gone.

**Comment by MAClavell** [comment]
Yep, that fixed it. Thanks!
