### ISSUE TITLE
Conflict with Weather Blocker

### ISSUE THREAD

**Issue by Ikabodo** [dev7355608/perfect-vision#104]
It seems Perfect Vision is throwing a lib-error when Weather Blocker is enabled.

```
j: Error detected, possibly in module 'perfect-vision'.
Could not find target '_weatherBlock.updateMask': Could not find root scope '_weatherBlock'.
```

**Comment by dev7355608** [comment]
I think you Weather Blocker might not be up to date.

**Comment by Ikabodo** [comment]
Yes, my bad for not checking an update. I just downloaded it so I figured it was the latest. Good catch.
