### ISSUE TITLE
Dim vision in dim light

### ISSUE THREAD

**Issue by daishimatt** [dev7355608/perfect-vision#106]
For the last 3 (recent) updates I've noticed that Dim vision changes aren't having any effect.

I have dim vision givng bright light in dim light areas, but when I select a token with dim vision the light levels aren't visibly changing.  It used to work perfectly until recently.

**Comment by dev7355608** [comment]
It works on my end. Do you get error messages in the console (F12 -> Console)?

**Comment by dev7355608** [comment]
Did you try whether it works when PV is the only active module?

**Comment by daishimatt** [comment]
yes, even with only PV on I get the same thing.
I've had this before if a location is set somewhere in the module, because
I run everything off a small server I put together.  Modules that work for
the developers don't work because the location is set incorrectly.  The
thing that is odd this time is that Darkvision is working fine, its just
Low-light vision that is failing.  As a note this is for a pf2e game.

**Comment by dev7355608** [comment]
Do you have PF2e's *Rules-based vision* enabled?

**Comment by MrChessur** [comment]
I am having this same issue and I don't have Rules-based vision enabled. I even jumped onto a test world completely new with only perfect vision enabled and it still does not properly show the dim area as bright for tokens with dim vision.

**Comment by dev7355608** [comment]
Sorry, I was confused and tested darkvision all this time for some reason instead of low light. I found the bug in PV and fixed it in v2.3.6.

I also know you didn't have the module Lichtgeschwindigkeit enabled: with it my buggy code would have been skipped. It's a great module that improves sight a lot. I highly recommend it.
