### ISSUE TITLE
Token Vision PF2e

### ISSUE THREAD

**Issue by netavarka** [dev7355608/perfect-vision#107]
Hi,

looks like the token vision in pf2e is broken.
Selecting a token with "has-vision" activated, removes all non-invisible tokens from the screen.

[https://streamable.com/g282fd](https://streamable.com/g282fd)

**Comment by Smoldar-og** [comment]
The same issue is happening on DND 5e

**Comment by dev7355608** [comment]
This is probably a module conflict. Do you get errors in the console (F12 -> Console)? Did you try whether if works when PV is the only active module? If it's a module conflict, you can use *Find the culprit* to figure out which module is causing the conflict.

**Comment by netavarka** [comment]
There were no module conflicts in the console yesterday, but i didn't try to deactivate every other module.

Release 2.5.0 fixed it, so i can only guess that it was the low-light vision problem?
The only module i use from the release notes is Sequencer, but that one was deactivated at the time of my test.

Thx for the great work!

**Comment by dev7355608** [comment]
Good to hear it was accidently fixed. Nice!
