### ISSUE TITLE
[BUG] Lights not working anymore

### ISSUE THREAD

**Issue by DarKDinDoN** [dev7355608/perfect-vision#109]
Hi,

With the latest version of perfect vision and 5e 1.4.1, I don't see lights on the canvas anymore
![image](https://user-images.githubusercontent.com/1687854/128263563-c4aac7bb-dc97-4ea5-8e1b-baa7732008c4.png)

Tested with a brand-new scene, with multiple parameters and only perfect vision activated.

**Comment by DarKDinDoN** [comment]
@dev7355608 Hmm after further research. The lights are working correctly **only** if there is a background image to the scene.

**Comment by dev7355608** [comment]
Thanks for the report. Fixed in 2.6.1.
