### ISSUE TITLE
Scene won't render and console error

### ISSUE THREAD

**Issue by west1778** [dev7355608/perfect-vision#11]
While having Perfect Vision turned on no scene will load and getting an error.

![image](https://user-images.githubusercontent.com/73608023/100138206-a92afb00-2e5b-11eb-9af8-54a048cad301.png)

**Comment by DarKDinDoN** [comment]
![image](https://user-images.githubusercontent.com/1687854/100139572-f7f28800-2e8f-11eb-9df2-997811e3c41e.png)
Same here

**Comment by dev7355608** [comment]
If you can, disable libWrapper in the mean time. I'll fix it later.

**Comment by west1778** [comment]
Oh yeah no rush on my part. :) Love your module. Just wanted to report the issue.

**Comment by Avitale34** [comment]
Came here to report same thing :) Love the module!

**Comment by dev7355608** [comment]
Fixed in v1.2.6.
