### ISSUE TITLE
Can see tiles on lower levels when perfect vision is enabled

### ISSUE THREAD

**Issue by Avitale34** [dev7355608/perfect-vision#110]
It seems like when perfect vision is enabled I am seeing tiles from lower floors through the roof.
![image](https://user-images.githubusercontent.com/65961637/128691499-3eff7390-5cf5-46a4-ba9f-628532160141.png)
![image](https://user-images.githubusercontent.com/65961637/128691521-f34b563f-d416-4599-86cf-b47ac2e40d5e.png)

**Comment by dev7355608** [comment]
Thanks for the report. Fixed in v2.6.3.
