### ISSUE TITLE
Cannot read property 'scale' of undefined

### ISSUE THREAD

**Issue by Zamrod** [dev7355608/perfect-vision#111]
Received 7 of this error when switching scenes and when I arrived none of the tokens were visible in the scene including my own:

libWrapper-wrapper.js:627 Uncaught TypeError: Cannot read property 'scale' of undefined
    at Token5e.refresh (foundry.js:44708)
    at x.🎁call_wrapped [as call_wrapped] (modules/lib-wrapper/lib-wrapper.js:1)
    at Token5e.wrapper (modules/perfect-vision/scripts/utils/patch.js:17)
    at modules/perfect-vision/scripts/utils/patch.js:52
    at Token5e.wrapper (modules/perfect-vision/scripts/utils/patch.js:12)
    at Token5e.wrapper (modules/perfect-vision/scripts/utils/patch.js:52)
    at x.🎁call_wrapper [as call_wrapper] (modules/lib-wrapper/lib-wrapper.js:1)
    at Token5e.🎁Token.prototype.refresh#0 (modules/lib-wrapper/lib-wrapper.js:1)

**Comment by dev7355608** [comment]
The error message doesn't tell much unfortunately. Were there error messages in the console before this one? This isn't necessarily a PV bug: the error just happens in a function wrapped by PV.

**Comment by Ikabodo** [comment]
Yeah, I'm getting similar behavior. Several of my players mentioned that they could not see the other players until the reloaded. I saw this error in the log.

I might be wrong about this, but I THINK it might be happening on scenes with animated tiles on them.

![image](https://user-images.githubusercontent.com/7766890/129458321-70750e0c-63b2-4835-99cb-647d3eb35179.png)

**Comment by Ikabodo** [comment]
It sometimes also freezes the loading of the scene.

**Comment by dev7355608** [comment]
Does it happen if PV is the only active module (besides libWrapper)?

**Comment by Ikabodo** [comment]
> Does it happen if PV is the only active module (besides libWrapper)?

Yes.

I'm not actually getting the error now after some tries, but scenes with animated tiles won't load properly when activated when PV is active by itself (and lib).

![image](https://user-images.githubusercontent.com/7766890/129463159-9c0deef4-75cb-4af7-b95f-2500f1abd7af.png)

**Comment by Ikabodo** [comment]
This is with only PV, and the the scene loads fine without animated tiles.

**Comment by dev7355608** [comment]
I released a big update today. Maybe it fixed itself, at least I hope so. If not let me know, and, if it's possible, share the scene with me that isn't working. I haven't been able to reproduce it yet.

**Comment by dev7355608** [comment]
This error happens without PV as well: 
![image](https://user-images.githubusercontent.com/31905376/129807506-ab247605-bf8e-422d-82ce-d7ddab16093b.png)

I don't think that's the error breaking the canvas when switching scene. Let me know whether you can still reproduce the freezing in 2.8.5.

**Comment by dev7355608** [comment]
Is this still an issue? Please let me know.

**Comment by Zamrod** [comment]
I'm not sure if it was the same issue but one of my players did run into the issue of not being able to see his own token after a scene change during the game today.

**Comment by dev7355608** [comment]
> I'm also having these issues with PV. I can always replicate it if I have a player connected and then delete a token and then try to move or add a token.

I just tried to replicate it but without success. Maybe it's a module conflict. Does it still happen if PV is the only active module (besides libwrapper)?

**Comment by Razeick** [comment]
I thought so too but I am not sure now. I moved my actors and modules to a new world and tried all the modules on while PV and libwrapper were on and I can replicate the issue anymore. I can still replicate it though on my original world

**Comment by dev7355608** [comment]
> I thought so too but I am not sure now. I moved my actors and modules to a new world and tried all the modules on while PV and libwrapper were on and I can't replicate the issue anymore. I can still replicate it though on my original world though

Could you share the error messages you get in the console (F12) if there are any.

**Comment by Razeick** [comment]
foundry.js:45110 Uncaught (in promise) TypeError: Cannot read property 'scale' of undefined
[Detected 4 packages: monks-little-details, lib-wrapper, perfect-vision, stairways]
    at Token5e.refresh (foundry.js:45110)
    at Z.🎁call_wrapped [as call_wrapped] (libWrapper-wrapper.js:467)
    at Token5e.tokenRefresh (monks-little-details.js:180)
    at Z.🎁call_wrapper [as call_wrapper] (libWrapper-wrapper.js:576)
    at Token5e.wrapper (patch.js:17)
    at patch.js:52
    at Token5e.wrapper (patch.js:12)
    at Token5e.wrapper (patch.js:52)
    at Z.🎁call_wrapper [as call_wrapper] (libWrapper-wrapper.js:576)
    at Token5e.🎁Token.prototype.refresh#0 (libWrapper-wrapper.js:164)
    at foundry.js:19760
    at Array.forEach (<anonymous>)
    at TokenLayer.activate (foundry.js:19760)
    at TokenLayer.activate (foundry.js:40469)
    at TokenLayer.activate (injection.js:136)
    at TokenLayer._onDropActorData (foundry.js:40696)

**Comment by dev7355608** [comment]
I think this issue was fixed but if it wasn't entirely, it is going to be no longer an issue once v9 is released.
