### ISSUE TITLE
Overlay from one token stacks on another

### ISSUE THREAD

**Issue by Avitale34** [dev7355608/perfect-vision#112]
When multiple tokens are stacked on top of each other any overlay conditions appear on top of the other. Pics below better show.

With PV
![image](https://user-images.githubusercontent.com/65961637/129303917-a177f84d-8cac-46c5-b194-879a6be7f41b.png)
![image](https://user-images.githubusercontent.com/65961637/129303934-007ab732-aa0a-4a81-b74b-3f63ddb583e8.png)

Without PV
![image](https://user-images.githubusercontent.com/65961637/129304024-a0a877b6-1d16-45d2-9084-eb19126d48b7.png)

**Comment by dev7355608** [comment]
I'm aware. I don't want status effects to be affected by lighting and monochrome vision. This is an unfortunate side effect, for which there's no good solution I'm aware of. I left it like it is for now, because it's going to be like this in Foundry v9 as well.

**Comment by Avitale34** [comment]
Hmm okay is there anyway to have that be an optional setting? I would rather have that effect then the current overlay setting. I ran a combat last session and a lot of the NPCs were walking on bodies of other npcs and created a really weird effect when trying to tell who was alive and who was dead. If not it's not possible that's fine too.

**Comment by dev7355608** [comment]
I don't like to add an optimal setting: I'd like to have a solution that works for everybody. But I made a change for the defeated (skull overlay) status effect. If a token has this status effect, it is rendered like a tile and the overlay icon is masked. Consequently it isn't rendered on top of other tokens anymore. This change is disabled if either the Levels module or the Token Factions module is enabled: it wouldn't work for technical reasons. Try 2.8.0, and let me know what you think.

**Comment by Avitale34** [comment]
Thanks it seems to work without levels! Unfortunately I use Levels for alot of my maps, so fingers crossed for future compatibility.

**Comment by dev7355608** [comment]
I made it work with Levels, but it's not perfect. It won't work correctly for overlapping tokens above the controlled token. But for tokens on the same elevation or below it works. It's probably not worth making it work with tokens above the controlled token, because it would probably entail a not insignificant performance impact.

![image](https://user-images.githubusercontent.com/31905376/129569299-81b12232-682b-4157-afcb-d948b2a9d00b.png)

**Comment by RavenknightDM** [comment]
This is very distracting. :( Isn't it possible to make it optional? It's not just overlays but any status effect.
![1](https://user-images.githubusercontent.com/53635985/130366321-f942a8c5-8ded-4e77-a04d-996f3e713c85.png)
![2](https://user-images.githubusercontent.com/53635985/130366324-9d201a25-f9f7-410c-8354-0017fce7f06e.png)
![3](https://user-images.githubusercontent.com/53635985/130366326-2cc1287f-550c-4e6f-a396-a192920f7004.png)

**Comment by dev7355608** [comment]
I cannot make the same change for all status effects. Then any token with a status effect would be rendered like a tile basically: that's not good. I was thinking to handle all overlay effects like the default skull icon is handled now. I suppose overlay status effects mostly mean that the token is incapacitated in one form or another. So there might not be any downsides to this approach. I would suggest we try it this way and see if someone complains. Status effects are going to be rendered on top always in Foundry v9 causing the same issue: so it won't be a PV-only issue much longer. And I assume there won't be a option to render status effects differently or any attempt to fix this issue. So PV already offers an improvement over what you can expect from v9 (without PV).

**Comment by RavenknightDM** [comment]
That sounds awesome. Again, sorry for the bad tone in my post.

**Comment by dev7355608** [comment]
No worries! I made the change in 2.8.13. Let me know if you notice any downsides to handling all overlay effects this way.

**Comment by RavenknightDM** [comment]
Works flawlessly. Thank you so very much.
