### ISSUE TITLE
New Vision and Lighting areas is misaligned with Levels

### ISSUE THREAD

**Issue by Iankid** [dev7355608/perfect-vision#113]
The new vision and lighting areas feature is exactly what I was looking for in conjuncture with the Levels Module.
I did find this bug though that misaligns it.
![vision levels](https://user-images.githubusercontent.com/60759323/129494134-12ec3ad2-6826-4a5d-8ed9-3a60b0ff9fd1.png)
Drawn area is top 19 ft. So any token who has a higher place LoS, and is able to see over the 19 ft mark should see the roof. However, currently they can only see the roof, when their Elevation, not their LoS, is 20+ ft.

I'm currently countering this by place a light source within the 20+ ft range.

**Comment by dev7355608** [comment]
Could share more details about your scene/token/drawing/roof settings? If you could export the scene and share it, that would be perfect.

**Comment by dev7355608** [comment]
Fixed.
