### ISSUE TITLE
after dnd5e update to 1.4.2, some scenes are completely black and white

### ISSUE THREAD

**Issue by jcolson** [dev7355608/perfect-vision#114]
if perfect vision is disabled, color comes back to scenes

![image](https://user-images.githubusercontent.com/2362647/129603950-c55638b0-462a-4705-ada9-9f2d05b60228.png)

![image](https://user-images.githubusercontent.com/2362647/129603991-e136c631-c6cc-4bd5-9cf3-c2e8a06ef0fc.png)

scene example:
![image](https://user-images.githubusercontent.com/2362647/129604034-07ae5a75-8aac-441c-9b7f-2840c8ee21c8.png)

another:
![image](https://user-images.githubusercontent.com/2362647/129604092-e29ce856-abcf-432b-ab98-4710774ef047.png)

**Comment by dev7355608** [comment]
Uncheck the box of *Saturation Level*. I haven't gotten to the bottom of this bug yet, but somehow the migration code of 2.8.0 can fail and force saturation to be zero in certain scenes.

**Comment by jcolson** [comment]
> Uncheck the box of _Saturation Level_. I haven't gotten to the bottom of this bug yet, but somehow the migration code of 2.8.0 can fail and force saturation to be zero in certain scenes.

that did the trick, thank you.
