### ISSUE TITLE
D&D 5e bug

### ISSUE THREAD

**Issue by justinthejaguar** [dev7355608/perfect-vision#115]
Similar issue to the prior one, but different. My scenes turn completely white with Perfect Vision on. I am given the following errors.

![image](https://user-images.githubusercontent.com/38022481/129649507-bc3fb962-2625-4f61-ae6a-835cb62625c7.png)

![image](https://user-images.githubusercontent.com/38022481/129649578-435e4b2a-cbec-4383-ac43-a2ba0e68d5ec.png)

PC tokens are visible on the scene, but not the NPC tokens or background. All tokens are png, and background is jpeg.

![image](https://user-images.githubusercontent.com/38022481/129649972-e9019aab-7a69-4a95-a313-77561ed904ca.png)

I have turned off saturation as suggested in issue #114
![image](https://user-images.githubusercontent.com/38022481/129650026-daab9ae3-8f38-4b98-842a-8dd746b6448d.png)

**Comment by dev7355608** [comment]
I think, I fixed this already. Check whether your PV is up to date (2.8.3).

**Comment by dev7355608** [comment]
I assume, this is no longer an issue. If not, let me know.
