### ISSUE TITLE
Deleting a scene you are presently viewing, and then switching to another scene causes vision error

### ISSUE THREAD

**Issue by foxreinhold** [dev7355608/perfect-vision#116]
Steps to reproduce:

1. Load a scene as a GM and have it be rendered on the canvas in front of you
2. Delete the scene from the game either from the quick nav bar or from the scenes menu on the right side while still viewing the scene.
3. Switch to another scene.
4. An outline equal to the size of the now deleted scene will be present on the currently viewed scene.

With perfect vision turned off, this does not occur.

![image](https://user-images.githubusercontent.com/77173822/129791287-c79afd10-acae-4bbc-b3c9-941774ea52fe.png)

Obviously this is an edge case since most people don't actively delete scenes players are looking at, and would likely only come up while the GM was logged in alone and setting maps up.  Reloading the page (F5) fixes everything.

**Comment by dev7355608** [comment]
Thanks for the report. Fixed it in 2.8.5.
