### ISSUE TITLE
Weird banding in already explored areas

### ISSUE THREAD

**Issue by foxreinhold** [dev7355608/perfect-vision#117]
![image](https://user-images.githubusercontent.com/77173822/130344601-1d358d52-3f17-4df2-ac22-973804f71ac3.png)

**Comment by dev7355608** [comment]
Did you get error messages in the console? Can you still reproduce it?

**Comment by foxreinhold** [comment]
After the most recent updates I have been unable to reproduce it.

**Comment by dev7355608** [comment]
Let me know should you experience this issue again.
