### ISSUE TITLE
[BUG] Monk's little details bug with "token highlight"

### ISSUE THREAD

**Issue by DarKDinDoN** [dev7355608/perfect-vision#119]
Hello,

"Monk's little details" got an update and the "token highlight" is now above the token instead of beneath.

![image](https://user-images.githubusercontent.com/1687854/130372977-a4913333-986f-489d-bfeb-4d2a3d4d8f87.png)

**Comment by dev7355608** [comment]
Thanks for the report. Fixed in 2.8.13.
