### ISSUE TITLE
5e Devil's Sight

### ISSUE THREAD

**Issue by perkyguy** [dev7355608/perfect-vision#12]
I know that this is DnD 5e Specific, but it would be amazing if we could come up with a way get Devil's Sight working as per the rules. The warlock's Devil's Sight invocation states,

> You can see normally in darkness, both magical and nonmagical, to a distance of 120 feet.

This is easier to handle with monsters/NPCs which have this feature, as the GM can ignore token vision to get around this. However, for PCs, it would be great to handle this. The current workaround is to give the token a Bright Vision radius. However, this ignores dim light (which is not affected by the invocation), and thus isn't quite correct. 

I'm not sure if this lies within the purview of this module, or if it would need to exist in another separate one. However, this is just a "vision-related shortcoming" that I run into.

**Comment by dev7355608** [comment]
Just configure bright vision like so:
```
Bright Vision in Darkness:  Bright Light / Bright Light (monochrome)
Bright Vision in Dim Light: Dim Light
```
Then dim light isn't affected. These settings should give you proper Devil's Sight.
