### ISSUE TITLE
Major lag issues on scenes with many walls

### ISSUE THREAD

**Issue by dmaneyapanda** [dev7355608/perfect-vision#121]
I can't pinpoint exactly when it started because it's been a few weeks since I hosted a game, but sometime in the last few weeks one of the PV updates has caused significant lag issues during token movement.  When selecting and dragging a token to move, it will go 10ish feet, then will lag for a half second or second, then move another 10 feet, then lag again, etc.  If I bring up the task manager, I can see the GPU at around 80% average, but spiking between 50-100% while this move is going on, which can end up taking 10s or more.

This primarily seems to happen on scenes with many walls - not something I would normally do myself, but I am running a campaign that I imported from Roll20, which imported with lots of tiny wall segments for cave walls, etc.  Prior to a few weeks ago I never had any significant lag issues, even with the excess of wall segments.  It is worth noting that I do not notice any problems with lag on scenes with no walls, or with a very small number of them.  I haven't done extensive testing though.

Possibly the issue is related to either one of the recent Foundry system updates, or the dnd5e updates, but as I'm having issues with both most recent release versions I suspect this qualifies as an issue with PV regardless.

I can replicate the problem with only PV (and libwrapper) loaded.  And the problem goes away if I turn off PV, even if I have my 50-100 other mods still enabled.  So it seems to definitely be PV causing it, not any module interaction.

**Comment by dev7355608** [comment]
I had a lot unoptimized placeholder code in pre 2.9.0. I released 2.9.0 just now with a lot of improvements. Let me know if you still experience lag in this scene.

**Comment by dmaneyapanda** [comment]
Works like a charm again.  Thanks!

**Comment by dev7355608** [comment]
Happy to hear that!
