### ISSUE TITLE
Cannot read property 'canvas' of undefined

### ISSUE THREAD

**Issue by s-magro** [dev7355608/perfect-vision#122]
Happens occasionally right after a scene change when clicking or adding a token to a scene - The result is that the user is unable to interact with the scene at all. The following error was in the console:

![image](https://user-images.githubusercontent.com/89585850/130962036-19c60967-1c88-4e12-9339-8734bf2f4614.png)

![image](https://user-images.githubusercontent.com/89585850/130962192-61bfbbed-c8ad-43ac-bb7a-0449ce35a7da.png)

**Comment by dev7355608** [comment]
Thanks for the report. Fixed it.
