### ISSUE TITLE
Sight Limit causes dysfunctional token movement

### ISSUE THREAD

**Issue by Spappz** [dev7355608/perfect-vision#124]
### Overview
When loading Perfect Vision is being used in a scene with a sight limit, a whole bunch of errors occur that cause all token movement (whether by click-and-drag or arrow keys) to become unpredictable, as well as Perfect Vision rules not applying. The follow console errors are reported:
> `Uncaught ReferenceError: can't access lexical declaration 'cache' before initialization [Detected 3 packages: perfect-vision, lib-wrapper, system:pf2e]`
Upon selecting any token (`lighting.js:249:17`)
> 
> `ReferenceError: can't access lexical declaration 'cache' before initialization`
Upon trying to move said token (`foundry.js:35168:15`)

I've left out all the error details as they are _long_, but I'm happy to post a complete log if you wish.

### Example
This actor has dim light vision using PF2 Perfect Vision rules in the PF2 system. I'm pressing the arrow keys to move the token.
https://user-images.githubusercontent.com/34202141/131234116-ef4c4f69-cf6c-4610-9019-1bea4172a4c5.mp4

Relevant scene settings for this example. However, I've done some testing and found the only two settings that matter is Token Vision being true and Sight Limit not being unlimited/blank. I assume the module is effectively disabled if Token Vision is false, so the bug is most likely triggered by Sight Limit.
https://user-images.githubusercontent.com/34202141/131234130-c95328ea-b425-48a8-a305-08796f5e8a3a.png

### Tested with...
**Software:** Foundry 0.8.9
**System:** PF2e 2.12.5.7603 / DnD5e 1.4.2 (tested and reproduced on both)
**Modules:** Perfect Vision 2.9.0, libWrapper 1.10.2.0 (no other modules loaded)
**Browser:** Firefox 93.0

All software/system/module versions should be latest at the time of writing.

**Comment by dev7355608** [comment]
Thanks for the report. Fixed it.
