### ISSUE TITLE
Fog reveal carries over from other scenes

### ISSUE THREAD

**Issue by magroader** [dev7355608/perfect-vision#125]
I was seeing this issue, then Beeblebrox posted about it in the Foundry Discord with actual repro steps:

https://discord.com/channels/170995199584108546/722566083499786352/881712482064924733

Beeblebrox says:
>  the problem stops when I disable the module.
> 
> To reproduce:
> - Open a scene with fog of war
> - Reset fog of war
> - Open an different scene with fog of war
> - Move a token with vision around the scene
> - Open the previous scene. The revealed areas from the 2nd scene will now also be visible on the 1st. (sometimes it doesn't happen until you go back and forth between the scenes twice)
> 
> The problem occurs when logged in as either a GM or a player.

**Comment by dev7355608** [comment]
Thanks for the report. Fixed it.
