### ISSUE TITLE
Latest update make targetting .. strange. 

### ISSUE THREAD

**Issue by Padhiver** [dev7355608/perfect-vision#126]
Hello !

I think there is an incompatibility with the target that Better Target uses, below is a screenshot without and with Perfect vision. The funny thing is that the Smart Target module also uses this icon for targeting and the same thing bugs.

![image](https://user-images.githubusercontent.com/80126915/131341988-0cc8526d-8ae6-4c11-9251-30e2e6b50338.png)

No error in console, and tested with all module disabled except Perfect Vision, Foundry 8.9 and DnD5e.

**Comment by dev7355608** [comment]
Thanks for the report. It's actually a bug in the pixi lib graphics-smooth. I added patch in the latest release that corrects that.

You may notice that the inner circle is jagged and the outline is missing. That's also currently not implemented correctly in graphics-smooth. But this library is going to be shipped with Foundry v9 as well. Meaning, it will look like that in v9 with or without PV unless graphics-smooth is updated before that to fix this issue, I suppose.
