### ISSUE TITLE
Not working on The Forge

### ISSUE THREAD

**Issue by AetherianRPG** [dev7355608/perfect-vision#127]
Perfect Vision module stopped working on The Forge. Dont't know if this is a server side issue or not. Anyway, posting this here too.
![Capturar](https://user-images.githubusercontent.com/68928934/131422478-371adefd-01d5-4d61-85ea-7ad87c5a938f.PNG)

**Comment by AetherianRPG** [comment]
![Capturar](https://user-images.githubusercontent.com/68928934/131423503-d50f371a-5361-46d9-9c3e-6468c9b148d6.PNG)

**Comment by dev7355608** [comment]
I assume it works again. If not, let me know.
