### ISSUE TITLE
Fog of war weirdness

### ISSUE THREAD

**Issue by BlackMoons** [dev7355608/perfect-vision#128]
Hi, Seem to be having issues with fog of war and the latest perfect-vision update.

Steps to reproduce: uncover some area on map A
Switch to map B, switch to map A (via nav at top of screen)
Everything is fine
Switch to map B, switch to map A
Fog of war is reset, or rather, fog of war only shows what you uncovered since 'everything is fine' and forgets everything uncovered before that?

Disabling perfect vision seems to fix this issue. 

I also see some weird fog of war artifacts on map B, if I travel along the bottom of the map, when map B is much bigger then map A

**Comment by dev7355608** [comment]
Thanks for the report and sorry for yet another fog of war bug! I try to optimize the laggy fog of war experience. I hope this is the last bug. I think it's fixed now in 2.9.6. Let me know.

**Comment by BlackMoons** [comment]
Fog of war seems fixed! Thanks!
