### ISSUE TITLE
Canvas won't load if Enhanced Terrain Layer module has an inactive terrain

### ISSUE THREAD

**Issue by RicoTheBold** [dev7355608/perfect-vision#129]
**Tested with a new world using:**
  Foundry VTT _0.8.9_
  Pathfinder 2nd Edition _2.13.2.7794 (system)_
  Perfect Vision _2.97_
  libWrapper _1.10.3.0 (required for Perfect Vision)_
  Enhanced Terrain Layer _1.0.32_

**Description of issue:**
  If a terrain drawing created with the Enhanced Terrain Layer module is set to "inactive" then the canvas drawing will fail, giving an error related to the terrain layer. The scene cannot be displayed until the Perfect Vision or Enhanced Terrain Layer modules are disabled.

**Steps to reproduce:**
  1. Load modules (default settings are fine)
  2. Create a new scene (default settings are fine)
  3. Select the Terrain Layer (triangle mountain icon), select the "Add Difficult Terrain" (pen icon) drawing tool for the terrain layer
  4. Draw a new polygon of terrain (same as drawing with default Foundry VTT drawing tool)
  5. Select the "Select Difficult Terrain" tool (box corners icon) and double-click to select the terrain you just created
  6. In the configuration window, check the "Inactive" box and click "Update Terrain"
  7. Switch to display a different scene and switch back to your scene (or you can probably just hit F5 to refresh, I guess) 
  8. Canvas will not display, and an error is logged.

**Other notes**
  Specifically it looks like a "drawing.drawDashedPolygon" function for drawing is getting nuked somewhere, and so the calls to that function bomb and it breaks the canvas.  When you set the terrain to hidden, it normally changes the border of the drawing to a dashed line, which is presumably handled by that function.

This didn't use to break, but I don't know exactly when it started. It took some hunting to figure out it was specifically the _inactive_ terrain that was the problem. On one map I had 2 created but inactive as pre-setup for a dynamic portion of a single map (out of 32 separate blocks of terrain). I ended up having to repeadtedly manually edit the exported scene JSON and import/test until I found the offending blocks of terrain. Sadly, disabling the drawing of borders in Enhanced Terrain Layer doesn't work - it would have been a nice workaround.

These are the errors displayed in the console.
![ETL and PV Error](https://user-images.githubusercontent.com/42160122/132104673-93f4a05e-2e61-463f-8055-98b77f418266.PNG)

**Comment by RicoTheBold** [comment]
I have created a corresponding issue for the [Enhanced Terrain Layer module](https://github.com/ironmonk88/enhanced-terrain-layer/issues/55)

**Comment by dev7355608** [comment]
I saw that Enhanced Terrain Layer hasn't been updated yet to address this issue so I included a temporary fix in the latest PV release.
