### ISSUE TITLE
Vision set to display as Scene Darkness does not provide vision

### ISSUE THREAD

**Issue by meticulousDraftsman** [dev7355608/perfect-vision#130]
No modules active besides Perfect Vision and dependency.
Scene darkness is set to 0.75, disabling Unrestricted Vision Range.
A token with a dim vision radius and their 'dim vision in darkness' set to Scene Darkness sees nothing, as though it had no illumination. Same behavior with bright vision, and Scene Darkness (monochrome).
Setting 'vision in darkness' to anything else, like Dim Light or Dim Light (Monochrome) results in expected behavior- vision within the specified radii of the chosen type.
![image](https://user-images.githubusercontent.com/90164607/132150618-32cd1a40-4e21-4842-88de-d73aafb28cbe.png)
![image](https://user-images.githubusercontent.com/90164607/132150560-5adeaa0d-6386-4159-87a1-226cb4d30db7.png)

**Comment by dev7355608** [comment]
Thanks for reporting and sorry for the long wait! Fixed in 2.9.8.
