### ISSUE TITLE
Perfect Vision unuseable on the Forge - most of my scenes washed out

### ISSUE THREAD

**Issue by spetzel2020** [dev7355608/perfect-vision#131]
UPDATED with images:
Was working great on the Forge several weeks ago.

Today after updating to the latest version 2.9.0, most of my scenes are washed out and unuseable: even dark scenes were completely white. Turning off PV fixed the problem.

There were a few scenes which didn't have this problem, but I didn't have time before my session to work out the difference between them and the broken ones.

First is without PerfectVision; washed out one is with just PV and libWrapper enabled.

<img width="671" alt="Screen Shot 2021-09-12 at 2 19 11 PM" src="https://user-images.githubusercontent.com/10853466/132969336-4be35a18-c5f4-4eab-a6d2-a4a4019a89ef.png">
<img width="695" alt="Screen Shot 2021-09-12 at 2 20 02 PM" src="https://user-images.githubusercontent.com/10853466/132969330-1a807d98-bd2f-490c-965f-e81a4dafd380.png">

**Comment by dev7355608** [comment]
Very odd. And it's only on the Forge? Locally this doesn't happen? Does it happen to all your players or just you?

**Comment by spetzel2020** [comment]
Just tried this again and everything is fine. Very weird. Will close for now but reopen if it recurs.
