### ISSUE TITLE
When Token Sight Limit is 0 you can still see tokens with Overlays

### ISSUE THREAD

**Issue by Avitale34** [dev7355608/perfect-vision#134]
So I noticed that when a token has a sight limit of 0 they still can see tokens with "Overlay" conditions on them. Picture for better visual.

![image](https://user-images.githubusercontent.com/65961637/133941848-364f74aa-d7cd-47ca-aa58-e99a9fb9fb38.png)

**Comment by dev7355608** [comment]
I cannot reproduce this. Could you share the scene with me? A token with 0 sight limit shouldn't see any token unless it sits right on top of it.

**Comment by dev7355608** [comment]
If this is still an issue, let me know.
