### ISSUE TITLE
Feature Request: Tremor-sense, Blind Sight, and True Sight - Options for through walls, and concern regarding appropriate status effects

### ISSUE THREAD

**Issue by ArchiusPendragon** [dev7355608/perfect-vision#135]
I understand this might be a significant hurdle, but -

Tremor-sense is frequently ruled to allow sight through walls; but can't see flying creatures.
Blind Sight is... debated to being allowed to see through walls, but a toggle for it to allow DMs to choose depending on the creature (Bats echo-locating through walls would be odd, but Magical Blind Sight might make logical continuity to allow for such)
True Sight being able to see invisible creatures/objects in range.

Invisible/Flying per token may be difficult to manage, and I'm uncertain of the underlying structure, but your mod is one I'm pointed to most frequently with regards to updating and fixing Foundry's vision system. Having these as options would be greatly appreciated.

**Comment by dev7355608** [comment]
Possible in V10 now Vision Modes/Detection Modes.
