### ISSUE TITLE
Prototype token's vision does not apply to the token itself

### ISSUE THREAD

**Issue by Babsobar** [dev7355608/perfect-vision#138]
Hello, 
I'm trying to make this module work but am facing the following issue
Pathfinder 2 edition 2.14.4.8167
FVTT 0.8.9
Latest version of perfect vision

When I edit an actor's prototype token to have him have vision and set his bright vision to 120 and save him, when I place a token on the scene, that token's bright vision is set back to 0.

**Comment by Babsobar** [comment]
Here is a screengrab of the issue at hand https://streamable.com/675ic2

**Comment by dev7355608** [comment]
Is PV the only active module (besides libwrapper)?

**Comment by Babsobar** [comment]
Yes, I tested by disabling all my modules and reactivating only PV and its dependencies.

**Comment by dev7355608** [comment]
PV never sets dim/bright vision settings of a token. Not sure what's happening here. You don't use 
[PF2E Perfect Vision Binding](https://foundryvtt.com/packages/pf2e-pv-binding)?

**Comment by Babsobar** [comment]
Okay, I might be doing something wrong then. 

Giant centipedes have darkvision but when you import the actor from the beastiary and toggle "Has vision" under the prototype token, shouldn't perfect vision give it vision? I had to input bright vision manually on the prototype token for the centipede to be able to see anything. And it doesnt carry over on newly created tokens. 

https://streamable.com/xcybyh Here is another screengrab showing exactly my modules

**Comment by Babsobar** [comment]
A little update: I created an PC actor and gave him the goblin ancestry to check if the issue was linked to monsters or also to players: Turns out players that have an ancestry that has darkvision have the intended behavior, they see in the dark out of the box. 

I tried this with a "goblin warrior" from the compendium, they have darkvision as a passive, but the issue remains for monsters.

**Comment by dev7355608** [comment]
Let me know if this is still an issue once v9 is released. If it's indeed a bug in PV, I'll likely won't fix it in the v8 version.
