### ISSUE TITLE
Feature Request - No Vision in Dim Light

### ISSUE THREAD

**Issue by tjlanza** [dev7355608/perfect-vision#139]
Right now we have settings for how Bright Vision and Dim Vision interact with Bright Light and Dim Light. I'd like to see an additional option added to this matrix. I would like to see an option to control how characters with neither Dim Vision nor Bright Vision see in areas with Dim Light - specifically, a setting that prevents them from seeing at all. In effect, I'd like an option to make Dim Light only useful to people with _some_ degree of improved vision.

**Comment by dev7355608** [comment]
I have to reject this request, because it would be a very big change, barely anyone would use it, and then there's the problem that a lot of light animations, like the torch or pulse animation, change their bright radius over time; those lights would be cut off in an unpleasant/undesirable way.
