### ISSUE TITLE
Token Vision Limit?

### ISSUE THREAD

**Issue by maxipad1991junkmail** [dev7355608/perfect-vision#14]
Loving this module.

Could this module support limiting a particular token's vision to a certain radius? 

For example, tokens can typically see any light sources within their line of sight, but if they are within a fog cloud they should only see 5 feet around them.  Would it be possible for this module to add an option which restricts a tokens sight to 5 ft, regardless of whether or not there are other light sources nearby? Or if they are blinded, limit sight to .1 units (so the player can see their token but nothing around them)?

**Comment by dev7355608** [comment]
Added in v1.3.0.
