### ISSUE TITLE
Compatability issue wit FXMaster

### ISSUE THREAD

**Issue by Ikabodo** [dev7355608/perfect-vision#146]
I've found a strange compatibility issue with Perfect Vision and FXMaster.

1. Apply a filter
2. Zoom out

What happens is that tokens sort of drift away from their original position off to the left...
I think it happens when you zoom out enough to see outside the padding.

![image](https://user-images.githubusercontent.com/7766890/140207715-2d626573-54b5-47fd-8f8e-8e0e7b3ce558.png)

**Comment by Ikabodo** [comment]
![image](https://user-images.githubusercontent.com/7766890/140208065-2b2e8d6e-e4f3-4f2e-8ebc-3a1a59d1c9d6.png)
Here's a better screenshot, where you can see where the token is supposed to be.

**Comment by dev7355608** [comment]
Thanks for the report. Fixed it.
