### ISSUE TITLE
How to make new canvas layer z-compatible with Perfect Vision?

### ISSUE THREAD

**Issue by mcglincy** [dev7355608/perfect-vision#147]
hi - I'm working on a new module called Dungeon Draw (https://github.com/mcglincy/dungeondraw-foundry-vtt) that adds a new DungeonLayer to the canvas, using zIndex -1 in layerOptions() to show the layer underneath the BackgroundLayer (and under any placeable tiles and tokens).

However, when Perfect Vision is enabled, tokens are getting drawn underneath my dungeon layer. I confirmed via the console that my layer is still zIndex -1. I started to dig into the Perfect Vision code, but realized it is non-trivial and thought it might be easier to just ask.

Any ideas how I can make my new layer play nice with Perfect Vision? 

In case it matters, I'm drawing my dungeon layer using PIXI.Graphics lineTo or drawPolygon calls, and using PIXI.TilingSprite for optional floor textures.

thanks!

**Comment by dev7355608** [comment]
Hello! I'm getting rid of PV's crazy separate layer system with the Foundry v9 release, and then I no longer need to add compatibility code for your module and others. I can add some compatibility code to make Dungeon Draw work with PV in v8. I'll take a look tomorrow.

**Comment by mcglincy** [comment]
Awesome, thanks so much! 

Let me know if there's anything I should add to my layer setup to make v8 compatibility easier, or for v9 future-proofing.

**Comment by dev7355608** [comment]
Fixed in 2.10.8.

In v9 there won't be compatibility code required anymore.
