### ISSUE TITLE
Scene thumbnail generation seems broken

### ISSUE THREAD

**Issue by HydrallUrakan** [dev7355608/perfect-vision#149]
For some reason, having Perfect Vision enabled has been preventing me from generating scene thumbnails; hitting the button creates a blank image in the thumbnail directory and also loads all of its tiles on the current scene (at least visually). Very strange issue. No errors in the logs, unfortunately.

**Comment by dev7355608** [comment]
I won't update PV for v8 anymore. It will likely be fixed by the v9 release. I'm closing this, but if the bug is still present once v9 is released, let me know.
