### ISSUE TITLE
Global Illumination Light (none) setting ignores color settings of bright vision.

### ISSUE THREAD

**Issue by omegaghost** [dev7355608/perfect-vision#15]
When you set this
![image](https://user-images.githubusercontent.com/7759628/101236469-85c94100-36e2-11eb-9873-bbe5c5375541.png)
your color settings for bright vision are ignored. In particular I'm using the module with 3.5 system for b/w darkvision, and it stops being b/w.

**Comment by dev7355608** [comment]
There's never a monochrome effect with global illumination enabled because the entire scene is lit, so technically there's no darkness. It's not a bug. With *None* it's just scene darkness.

**Comment by omegaghost** [comment]
I see, that sorta makes sense, but isn't too obvious. Thanks.
