### ISSUE TITLE
Can’t save darkness level in scene configuration in v9

### ISSUE THREAD

**Issue by Zamrod** [dev7355608/perfect-vision#151]
In v9 test 1 if you change the darkness level in the scene configuration and save it then switch to another scene and come back, the setting with be reverted. Tested with PV 3.0 and 3.0.1

**Comment by dev7355608** [comment]
I'm unable to reproduce this.

**Comment by Zamrod** [comment]
Found the cause of this issue. It is unrelated to perfect-vision.
