### ISSUE TITLE
v9: Tokens with dim vision cannot see in dim light in when a scene has a sight limit set

### ISSUE THREAD

**Issue by strongpauly** [dev7355608/perfect-vision#153]
After upgrade, tokens which have a dim vision radius can only see themselves in dim light.  Moving/creating a nearby light source enables their vision.

Using Dungeons & Dragons 5e vision rules and foundry build V9 233.

**Comment by dev7355608** [comment]
I'm unable to reproduce this. Do you get errors messages (F12 -> Console)?

**Comment by strongpauly** [comment]
I have a sight limit set on the scene to 60.  Turning this off (setting it to empty) re-enables vision for tokens with dim vision

Also checked for errors in console, only a warning stating:
`foundry.js:4940 game.data.version is deprecated since V9 in favor of game.version`.
This was with only perfect vision and libWrapper enabled.

**Comment by dev7355608** [comment]
Thanks! Fixed in v3.0.2.

**Comment by strongpauly** [comment]
Tested and looks good!
