### ISSUE TITLE
Unable to update using Foundry 0.8.9

### ISSUE THREAD

**Issue by bonez565** [dev7355608/perfect-vision#154]
Hello, I believe there is a misconfiguration when checking for foundry version. When updating modules Perfect Vision gives an error that it requires core software version 9.233.

![Screenshot 2021-12-07 114927](https://user-images.githubusercontent.com/11901899/144968341-b087504f-8c5d-410f-b156-8613b39cc0e6.png)

**Comment by dev7355608** [comment]
The last PV version that is compatible with v8 is 2.10.8. I already released PV for v9, which is not backwards compatible. You can ignore the warning.
