### ISSUE TITLE
perfect-vision has an error when WeatherBlocker is enabled

### ISSUE THREAD

**Issue by galaara98** [dev7355608/perfect-vision#158]
FoundryVtt 0.8.9
Only perfectvision(2.10.8) , libWrapper(1.11.0.0) enabled, no error
if perfectvision(2.10.8) , libWrapper(1.11.0.0) and WeatherBlocker (0.6.2) enabled

then the game displays an error in red ribbon:
! Perfect Vision: Error detected in module (See JS Console)

no error in the JS console

**Comment by dev7355608** [comment]
WeatherBlocker is not up to date: PV requires WeatherBlocker 0.6.3 or higher.
