### ISSUE TITLE
In V9 Test 3 module fails to load with error

### ISSUE THREAD

**Issue by Zamrod** [dev7355608/perfect-vision#159]
Module fails to load on start up with the following error:
index.js:4 Uncaught TypeError: Cannot redefine property: localTransform
[Detected 1 package: unknown:perfect-vision]
    at Function.defineProperties (<anonymous>)
    at index.js:4

This is with PV 3.0.9

**Comment by dev7355608** [comment]
Fixed in 3.0.10.
