### ISSUE TITLE
geometry.segments.los undefined with Pathfinder 2nd Edition 3.0.1 and Perfect Vision 3.1.7

### ISSUE THREAD

**Issue by leerhund** [dev7355608/perfect-vision#161]
GM view on the left, player on the right.

![PerfectVision](https://user-images.githubusercontent.com/95336883/147081866-a1fd7235-3c4e-4523-9927-0d54b1cb8231.png)

**Comment by leerhund** [comment]
downloaded and replaced with Perfect Vision 3.1.6 and it works correctly with PF2e without error.

**Comment by dev7355608** [comment]
Fixed! Also I noticed that the *Sight Limit* input wasn't even showing up in the token config in PF2e. Fixed that as well. Thanks for the report.

**Comment by leerhund** [comment]
Verified the error on the GM side is resolved. New error when logging in as player.
![image](https://user-images.githubusercontent.com/95336883/147099160-9e99004d-aa7e-4232-ae9e-b760f15b8f18.png)

**Comment by dev7355608** [comment]
Fixed.
