### ISSUE TITLE
Perfect Vision doesn't allow players to see canvas (Foundry v.9, DnD 5e)

### ISSUE THREAD

**Issue by profdresser** [dev7355608/perfect-vision#164]
Hello,
I've got a strange one. So, when I'm logged in as a GM, everything is working fine with Perfect Vision. However, when I log in as a player, all I get is a grey screen. It seems that the player is indeed loaded in; when I run Always HP, their actor's health appears.
![With PV disabled](https://user-images.githubusercontent.com/88245061/147149194-b6a6d2f2-e3ba-4fdb-8945-0b947fc09105.png)
![With PV enabled](https://user-images.githubusercontent.com/88245061/147149255-0ba86712-5c91-4042-833a-44f2ebcfd572.png)

**Comment by dev7355608** [comment]
You need to update PV: 3.1.8 is broken.
