### ISSUE TITLE
Sight Limit only appearing in Scene and Token Configurations and Toggle Delimiters not appearing

### ISSUE THREAD

**Issue by Aggrus** [dev7355608/perfect-vision#165]
![image](https://user-images.githubusercontent.com/40422088/147234928-6d4f2f3a-88a5-4260-9b75-0912bdaa5fa1.png)

![image](https://user-images.githubusercontent.com/40422088/147235053-4ac8306c-7a97-47e7-91c3-79be6c2aff67.png)

Only active modules are Perfect Vision and its dependencies and Tidy UI. Foundry version 0.89, system: DnD5e 1.5.6

**Comment by dev7355608** [comment]
PV 3 is v9 only. You need to update v9 to get the new features.
