### ISSUE TITLE
Thick borders

### ISSUE THREAD

**Issue by Ikabodo** [dev7355608/perfect-vision#168]
Not sure if this is intended or not, but it seems perfect vision is eliminating the blurred effect of lightning on borders. This is with v9 and perfect vision 3.2.5.

With Perfect Vision:
![image](https://user-images.githubusercontent.com/7766890/147396698-3cf37d34-a70b-4511-9d6b-f77664f0ea8d.png)

Without Perfect Vision:
![image](https://user-images.githubusercontent.com/7766890/147396712-c221ad2b-80b6-4926-b5f7-cee84bd22971.png)

**Comment by dev7355608** [comment]
Intentional, see https://github.com/dev7355608/perfect-vision/releases/tag/v3.2.1

This fixes an unpleasant ring effect around light sources, which was especially noticable with low darkness level or light sources with negative luminosity.

The blur effect of lighting border without PV is so large because of technical limitations of current core implementation. PV changes that completely, which removes the large blur effect and vision/light actually reaches walls. With the sight layer change in v3.2.1 it feels a little sharper, because the sight layer now hides the small light falloff completely.

**Comment by Ikabodo** [comment]
Oh. I see, thank you for explaining! I guess it’s one of those situations where you have to pick.

The border is kind of thick to my taste, as it hides the graphical wall on most maps.

**Comment by dev7355608** [comment]
I now see that I forgot to consider something. I didn't notice because my performance settings were high/max, in which case these is an extra blur applied to the lighting. Taking a closer look at your screenshot it looks like you're at medium or low, right?

**Comment by dev7355608** [comment]
I fixed the issue I mentioned above in v3.2.6.

But I have to reevaluate whether this is the best way to fix the ring effect.

**Comment by veithflo** [comment]
I endorse this issue, and adding two unmentioned reasons:
1) Doors aren't visible anymore. They appear as black blurry wall, with a door icon to click. Same for thin walls who are now hidden by the black blur. I can draw walls outside a little more, but i can't do that for doors or thin walls.
2) The black blur also hide the border of selected tokens when the token stands next to a wall. In a dead end or a corner, most of the border is hidden and it's hard to see what token is selected. If the border would be above the black blur it wouldn't be so inconvenient.

I would rather bear with the halo effect than with this black blur covering everything. Hiding the walls & doors makes the maps very unattractive compared to vanilla.

**Comment by dev7355608** [comment]
I reverted the initial halo fix. Now, if Fog Exploration is disabled, the halo effect is reduced greatly without hiding walls and doors by a new technique, but it doesn't work really with Fog Exploration enabled. So with Fog Exploration enabled the fog is just like core (no attempt to fix the halo effect).

Let me know if you have any complaints about how the fog looks with Fog Exploration disabled.
