### ISSUE TITLE
Extreme performance issues

### ISSUE THREAD

**Issue by NateHawk85** [dev7355608/perfect-vision#17]
With the only other module enabled being FPS meter (to track performance), in a scene with a few dozen walls and lights, I get noticeable FPS dips when moving tokens with vision enabled. Even without selecting tokens, it seems that the performance does take quite a hit. Although my system is relatively mid-tier (i7-7700 and GTX 1080), I'm dropping from a consistent 60 FPS to nearly mid-30's at times and an average of roughly 45-50. I have the default D&D5e vision rules enabled, including monochrome for darkvision.

I absolutely _love_ this module, but the performance issues make it hard to justify using, especially since I have players with much worse systems than I do.

**Comment by dev7355608** [comment]
I tried my best to optimize it in v1.2.10. Also I noticed that the performance significantly better in Chrome compared to Firefox and the native app. Let me know how much you FPS improved.

**Comment by dev7355608** [comment]
I had to revert a large part of the performance optimizations in v1.2.11 because of a bug. Something didn't work as expected. I'll keep working on it.

**Comment by Boydbueno** [comment]
A bit of a late reply, but for me the performance issue comes in when I turn on 'Actual Fog of War'. Players have no way of disabling this for themselves. So it's either everyone has it on or everyone has it turned off.
Just keeping it turned off makes things much better for me though.

**Comment by Retrocrow** [comment]
The perfect vision really decreases perfomance. I have top-tier PCand see almost no FPS reduction, but my players notice it without doubts. "Actual Fog of War" is turned off.

**Comment by dev7355608** [comment]
Performance should be massively improved in PV 2.0.0.
