### ISSUE TITLE
Actor with light influences fog of war from other actor

### ISSUE THREAD

**Issue by veithflo** [dev7355608/perfect-vision#170]
Hi there. First, thank you for spending your time making this addon and providing it for us.
I'm new to Perfect Vision, and didn't use it before Foundry v9, therefore I can't say much about it before v9.

If any actor-token with vision emits light on a scene with fog exploration, the emited light also lights up previously explored, but now unseen, areas for players. It doesn't light up areas unexplored for the other players, they stay completly hidden. It only happens when the light-emitting token has vision. It happens during day and night (darkness level), but during day it's barly visible, and during night it's conspicuous. If there is no fog exploration and therefore no fog of war, there is also no issue. If i place a normal light directly on the map, it behaves as it should and will only brighten area in line of sight.

I remember, there was a setting for light type before v9: local, global and universal. With v9 this setting is gone completely. And in the tutorial i watched, the token-emitting-light behaves like global lights and not like a local light. And now with v9 everything is per default a local light, except the token-emitting-light. At least as long Perfect Vision is on. Without Perfect Vision, there is also no issue and the light behaves like a local light.

Here a example, view from GM with selected Character A:
![grafik](https://user-images.githubusercontent.com/32668369/147426129-fcaa4ef1-1975-43ba-aceb-d50bbfa66661.png)

Here same scene, view from Player B with selected Character B:
![grafik](https://user-images.githubusercontent.com/32668369/147426158-24435af8-22b8-45fe-b6af-133d519585fa.png)

Here you can clearly see, the quadrant of Character A is blue due to it's token-light.

Same example without Perfect Vision, view fom GM with selected Charater A:
![grafik](https://user-images.githubusercontent.com/32668369/147426302-285dcaf6-b5f9-4953-9634-0f33c635fcef.png)

... without Perfect Vision, view from Player B with Character B:
![grafik](https://user-images.githubusercontent.com/32668369/147426396-5db4a727-d70c-4514-b13b-bac49e4d5de5.png)

And here you see, the quadrant of Cahracter A is dark because there is no line of sight and therefore no light calculation.

**Comment by veithflo** [comment]
Maybe it has something to do with the recognition of the current players owned tokens. Maybe Perfect Vision assumes all tokens with Vision are legit sources and calculates the fog of war darkness with them instead ignoring vision from not owned sources.

And please ignore the light with vision quadrant, that was just for testing purpose and for curiosity. ("Why is there a Vision, checkbox on Lights but no light-type anymore?")

**Comment by dev7355608** [comment]
Thanks for reporting this! Fixed in v3.2.7.
