### ISSUE TITLE
Desaturation of unilluminated walls leads to grayscale wall-drawing-mode

### ISSUE THREAD

**Issue by veithflo** [dev7355608/perfect-vision#171]
Thanks for fixing #170 so quickly. I can validate the fix works, but i've found something else maybe related to it. Nothing ciristical and no game-breaker, but nethertheless an issue.

The darkness-monochromisation/desaturation also affects wall-lines during wall-drawing-mode. They all turn gray if not exposed to light. All walls who blocks light/sight (basic walls, closed doors, ethereal walls) will be gray, even when exposed to light (as the light is stopped a pixel before them i guess).

![grafik](https://user-images.githubusercontent.com/32668369/147484662-ca9d150c-60fa-4b2c-a318-fe4c2c01a447.png)

**Comment by dev7355608** [comment]
Thanks for the report! Fixed in 3.2.8.
