### ISSUE TITLE
Perfect Visions turns off lighting effects on player views

### ISSUE THREAD

**Issue by Eligarf** [dev7355608/perfect-vision#173]
I placed a few lights placed around a town map, and it all appears as expected from the GM view. However, when logging in as a player, none of the lights were visible until I used Find the Culprit to isolate the behavior to the perfect vision module. If perfect vision is disabled, all the lights show up on the map as expected, and when enabled, no lights show up on the map.

**Comment by dev7355608** [comment]
Could you share this scene with me? (Right-click scene -> Export Data)

**Comment by dev7355608** [comment]
And check the console for error messages (F12 -> Console). I assume it does happen if there's no other module active besides PV (and libwrapper), right?

**Comment by Eligarf** [comment]
No errors in the console for the player vs the GM, and it happens with just PV and libwrapper enabled. I am able to see the the lights as GM in both Chrome and Edge. This is on Forge and I'm using two different accounts for GM and player to make sure no temporary player weirdness gets involved.
[no-lights-for-players.zip](https://github.com/dev7355608/perfect-vision/files/7797433/no-lights-for-players.zip)

**Comment by dev7355608** [comment]
Fixed in 3.2.14. Thanks for the report!
