### ISSUE TITLE
Vision Rules selection disabled

### ISSUE THREAD

**Issue by ctbritt** [dev7355608/perfect-vision#176]
Can't select a new ruleset for vision. See attached screenshot: 
<img width="560" alt="Screen Shot 2022-01-02 at 3 58 25 PM" src="https://user-images.githubusercontent.com/4516034/147889299-7daebce1-f303-4207-9611-1f06567f79be.png">
This is on v3.3.0

**Comment by dev7355608** [comment]
Thanks for the report! Fixed.
