### ISSUE TITLE
Weird Dots Appeared

### ISSUE THREAD

**Issue by JinDaKiD** [dev7355608/perfect-vision#179]
While setting up scenes today, I went to check the video and all of a sudden I am seeing multiple little dots every where.

![Error](https://user-images.githubusercontent.com/82170242/148129162-666a00b0-28bc-473e-9b0a-fa62efd48e88.png)

**Comment by dev7355608** [comment]
That's PV's delimiter overlay. See [here](https://github.com/dev7355608/perfect-vision#scene-controls). You probably pressed the default keybinding by accident (CTRL+H).
