### ISSUE TITLE
Error on v9 build 238 with 3.5e SRD system 0.99.0: This is not a registered game setting

### ISSUE THREAD

**Issue by irbian** [dev7355608/perfect-vision#180]
![image](https://user-images.githubusercontent.com/3071767/148137630-08e4df72-8c7a-40db-85c4-5603e5b88d0f.png)

**Comment by dev7355608** [comment]
That's Health Estimate's fault. But this module should be v9 compatible. Try CTRL+F5 and/or uninstall, then reinstall Health Estimate. That should fix it.

**Comment by irbian** [comment]
It worked reinstalling health estimate, thanks! https://github.com/mclemente/healthEstimate/issues/51#issuecomment-1003080276
