### ISSUE TITLE
Drawing-caused Darkness isn't greyscale when seen with Darkvision

### ISSUE THREAD

**Issue by Bolt7** [dev7355608/perfect-vision#184]
Details:
- Pathfinder 2e system
- Rules-based Vision on
- Scene darkness 0
- Drawing darkness 1 (set in lighting tab, with Override and Active toggled)
- A light is right outside the door (the tokens are on the inside).

Images:
GM perspective
![image](https://user-images.githubusercontent.com/75871317/148693432-0f5e40be-8897-4035-a55a-66e8ff9f2ed2.png)

Creature with darkvision
![image](https://user-images.githubusercontent.com/75871317/148693462-25289d59-1e24-4e39-a86f-758dbca9064c.png)

Creature without darkvision
![image](https://user-images.githubusercontent.com/75871317/148693499-ee434dab-a82c-46b7-b018-1891b652ad0a.png)

Creating with darkvision, when the scene darkness is set to 1 (this is correct, and the saturated part is caused by the light)
![image](https://user-images.githubusercontent.com/75871317/148693540-488dd129-828d-424d-ad23-2dc0e69366ce.png)

**Comment by dev7355608** [comment]
You have to check the override checkbox of *Saturation Level* in this situation, otherwise the drawing inherits the saturation level of the scene, which is linked to the scene darkness and is 1 because the darkness level of the scene is 0.
