### ISSUE TITLE
Conflict with Levels module option

### ISSUE THREAD

**Issue by Dialectikal** [dev7355608/perfect-vision#187]
I've discovered a conflict with the Reveal Token in Fog option in the Levels module.

This option is important, as it allows players to clearly see tokens which they are allowed to target in game. However, if I set a Sight Limit through Perfect Vision, those tokens which would be revealed in fog are still revealed according to the player's normal sight range. This also occurs when creating shapes to override the Sight Limit, such as a circle for Fog Cloud or Darkness.

![PerfectVisionLevelsConflict](https://user-images.githubusercontent.com/31572084/149022696-4133c062-ee9f-4766-87d4-cd9ebdbd1659.png)
.

**Comment by dev7355608** [comment]
Fixed in 3.5.0.
