### ISSUE TITLE
[Bug] Darkness created by deleted Token with sight limit will persist 

### ISSUE THREAD

**Issue by sorrythatuserbla** [dev7355608/perfect-vision#188]
How to reproduce:
Create an acteur with 20 dim light, -0.5 Luminosity, sight limit active
Pull the acteur to the canvas
Remove the acteur from the canvas.

The zone of darkness will persist until the scene is reloaded. Nothing is seen on the light layer. Also it is not visible for the GM. Only visible when you select a token with vision in the scene.

GM View after creating 2 "darkness" tokens and deleting the right one:
![image](https://user-images.githubusercontent.com/78597675/149084517-a346b797-f8da-485a-9151-3df5276feada.png)
Selected a token with vision to see the effect:
![image](https://user-images.githubusercontent.com/78597675/149084595-f5e133d2-0558-442d-b282-bbc1ac271965.png)

**Comment by dev7355608** [comment]
Thanks for the report! Fixed in 3.5.1.
