### ISSUE TITLE
Feature Request - Improvements to Drawing Lighting

### ISSUE THREAD

**Issue by JDCalvert** [dev7355608/perfect-vision#189]
### Drawing Lighting Priority
The 3.5.0 update exposed light priority, so we can have dark lights (e.g. high-level [darkness](https://2e.aonprd.com/Spells.aspx?ID=59) spell) have priority over a lower-level light (e.g. [light](https://2e.aonprd.com/Spells.aspx?ID=171)), or have the higher-level light spell have priority over the darkness.

However, at the moment there isn't a priority on drawing lights. For example, I'd like to create an area of darkness using a drawing, and set its priority, and then that darkness would not be penetrated by lights with lower priority, either from outside or within (and the light inside would not light up outside the darkness either). This configuration could also be done on a scene-level. So most of the scene could be dark with a priority of 100, and only drawings and lights with a higher priority would change it.

### Darkness in Drawing Lighting Blocks Light
It would also be great if there was an option on drawing lighting to make the drawing "block" light from the other side (e.g. how the Darkness spell is described in Pathfinder 2e) similarly to how lights do in 3.5.0. For example, if the drawing set an area of total darkness then:
- A token without darkvision would neither see anything in the darkness or on the other side of it.
- A token with darkvision would see anything in the darkness _or on the other side_ in greyscale.

I made a module [Sense Walls](https://foundryvtt.com/packages/sense-walls) which accomplishes the first point, but not the second.

---

The reasons for asking for these settings on drawing lights instead of using standard lights is:
- Drawing lights can be a custom shape.
- Drawing lights currently interact nicely with darkvision (e.g. those with darkvision can see greyscale into the dark) whereas lights currently do not.

**Comment by dev7355608** [comment]
PV 3.6 is going to be all about magical darkvision and blindsight. There're going to be two types of sight limits: natural (for fog etc.) and magical (for magical light/darkness). Vision can be configured to ignore natural or magical restrictions or both. There will probably be a third type that can't be penetrated by blindsight and magical darkvision.

The order is currently drawings -> templates -> light sources. The reason I don't allow drawings sight limits to be applied after lights is that there would be no visual feedback for that. A light with higher priority would remove the darkness effect of a dark light with lower priority in the overlap, but the drawing wouldn't change the appearance of the light: it would still appear dark, but the sight limit is only applied partially. But there is the [Light/Sound Mask](https://github.com/caewok/fvtt-light-mask) module that allows you to change the shape of a light source. With the help of this module there should be really a need for drawings above light sources, right?

**Comment by JDCalvert** [comment]
That all sounds awesome! Yeah I agree that making lights interact with vision types is better than adding more light features to drawings. I'll close this issue and eagerly await 3.6!
