### ISSUE TITLE
x-ray vision

### ISSUE THREAD

**Issue by rapus95** [dev7355608/perfect-vision#19]
would it be possible to implement a token individual vision modifier that allows for (restricted) x-ray vision as for the x-ray ring or the Ghostly Gaze?
https://5e.tools/items/ring-of-xray-vision-dmg.html (30ft or less depending on material -> variable range, selected by GM)
https://5e.tools/optionalfeatures.html#ghostly%20gaze_xge (flat 30ft incl darkvision)

**Comment by dev7355608** [comment]
I could add a simple option that allows to see through all walls within X ft. This would be a separate option next to dim/bright vision.

**Comment by rapus95** [comment]
As long as it's token based that'd be nice!

Further suggestion: Would you be able to add a "thickness" modifier to walls and a token-individual "wall penetration modifier"? Kinda like customizable terrain walls. That way it'd just be a check of penetration>=thickness && distance<range for a simple case and for a more complex case it would allow cummulative penetration, i.e. penetrate walls and correspondingly reduce the remaining penetration until the view can't penetrate further. (i.e. penetration 10ft could penetrate 10 1ft walls or 1 10ft wall. Though I probably would not use feet for it since it's more about density than about thickness; maybe just keep it dimensionless)
Walls with the thickness not set would default to 1 I'd say if floats are allowed, if integer only I'd default it to 5 or 10 probably

**Comment by dev7355608** [comment]
While it would be possible, I don't want to add this feature at the moment because it would probably be rarely used, and I'd like to keep the module simple and light. But I'll consider to add a simple x-ray vision that penetrates everything.

**Comment by dev7355608** [comment]
V10 Detection Modes make it possible to see tokens through walls.
