### ISSUE TITLE
Sight Limit from Ambient Light sources no longer working

### ISSUE THREAD

**Issue by KenGitsIt** [dev7355608/perfect-vision#190]
This seems to have been broken within the last release or three.  Setting the sight limit on the scene still works, but the sight limit on ambient light sources no longer seems to have any effect.

**Comment by dev7355608** [comment]
There was breaking change regarding the sight limiting behavior of light sources in v3.5. The luminosity changes the behavior now. You can read more about it in the [release notes](https://github.com/dev7355608/perfect-vision/releases/tag/v3.5.0).
