### ISSUE TITLE
Issue: Drawing Example 2: Magical Darkness / Fog Cloud

### ISSUE THREAD

**Issue by Snackpackson** [dev7355608/perfect-vision#191]
When I tried this everything seemed to work perfectly until I moved two tokens next to each other. Sometimes, depending on which direction the token had moved prior to moving adjacent to the other token, the other token would become visible. I noticed a similar issue with being able to sometimes move through wall corners. I assume this has something to do with the sight limit having a hard minimum of 0. It seems that a vision of 0 allows a token to still see itself and the space it occupies and, occasionally, adjacent tokens. Would reducing the minimum to a negative number fix this?

**Comment by dev7355608** [comment]
Please attach a couple of screenshot so I'm sure I understand the problem correctly.

**Comment by Snackpackson** [comment]
![Example_2](https://user-images.githubusercontent.com/84239528/149460965-aca475b3-ac97-4d68-94f8-94306a690d27.PNG)
![Example_1](https://user-images.githubusercontent.com/84239528/149460969-e9f35184-3391-4458-9c4c-333e280bba4f.PNG)
![Truth](https://user-images.githubusercontent.com/84239528/149460971-0fb1ff12-fa0e-453c-a68a-67d66df8942f.PNG)
![Example_3](https://user-images.githubusercontent.com/84239528/149460976-2041e161-8acf-4ad8-be56-9f4bd2949f95.PNG)

**Comment by Snackpackson** [comment]
You can see that an adjacent token is visible
When diagonal from the other tokens I wasn't able to see the others.
In DM view, with no token selected, you can see all of the tokens.
When I moves around a bit and came back, the other adjacent token was visible instead.

I was told that the wall issue I mentioned above might be associated with floating point rounding on the token position as it completes its move. I suspect this is similar. Thank you!

**Comment by Snackpackson** [comment]
Is there any option to make certain tokens immune or partially immune to the effects of this circle? The token I selected in the examples above is supposed to have D&D 5e Warlock Evocation called Devil's Sight, making him able to see through the darkness. Another token from the examples is meant to have Tremorsense and would Ideally be able to "see" anything within a 10ft radius of the token regardless of lighting effects. I really appreciate the work you're doing and, though my coding experience is very minimal, I am happy to help any way I can. Please let me know if I can assist you in any way.

**Comment by dev7355608** [comment]
This is related to the origin offset I described in #193 and PV's circle visibility test. I'll have to see what can be done about this particular situation.

Devil's Sight and Blind Sight / Tremorsense is coming in version 3.6.

**Comment by dev7355608** [comment]
Fixed in 3.5.2.
