### ISSUE TITLE
Feature request: Additional tint option(s) associated with other brightness and vision capability combinations.

### ISSUE THREAD

**Issue by Snackpackson** [dev7355608/perfect-vision#192]
I was looking for a simple way to allow players to determine the true lighting of an area regardless of how their token's vision capabilities when someone recommending this module to me. If there were tint options associated with each vision type and lighting level, a color could be associated to each. This would perhaps be the quickest and easiest way to allow players to do what I hoped to allow them to do, notice dim lights in darkness when they have darkvision.

If a second tint color could be tied to the Dim Vision in Dim Light and Bright Vision in Dim Light options, I think that would provide what I desire!

**Comment by dev7355608** [comment]
So do you want your players to be able to tell if something is dim light, but it isn't important that they actually see how it looks in dim (instead of bright)? Or would you want your darkvision players to be able to see the scene without their special senses temporarily?

**Comment by Snackpackson** [comment]
If they are looking down a passageway filled with dim light with darkvision it appears the same way it would if they were looking down a passageway filled with bright light. There is no way for them to tell the difference with manually changing their vision or selecting a different token.

**Comment by dev7355608** [comment]
I might consider adding a keybinding such that vision is rendered normally (without enhancements) while the key is held down. This is probably the best solution.

**Comment by Snackpackson** [comment]
That would certainly be appreciated, though I would prefer the second tint instead. Some maps may have many more instances where visible light could be used by the DM to provide information/clues. It would be much easier if players didn't have to remember to toggle their vision every time they view a new area.

**Comment by dev7355608** [comment]
I won't add a tint option because that would mean loss of color information, and I don't want to trade brightness information for color information. If you want players to be able to tell the difference between dim and bright light always, just change the vision rules to *Dim/Bright Vision in Dim Light* = *Dim*. Then lights are rendered normally, but you and your players have to keep in mind that dim light within range applies no penalties.

**Comment by Snackpackson** [comment]
Alright, well I appreciate your consideration and respect your decision to not pursue this. However, I feel that you have already made a trade that costs users brightness information. Perfect vision currently gives users the option to trade aspects of the map's true brightness information for oversimplified representations of individual perspectives. Darkvision shouldn't make dim light indistinguishable from bright light. It just means that dim light should be treated as bright light in a mechanical sense (at least in 5e D&D). If your module can provide users with a quick and easy way for differentiating brightness information and representations of individual perspectives without sacrificing truth data regarding the map's true brightness, I think your vision for Perfect Vision may be closer than ever to being realized. I think being able to toggle Perfect Vision off and on would work but I would personally prefer it if I could just see the differences without toggling. I mean no disrespect and I truly appreciate you and you mod but the only aspect of Perfect Vision that works ideally in my opinion is the Dim Vision in Darkness and I usually give it a color tint to help make the difference more distinguishable for my imperfect human eyes.

**Comment by dev7355608** [comment]
With V10 Vision Modes this isn't a PV-specific issue anymore. At  the moment I have no plans for PV to add or modify vision modes, which includes this issue presented here.
