### ISSUE TITLE
Unresponsive UI with 3.5.1 (exception)

### ISSUE THREAD

**Issue by JimKuhn** [dev7355608/perfect-vision#194]
I've dropped from a (clamped) 30fps to **~0.07fps** when Perfect Vision is enabled.  If I disable the module, I'm back to 30fps.

The most recent version I had prior to upgrading would have been 3.39 or 3.40 (I update ~weekly).  Everything was working fine at that point.

I'm running FoundryVTT 9.242 w/5e 1.5.7

PerfectVision is set to use the default 5e settings.

I just tried disabling **ALL** modules except perfect-vision (and the required libwrapper), and the problem persists.

Browser is Chrome (on Windows) Version 98.0.4758.54.  I also tried on Version 97.0.4692.71 (on a different machine).  Same result.

**Comment by dev7355608** [comment]
Any error messages or a lot of warnings? (F12 -> Console)

Is the FPS bad a freshly created world/scene as well? Or only in a specific scene?

**Comment by JimKuhn** [comment]
In a completely blank scene, https://github.com/dev7355608/perfect-vision/blob/691ef7e1aabea934d93ac31b2522650af501fbe1/scripts/core/point-source/shader.js#L113 throws an exception when I select a token with vision.  This may not be the _same_ problem, as it seems to completely break the ui:

```javascript
shader.js:113 Uncaught TypeError: Cannot read properties of undefined (reading 'worldTransformInverse')
[Detected 1 package: perfect-vision]
    at AdaptiveIlluminationShader.AdaptiveLightingShader.update (shader.js:113:46)
    at r._renderDefault (mesh.min.js:8:3307)
    at r._render (mesh.min.js:8:3195)
    at r.e.renderAdvanced (display.min.js:8:20105)
    at r.e.render (display.min.js:8:19492)
    at e.render (display.min.js:8:19591)
    at e.renderAdvanced (display.min.js:8:20176)
    at e.render (display.min.js:8:19492)
    at e.renderAdvanced (display.min.js:8:20176)
    at e.render (display.min.js:8:19492)
    at e.render (display.min.js:8:19591)
    at LightingLayer.e.render (display.min.js:8:19591)
    at EffectsCanvasGroup.e.renderAdvanced (display.min.js:8:20176)
    at EffectsCanvasGroup.e.render (display.min.js:8:19492)
    at e.render (display.min.js:8:19591)
    at r.render (core.min.js:8:123688)
    at t.render (app.min.js:8:355)
    at t.emit (ticker.min.js:8:573)
    at e.update (ticker.min.js:8:3424)
    at _tick (ticker.min.js:8:1433)
```
This exception also happens in the original scene.

**Comment by dev7355608** [comment]
No other errors?

Uninstall and reinstall PV, then force refresh the cache, so we can rule out cache problems.
![image](https://user-images.githubusercontent.com/31905376/149586764-6b174d72-8890-48a6-8de6-12cf26000868.png)

**Comment by JimKuhn** [comment]
Same result.

**Comment by dev7355608** [comment]
What about other error messages? There should more before that error message you posted.

**Comment by JimKuhn** [comment]
The last message prior to that is just:

```
Foundry VTT | Activating pending audio playback with user gesture.
```

**Comment by dev7355608** [comment]
Just to make 100% sure: no errors (nothing red) before this error message at all?

**Comment by dev7355608** [comment]
I just heard of a critical libWrapper bug: make sure libWrapper is up to date (1.11.4.0).

**Comment by JimKuhn** [comment]
That might be it.  I updated everything at the same time earlier today, but libWrapper is 1.11.3.0

**Comment by dev7355608** [comment]
libWrapper needs to be 1.11.4.0; 1.11.3.0 is broken. If it doesn't want to update, uninstall and reinstall libWrapper.

**Comment by JimKuhn** [comment]
Ugh... they were released close together... "2 hours ago" on github.  I must have hit the window perfectly.  Sorry for the wild goose chase... it's working perfectly now :-(
