### ISSUE TITLE
Version 9 Foundry issue screen locks up.

### ISSUE THREAD

**Issue by mark-drury** [dev7355608/perfect-vision#196]
Running foundry version 9.242 through Forge and perfect vision version 3.5.3, the map opens OK but when I right click and drag to move the map it locks up after moving the map a short distance. When I disable the module the problem goes away, and returns when re-enabled. When I updated the worlds and it loaded up for the first time the map was blank, found to be Perfect Vision module causing that issue too.

**Comment by dev7355608** [comment]
It's probably a caching issue. Try this:

![image](https://user-images.githubusercontent.com/31905376/149838007-3367f1f0-66a3-46bb-9991-a897802b4fe1.png)

**Comment by dev7355608** [comment]
I assume the cache refresh fixed the problem. If not, let me know.

**Comment by mark-drury** [comment]
It did fix it, thanks for the quick response, and I’m sorry I didnt reply sooner, the message went into my junk and I missed it.

Mark
