### ISSUE TITLE
Token's sight limit doesn't work

### ISSUE THREAD

**Issue by Ddinistrioll** [dev7355608/perfect-vision#198]
I can't change the sight limit in the token vision configuration.

I'm on Pathfinder 2E, and I use Rule Based Vision.

I can change the sight limit for the scene, in the light configuration, in the drawing configuration, and even in the token light configuration, but the input field in token vision configuration doesn't seem to be enabled (It doesn't react when I click on it).

**Comment by dev7355608** [comment]
It's disabled, because it's automatically managed if RBV is enabled: it's either unlimited or 0 depending on the blinded condition.

Do you want to use token sight limit for something other than blindness?

**Comment by Ddinistrioll** [comment]
Yeah, we like to sometimes mess with it (always special occasions)

My players are loving the vision shenanigans I do sometimes. But obviously, having vision limited to 30ft (for instance) for a combat is very different from having blinded vision. Most of the time I can do it via the lights/drawings (when I want a localised vision limiter), but sometimes I only want one player to experience it.

I don't think removing this option (and removing it only for token vision setting) is necessary, as RBV is already managing the vision radius. It's only limiting the options we have. 

Btw, PV is probably in my top 3 favorite modules, so good job on this!

**Comment by dev7355608** [comment]
I unlocked token sight limit in 3.5.5. The blinded condition still forces the sight limit to 0 while the actor has the condition, but doesn't override the sight limit that was previously set.
