### ISSUE TITLE
Newest Release broke the ability to adjust Tile resizing.

### ISSUE THREAD

**Issue by Ssezra** [dev7355608/perfect-vision#199]
(DND5e) The latest release broke the ability to adjust tile resizing. A tile can be placed but cannot be resized afterwards. Tiles also bug out rendering any new tiles being added. (3.5.5 and 3.5.4)  This is fixed by uninstalling perfect vision or using an older version. 3.5.3.

**Comment by dev7355608** [comment]
Thanks for the report. I moved the tile border to a different layer so that it is not affected by lighting or the monochrome filter, but that breaks the resizing handle. It seems like it won't be so simple after all, that's why I reverted the change for now. Fixed in 3.5.6.
