### ISSUE TITLE
Reduced pixel density when a token with darkvision is selected

### ISSUE THREAD

**Issue by silvative** [dev7355608/perfect-vision#2]
Hi, and congratulations on the mod launch!

I've been noticing that the vision of selected tokens appears compressed or mipmapped somehow in a fairly unattractive way. It's only noticeable on high pixel density maps (mine are all 256, a friend couldn't replicate on 61 until he turned up to 256 as well). It's hard to capture in video because it looks like poor compression, but it's even harder to describe with words, so:

![gif](https://user-images.githubusercontent.com/66365038/99314754-77ada080-2859-11eb-9666-fb1f0bcdf1f7.gif)

As you can see even though the video is a little compressed it's clearly getting worse when I select/deselect the token. It's very noticeable ingame especially zoomed out (invisible zoomed all the way in). Of course this only occurs with the mod on. FXmaster disabled and Greyscale filter off don't change the results you see here.

My settings if you want to recreate:

![image](https://user-images.githubusercontent.com/66365038/99315163-2520b400-285a-11eb-8b6d-158a852be58c.png)

I also have the core antialiasing turned off, but that shouldn't be toggling based on token selection anyway. Is it possible the mod is turning it back on somehow?

**Comment by silvative** [comment]
Breakthrough! Lordufreeman worked it out!
I have 125 percent scaling in Windows on my 1440p monitor for readability when I'm not using my glasses. After setting that to 100 percent and refreshing my browser the issue disappeared!

So I guess clarifying this one to have a known trigger condition c:

**Comment by silvative** [comment]
Seems to also exist with just font scaling instead of total scaling which is really strange. This is still happening if it's the only other mod installed btw- foundry 0.7.7 and the latest pf2e version.

**Comment by dev7355608** [comment]
I haven't looked into this issue yet. I'm hoping it was somehow solved in the newer releases. Please tell me whether this is still an issue.

**Comment by silvative** [comment]
Still visibly happening for me after updating :c 
![output](https://user-images.githubusercontent.com/66365038/99910475-2c2a4500-2ce6-11eb-9d10-5e16feb5e200.gif)

**Comment by dev7355608** [comment]
I figured out that this is an issue that affects other modules that use filters as well. The resolution of filters is not properly adjusted if the scaling is not at 100%. I reported the problem with a solution to the Foundry devs [here](https://gitlab.com/foundrynet/foundryvtt/-/issues/4176).
