### ISSUE TITLE
Having a weird overlap of light and monochrome

### ISSUE THREAD

**Issue by Avitale34** [dev7355608/perfect-vision#20]
Having a weird overlap of light and monochrome in the newest update. If you have someone producing light and someone with darkvision in the same room I am getting this kind of overlay. The selected character does not have darkvision but looks like he is seeing through it.
![image](https://user-images.githubusercontent.com/65961637/102183229-7d5bcd80-3e7b-11eb-9651-251840cdc0fd.png)

**Comment by Avitale34** [comment]
![image](https://user-images.githubusercontent.com/65961637/102183717-4639ec00-3e7c-11eb-9d82-5a1dba960372.png)

**Comment by dev7355608** [comment]
Fixed in v1.2.11.
