### ISSUE TITLE
Feature request - Separate saturation options for unilluminated areas and monochrome vision

### ISSUE THREAD

**Issue by hoyer1066** [dev7355608/perfect-vision#200]
At the moment you have to choose a single saturation level that effects both unilluminated areas and monochrome vision.

This means in order to have the "see in grayscale" part of darkvision etc visible on the scene, your normal darkness also needs to be monochrome. This creates a harsh cut off between the monochrome darkness and coloured illuminated areas, which is quite ugly and also negates a lot of foundry's lovely blended lighting - this works well for intentional monochrome vision as it highlights the difference between the illumination levels, but a negative for general unilluminated areas.

This is particularly noticeable and mostly a problem on any non-battlemap and Theatre of the Mind scenes or any scene not using Token Vision.

My proposed solution is simply to have two options in Configure Scene -> Lighting, one for 'Unilluminated Area Saturation Level' and one for 'Monochrome Vision Saturation Level'. They would both work just like the 'Saturation Level' does now, with a toggle button and a slider, but would each only effect their particular case.

_Battlemap, Saturation = Darkness, Normal Vision_
![Battlemap_Saturation-Darkness_Normal-Vision](https://user-images.githubusercontent.com/77966438/150273356-81242c64-589b-448a-a8c4-5ae47307988a.JPG)
_Battlemap, Saturation = Darkness, Darkvision_
![Battlemap_Saturation-Darkness_Darkvision](https://user-images.githubusercontent.com/77966438/150273355-f2d23a9d-e568-42c8-8711-dce27bd1cbbc.JPG)
_Battlemap, Saturation = 1, Normal Vision_
![Battlemap_Saturation-1_Normal-Vision](https://user-images.githubusercontent.com/77966438/150273351-f01b2872-d0ad-4667-91bf-6053ad777065.JPG)
_Battlemap, Saturation = 1, Darkvision_
![Battlemap_Saturation-1_Darkvision](https://user-images.githubusercontent.com/77966438/150273362-1207ff03-3158-4318-a4f8-075e7fed7afd.JPG)
_Image Scene, Saturation = Darkness, No Token Vision_
![Image-Scene_Saturation-Darkness](https://user-images.githubusercontent.com/77966438/150273360-a58dcced-ebc7-407a-ba77-fa3ca7d85146.JPG)
_Image Scene, Saturation = 1, No Token Vision_
![Image-Scene_Saturation-1](https://user-images.githubusercontent.com/77966438/150273359-77913576-edd3-4f43-8cc6-0e6d8d11b7b5.JPG)

[Battlemap images are taken using my preferred custom settings for Perfect Vision - Dim Vision in Darkness = Scene Darkness (monochrome), Dim Vision in Dim Light = Dim Light. This does mean it looks different to how it does with the standard Dungeons & Dragons 5e settings, but if anything it's even more apparent with the standard settings.

**Comment by dev7355608** [comment]
Preview:

*Current version*
![image](https://user-images.githubusercontent.com/31905376/150409341-de18ecc8-48a2-4e2c-b17e-8b6e9cca56de.png)

*With gradual saturation falloff*
![image](https://user-images.githubusercontent.com/31905376/150409272-e243e609-db16-4cb8-9323-d6b1d269d3d0.png)

**Comment by dev7355608** [comment]
New blending of gradual lights and vision in 3.5.7. I consider this fixed, but feel free to give feedback.
