### ISSUE TITLE
Perfect Vision hides scene padding boundaries

### ISSUE THREAD

**Issue by HydrallUrakan** [dev7355608/perfect-vision#201]
As shown - 
Without Perfect Vision
![image](https://user-images.githubusercontent.com/94702225/150558275-9f8798c6-5baf-4e05-ae2c-afd5512f5fc7.png)

With Perfect Vision
![image](https://user-images.githubusercontent.com/94702225/150558377-96946ea8-48ef-451f-b969-35de14bca1af.png)

I would like to be able to see the boundaries of the map as a DM, particularly when building maps out of tiles instead of static background images. Seems like it happens regardless of settings or the GM Vision option being toggled on or off.

**Comment by dev7355608** [comment]
Thanks for the report. Fixed in 3.5.7.
