### ISSUE TITLE
Blindsense Implementation

### ISSUE THREAD

**Issue by maxipad1991junkmail** [dev7355608/perfect-vision#203]
Would it be possible to implement a form of blindsense per PF1e or PF2e? Blindsense gives rough location information but not distinguishing features. My suggestion would be a toggle in token vision settings for blindsense which renders all unseen tokens within a specified area a single flat color.

I recently had a player who has blindsense get blinded. Currently we handle this by giving them restricted vision to 30 ft (which is awesome.) However this also gives the player a lot of additional information their character wouldn't have, because blindsense is imprecise. In this case, I'd love it if they couldn't tell who their friends and foes were if they left the limited vision range and had to chase after them.

In action, the blindsense could give a token vision out to specified distance (30ft) that would show only tokens the character's normal sight does not see (whether due to lighting, fog clouds, blindness, or possibly a token being toggled as unseen.) Blindsense would paint tokens that aren't visible to "normal" sight a single color (electric blue for example) so it's clear that they can't see the token normally.

This would work well for me since I use round tokens with character art, but might work less well for top down tokens. However, I still think it would be useful in those cases, displaying a limited but meaningful level of information to players.

**Comment by dev7355608** [comment]
Blindsense/blindsight is coming, which allows you too see through sight limited areas (fog / magical darkness), but it won't have any visual downsides. What you are asking would be a lot of work and that wouldn't be worth it considering that blindsense/blindsight are probably rare senses a player character would have; also some forms of blindsight are 100% accurate, so it would need an extra setting, and that would make it more complicated. I have ask you to pretend the vision is imprecise or that you can't tell friend from foe.
