### ISSUE TITLE
pixi.js not present in scripts folder

### ISSUE THREAD

**Issue by tagnullde** [dev7355608/perfect-vision#205]
Apparently you are importing pixi.js from the scripts folder. However pixi.js isn't present in the new update and throws an error in foundry.

![grafik](https://user-images.githubusercontent.com/44159008/151372377-e9932f1d-d2bb-407f-8809-7f19f7efbdee.png)

![grafik](https://user-images.githubusercontent.com/44159008/151372539-c9bf2b60-8841-4598-8b2c-da7de5e9b009.png)

![grafik](https://user-images.githubusercontent.com/44159008/151372288-584e9a78-9b7e-4a4c-9a70-125db5631013.png)

**Comment by dev7355608** [comment]
Thanks for the report! Fixed it.
