### ISSUE TITLE
GM Vision no longer disables desaturation

### ISSUE THREAD

**Issue by AvDalfsen** [dev7355608/perfect-vision#206]
I was working on some maps this afternoon and things were working fine. When I came back just now, after updating all the modules, I realised that the GM Vision button no longer disables the desaturation, but instead just increases the brightness.
GM Vision off:
![image](https://user-images.githubusercontent.com/42408840/151675052-f576178c-5bb4-4caf-87ce-fa146ebed2a2.png)

GM Vision on:
![image](https://user-images.githubusercontent.com/42408840/151675059-76a29a90-a7e6-4944-a391-6f6f0f49053f.png)

This afternoon I could see the blue water, the brown piers, etc.

**Comment by dev7355608** [comment]
Thanks for the report! Fixed it.
