### ISSUE TITLE
Everything is suddenly in greyscale

### ISSUE THREAD

**Issue by simondw2000** [dev7355608/perfect-vision#207]
I have just done a module update and now all of my maps without lighting effects are in greyscale. This includes maps that are not set to use token vision, and are in full daylight mode, and should therefore be completely visible and in colour to everyone.

Disabling Perfect Vision seems to be the only way to fix this issue.
No console errors.

**Comment by simondw2000** [comment]
Additional info...
This is only affecting older maps. Anything new does not have this issue.

I've also found another way to fix it. I can tick and untick the "Unrestricted Vision Range" option for a map and it fixes it.

**Comment by dev7355608** [comment]
What's *Saturation Level* set to in those scenes?

**Comment by simondw2000** [comment]
![image](https://user-images.githubusercontent.com/30345746/151812446-69db1cd1-4f7c-44af-82ef-0d2ec803359b.png)

This is from one that had the issue after updating, but I have now enabled and immediately disabled "Unrestricted Vision Range" so it's now fixed.

I have never touched the "Saturation Level" option on any of my maps so far.
