### ISSUE TITLE
Compatibility with Levels: Vision Zones apply to wrong Levels (v9)

### ISSUE THREAD

**Issue by kitt-schlatter** [dev7355608/perfect-vision#208]
Right now on v9 of foundry, by default any drawn polygons which have lighting configured will appear to apply to all defined levels regardless of what top and bottom elevations are set for that polygon; however, if you modify a lighting polygon in some way (move it, change a property, etc.) then the lighting effects start properly applying according to the levels specified for that polygon and for whatever level the currently selected token(s) should see.

The lighting conditions then stay "locked in" if you swap (tab) to another token at a different level. This can be "fixed" again by modifying the lighting polygon(s) to "refresh" them in your view, but once again tabbing to another token leaves their view "locked in" to this new state.

I'm not sure what the expected behavior with Levels is, but considering you can get lighting polygons to respect levels with a "refresh" of the polygon, I'm assuming lighting settings are meant to respect the levels they're set for. Either way, it seems like some aspect of this overall behavior is bugged.

**Comment by dev7355608** [comment]
Thanks for the report! Fixed.
