### ISSUE TITLE
[Suggestion] Custom Vision Rules

### ISSUE THREAD

**Issue by DeViMoRPh** [dev7355608/perfect-vision#21]
Hello!

First of all thanks for the module! 

It's amazing to have the ability to customize the vision per character. In our setting each race has very distinct vision similar to 3.5e.

![image](https://user-images.githubusercontent.com/76123707/102389051-e6098e00-3fd2-11eb-9689-0f19a6a39c21.png)

I was wondering if it would be posible to do something like this.

I'd love to have the oportunity to:

1. Set the vision range on each scene lighting of Global Ilumination. Thanks to your module I can do some customizations in how they see but I still have to set up the vision range for each scene.

2. Have another option for the scene lighting. Thanks to your module I can set it up to **darkness** and **dim** (penumbra in the image). Right now, Foundry gives infinte vision range to all characters in Bright Light. In my setting, for example, drows see really bad at daylight (like humans in darkness) and I haven't been able to simulate that (other than give infinite vision to all and limit the drow but I can't use lights with this trick).  Would it be posible to add **daylight** in Global Ilumination as well as a third option?

The second point might be too specific... but I think the first point would be a nice addition to everyone.

Again, thanks for all your work!

**Comment by dev7355608** [comment]
I'm going to add an option that allows to set the maximum vision radius of a token in v1.3.0 so that they cannot see beyond the specified radius. Would this partly solve (2)?

(1) could be mostly solved if it was possible to specify formulas in the dim/bright vision fields, I think. Not sure that's possible at the moment. I'll have to look into it.
