### ISSUE TITLE
No map renders any more

### ISSUE THREAD

**Issue by TimWerdin** [dev7355608/perfect-vision#211]
If I enable the module in a world no map is rendered any more and I see a red banner with the message:
`Canvas drawing failed for LightingLayer`.
I'm using Foundry 9.249 with Perfect Vision 3.6.10 and libWrapper 1.12.3.0

**Comment by dev7355608** [comment]
Please open the console (F12 -> Console) and look for the detailed error message (anything red). Let me know what it says.

**Comment by TimWerdin** [comment]
After unloading the module and loading it again multiple times it now works. If I would encounter the issue again I will look into the console
