### ISSUE TITLE
Feature Request: Collapse Category on deselect

### ISSUE THREAD

**Issue by the-real-orson** [dev7355608/perfect-vision#212]
I prefer to click on categories over hovering, but having the category remain open after clicking on it can get frustrating.  Would be great if either the default behavior was to close the category when switching/deselecting token or have that as an option in the settings.

Love the HUD!!!!

**Comment by dev7355608** [comment]
I'm confused: what categories are we talking about here?

**Comment by the-real-orson** [comment]
Items, Spells, Checks, Saves....etc.

**Comment by the-real-orson** [comment]
Oh shit, I'm on the worng GIT!!!!!  fuck me, sorry

**Comment by dev7355608** [comment]
All good!
