### ISSUE TITLE
Day/Night Support?

### ISSUE THREAD

**Issue by keyxmakerx** [dev7355608/perfect-vision#215]
So I maybe missing something, but my tokens currently can't see in the day time. I've tried both 5e and custom settings, where bright vision for darkness is total darkness, and bright vision in dim light is bright, but it only gives them vision of 5 ft. Not sure how to fix, or if i'm doing something wrong?
![Screenshot from 2022-02-13 14-27-09](https://user-images.githubusercontent.com/2086621/153773555-594d0dfa-4996-417b-89dd-364c079cc5c0.png)

**Comment by dev7355608** [comment]
Enable Unrestricted Vision Range (scene configuration) for daylight scenes. No need to modify the token vision settings. Even if Darkness Level is 0, that doesn't mean that the scene is filled with light and tokens can see everything. But if Unrestricted Vision Range is enabled, tokens can see as if everything was filled with light. You can link Darkness Level and Unrestricted Vision Range with the Vision Limitation Threshold setting. Those are all core lighting settings, not Perfect Vision specific settings (but you can them configure those locally with Perfect Vision's lighting drawings, if you want to, for mixed indoor/outdoor scenes, for example).
