### ISSUE TITLE
Compatibility with Monk's Little Details: Vision Zones apply to wrong Levels (v9)

### ISSUE THREAD

**Issue by DarKDinDoN** [dev7355608/perfect-vision#216]
Hello,

FVTT 9.249
5e 1.5.7
Perfect Vision 3.6.16

Using Monk's Little Details with these settings:
![image](https://user-images.githubusercontent.com/1687854/153934415-3b79384f-cd1a-440a-b99b-b11d1f0dc9fd.png)

GM vision ✅ 
![image](https://user-images.githubusercontent.com/1687854/153934496-e5648b37-0842-41f2-8fa3-7b13320b50c1.png)

Player vision ❎ (highlight is above token)
![image](https://user-images.githubusercontent.com/1687854/153934544-c807fb30-ce66-43b5-b316-1cea327331ea.png)

**Comment by dev7355608** [comment]
I assume you have the Levels module enabled and the selected token has a higher elevation than other tokens. Is that correct? Without the Levels module this shouldn't happen.

**Comment by DarKDinDoN** [comment]
@dev7355608 No, levels is not installed.
I tested with only perfect vision and Using Monk's Little activated

**Comment by dev7355608** [comment]
I'm unable reproduce it. Can you spot any error messages in the console (F12 -> Console)?

**Comment by DarKDinDoN** [comment]
@dev7355608 ok, I know what is the issue.
When I'm testing things, I'm always opening another window on my secondary screen.
My secondary screen is in portrait mode, meaning the width is < 1024px.
The bug appears below 1024 :)

**Comment by dev7355608** [comment]
Could you explain a bit more what you mean by "below 1024". I tried all kinds of window dimensions, but I'm still unable to reproduce this.

No errors in the console?

**Comment by DarKDinDoN** [comment]
@dev7355608 No error in the console.

![image](https://user-images.githubusercontent.com/1687854/153961526-cbce456e-9776-428a-9c5f-17660c396cdb.png)
![image](https://user-images.githubusercontent.com/1687854/153961529-4c50e60a-e80c-49bd-b6ed-62d2685f849c.png)
![image](https://user-images.githubusercontent.com/1687854/153961532-7082ff91-11e9-4f88-b979-2051b03c5d7b.png)

It's actually happening at specific resolution. I could reproduce by slowly reducing the Chrome window width.
Sorry for the vague explanation :D

**Comment by dev7355608** [comment]
Looks like the browser zoom level or windows scaling is at something other than 100%. What is it set to?

**Comment by DarKDinDoN** [comment]
Windows scaling is set to 105%.

**Comment by dev7355608** [comment]
Fixed. Thanks for the report!
