### ISSUE TITLE
Darkvision overlapping with light sources creates darkness colored border.

### ISSUE THREAD

**Issue by the-real-orson** [dev7355608/perfect-vision#217]
Example scene....

Here is a shot of the light sources (they look nearly identical with or w/o PV activated):
https://photos.app.goo.gl/nnsD68RvDrbGnLJDA

Here is a shot with PV activated and TestPlayer's darkvision overlapping (whether using 5e monochrome or custom, visible purple halo is visible):
https://photos.app.goo.gl/syrQDKdhT87Fb6bM7

Here is a shot with PV deactivated and TestPlayer's darkvision overlapping:
https://photos.app.goo.gl/VrgH2sbPgka4KnkW8

To me this looks pretty awful in play, not sure if it is supposed to look like this, I don't think so because I recall deactivating PV after installing Foundry 9.245 for this reason.

**Comment by dev7355608** [comment]
That doesn't look right. Could you export the scene and share it with me? Scenes Directory -> Right Click -> Export Data

**Comment by the-real-orson** [comment]
[fvtt-Scene-mine-below-ground.txt](https://github.com/dev7355608/perfect-vision/files/8065056/fvtt-Scene-mine-below-ground.txt)

**Comment by dev7355608** [comment]
I can't reproduce it. Double check that PV is up to date (v3.6.17). And check the console for errors please (F12 -> Console).

**Comment by the-real-orson** [comment]
ooops...looks like I'm still on 3.6.15, no errors in console, will report back after update

**Comment by the-real-orson** [comment]
No change after update, no errors in console.

**Comment by dev7355608** [comment]
Any warnings in the console with "WebGL" in it?

**Comment by the-real-orson** [comment]
Negative, just some mid-qol warnings from modules not installed.

**Comment by dev7355608** [comment]
Could I possibly connect to your world for further investigation?

**Comment by the-real-orson** [comment]
you bet, sent you an email

**Comment by dev7355608** [comment]
Fixed. Thanks for the report!

**Comment by the-real-orson** [comment]
Awsome!! thank you!
