### ISSUE TITLE
Feature Request: Backlit? vision

### ISSUE THREAD

**Issue by ravingdragoon** [dev7355608/perfect-vision#218]
I was hoping there might be a way that you could implement something like dim vision in areas of darkness when there is a light source on the other side. For instance, this would make it so a creature with vision would see dimly in a hallway if there was a light source at any point within its sight limit, as would happen in reality where you would see objects/creatures as backlit if there was a light source you could see anywhere behind the objects/creatures.

**Comment by dev7355608** [comment]
Do you want that tokens block vision/light? Either way, the creature might be prone or pressed against a wall (hiding) or transparent (ghost): in these and others cases you probably wouldn't want the creature to be backlit. But that's practically impossible to automatically detect whether to backlit. The GM would need manual control over this. So the best way is to simply ignore those physics completely, or as GM ping on the map for the players where they see a shadow in between them and a light source.

**Comment by dev7355608** [comment]
Do you want this?: (token left / light right)
![image](https://user-images.githubusercontent.com/31905376/155809425-588be38c-fc8e-42ff-821d-ada3870e5041.png)

I don't see how that would be physically accurate. No light hits the area conical area between the token and the light source: why should the token be able to see in this area? Of course, if something is between the observer and the light source, the observer would be able to tell that something is there by the silhouette, but wouldn't be able to see actually see it.

**Comment by ravingdragoon** [comment]
So here is a real life example of a similar light situation. The light source is directly behind the wall, but the light still provides dim lighting. The camera did make the cabinet a bit brighter than the view with my eye, but otherwise made the view a bit darker than what I could actually see..

![4C110BE2-5CCE-43DB-96F5-00B6D98A8D0F](https://user-images.githubusercontent.com/72875320/155885601-eb528b0f-8e56-4594-8d50-68c45322f77f.jpeg)

**Comment by ravingdragoon** [comment]
I guess I want that "see the silhouette" ability. My players frequently complain in dark areas that they should have been able to see something/someone's silhouette, if they weren't hiding, when it was between them and a light source. Maybe I should try a different way? Like with the token emitting dim light just in its space and a secondary image that is blurry or blacked out...

**Comment by dev7355608** [comment]
The simplest solution would be to ignore real light physics. There are those issues that I mentioned in my first post, another would be eye height and creature size: a larger creature would have a silhouette, but a swarm of rats wouldn't. I recommend to ping on the map if something larger is between the light source and the player, just like you would when something some noisy creature is in the darkness, which is a similarly difficult problem to automate.
