### ISSUE TITLE
PV drawing configuration blocking sight of overhead tiles

### ISSUE THREAD

**Issue by Razeick** [dev7355608/perfect-vision#219]
After following the example  from Drawing Example 1: Mixed Indoor/Outdoor Scene the edges of the drawing are blocking the Overhead tiles. Reddit link below best explains it however I have found the same issues with Better Roofs deactivated as well.

https://www.reddit.com/r/FoundryVTT/comments/sqxwc7/issue_with_perfect_vision_and_better_roofs_modules/

**Comment by dev7355608** [comment]
I made some changes to roof tiles in 3.7.0 that fix this (purely visual) issue.
