### ISSUE TITLE
Light bleed through revealed fog of war, showing background color where it should be monochrome.

### ISSUE THREAD

**Issue by intemptesta** [dev7355608/perfect-vision#22]
I experience this on two versions;
Foundry VTT 0.7.7
Perfect Vision 1.2.8
and
Foundry VTT 0.7.8
Perfect Vision 1.2.13

If a token is behind a wall they should see revealed FoG as monochrome, but lights will reveal the color of the background regardless of line-of-sight.
![image](https://user-images.githubusercontent.com/13413266/102441963-e72fcf00-4055-11eb-8804-23b6f49526c4.png)

**Comment by dev7355608** [comment]
Fixed in v1.2.15.
