### ISSUE TITLE
Perfect Vision causes canvas to crash for some users after trying to load specific scenes

### ISSUE THREAD

**Issue by Waltrobus** [dev7355608/perfect-vision#220]
The cause of this bug has been really hard for me to pinpoint, but I have two players whose whole canvas crashes after trying to load certain maps when Perfect Vision is enabled. I tried having all other modules disabled and this confirmed the bug being caused by PV. The crash prevents to users to see anything on their canvas (though they can find tokens etc in there by hovering their mouse over the tokens) and loading a different scene does not fix this. After trying to reload, they usually get an WebGL error popup from Foundry. It seemed at first like the known WebGL -problem with Intel HD drivers, but that does not seem to be the case (at least not definitely) with this bug.

Attached is my console log from a player whose canvas crashed starting from the loading of the scene that causes a crash. He uses a laptop and this bug seems to be tied somehow to those specific systems as the other player also is playing with Foundry on a laptop.

[PV_log.txt](https://github.com/dev7355608/perfect-vision/files/8128446/PV_log.txt)

**Comment by dev7355608** [comment]
The log indicates that there is a problem with some shader, but it's missing the actual error message of what's wrong. Click on *click to view full shader code* and make some screenshots.

**Comment by Waltrobus** [comment]
After trying to debug this with my player, I am not at all anymore sure this is actually a Perfect Vision related problem as I was unable to see the same results as earlier when disabling and enabling the module. Earlier I am quite sure there was direct mention of Perfect Vision in the error log, but of course there is no such mentions now. So this might be related to some other module all together, but none the less the bug persists when trying to load certain scenes with modules enabled.

If this is not related to Perfect Vision, I would appreciate some help though! Here is also the log with the actual shader error messages.
[PV_log2.txt](https://github.com/dev7355608/perfect-vision/files/8128661/PV_log2.txt)

**Comment by dev7355608** [comment]
Is there anything highlighted red in the shader error message? Right now it just looks like that any shader fails (even non-PV shaders) to compile for some reason. I suspect this has to be a driver bug. You mentioned the Intel HD bug, so I assume you already tried a bunch of things in this regard: testing the latest drivers as well as tried what is mentioned here?: https://discord.com/channels/170995199584108546/486930822465716249/876909288696725555

**Comment by dev7355608** [comment]
I assume this wasn't related to PV. I'm closing this, but let me know should I be wrong though.

**Comment by Waltrobus** [comment]
Hello! Yeah, I've tried making some tests, but it's quite hard as I am not able to reproduce the problem myself and need to test it with my players.

But it does seem that the actual problem is related to Foundry core (the Intel GPU problem, but not quite as it is reported so far) and PV just makes it a bit more enhanced. I'll let you know if I find more about this!
