### ISSUE TITLE
GM Vision doesn't add light after updating to Foundry `9.251`

### ISSUE THREAD

**Issue by kuroikyu** [dev7355608/perfect-vision#223]
## Context
Updated to Foundry VTT Version 9 `Build 9.251`. This is a test world where only the following modules are active. 
- Perfect Vision `3.7.1`
- libWrapper `1.12.4.0`

## Issue description
Hi, after the Foundry update it seems the GM Vision only removes the black & white filter but doesn't add any extra light to the scene, leaving it quite dark. I've tried scrolling on the tool icon as I remember that used to adjust the amount of light it added but to no avail.

I should mention I don't see any errors on the console.

## Images

<details><summary>No GM Vision, no token selected:</summary>

![image](https://user-images.githubusercontent.com/8393202/156342992-af334f21-c415-44fd-848d-afcfab61fc46.png)

</details>

<details><summary>GM Vision, no token selected:</summary>

![image](https://user-images.githubusercontent.com/8393202/156343019-cb154ff5-44c9-4062-9626-aecfc4e42b35.png)

</details>

<details><summary>No GM Vision, token with dim vision/sight 60:</summary>

![image](https://user-images.githubusercontent.com/8393202/156342916-62bda6b1-a827-47d5-8ed2-ef7235f03d03.png)

</details>

<details><summary>No GM Vision, token with bright vision/sight 60:</summary>

![image](https://user-images.githubusercontent.com/8393202/156342949-0dec968f-c3ea-4818-b472-1001a9362e56.png)

</details>

**Comment by dev7355608** [comment]
Thanks for the report! Fixed in 3.7.2.
