### ISSUE TITLE
Perfect Vision causes scenes to fail to load on FoundryVTT 9.254

### ISSUE THREAD

**Issue by Aeristoka** [dev7355608/perfect-vision#224]
![image](https://user-images.githubusercontent.com/7988297/156863719-b59c8d8d-4b99-422c-8222-21261c6b22e6.png)

Causes scene to not render at all.

Probably related to 1 or both of these 2:
https://gitlab.com/foundrynet/foundryvtt/-/issues/6795
https://gitlab.com/foundrynet/foundryvtt/-/issues/6797

From here:
https://foundryvtt.com/releases/9.254

**Comment by dev7355608** [comment]
Thanks for the report. Fixed.

**Comment by Aeristoka** [comment]
> Thanks for the report. Fixed.

Like a magical, fast wizard.

Thanks!
