### ISSUE TITLE
Overhead tile occlusion and other details do not work as expected

### ISSUE THREAD

**Issue by ianm32** [dev7355608/perfect-vision#229]
My use case for this is pretty niche, so I'm not sure if it's addressable without breaking something else.

When an overhead tile's Occlusion Mode is set to "None (always visible)," the tile still appears translucent to the GM unlike in Core functionality.

Furthermore, its opacity does not seem to be animatable by such modules as Sequencer.  I believe that before recently, this wasn't the case (though I will admit I am not certain of it).

I've attached some short video captures of attempting the same things with and without Perfect Vision enabled, as well as the macro script I'm using.

Active Modules in this Test Environment:
----------
libWrapper
Perfect Vision
Sequencer
socketlib
----------

Macro being used:
```
const target = canvas.foreground.get('LyiKGI0UBmI3svax')
target.document.update({ alpha: 0 })

new Sequence()
    .animation()
        .on(target)
        .fadeIn(1000, {ease: "easeOutCubic"})
    .play()
```

https://user-images.githubusercontent.com/27756065/157387140-e71e3ed1-5924-47e0-b625-84f57cfe2f3c.mp4

https://user-images.githubusercontent.com/27756065/157387145-30bbf067-1e28-4e2d-bdba-24a36cbf326f.mp4

**Comment by dev7355608** [comment]
Thanks for the report! Fixed in 3.7.7.
