### ISSUE TITLE
With global illumination off unlit areas are monochrome for DM

### ISSUE THREAD

**Issue by amcvfx** [dev7355608/perfect-vision#23]
Foundry 0.7.8
D&D 5th 1.2.0
Perfect Vision 1.2.13

I am finding that when Global Illumination is off, and no token is selected, unlit areas of the map are monochrome. This is with Improved DM vision on or off,

![image](https://user-images.githubusercontent.com/35099081/102468768-3ecc3b80-4052-11eb-8cab-5ef865a12c42.png)

When Global Illumination is turned on the map displays correctly

![image](https://user-images.githubusercontent.com/35099081/102468879-5efbfa80-4052-11eb-80ac-21ad81f95e88.png)

**Comment by dev7355608** [comment]
I still can't reproduce it. Are all other modules disabled? Errors in the console?

**Comment by amcvfx** [comment]
I found the culprit. It's MidiQOL for some reason. Not sure how that affects vision though?

**Comment by dev7355608** [comment]
I managed to reproduce it when I enabled Midi QOL's _Players control owned hidden tokens_. Do you have this option enabled?

**Comment by amcvfx** [comment]
Great that's it! Thanks for tracking that down

**Comment by dev7355608** [comment]
I now know what the problem is. I'm going to report it to the Midi QOL devs. This bug could break other modules as well.
