### ISSUE TITLE
New update black screen.

### ISSUE THREAD

**Issue by mark-drury** [dev7355608/perfect-vision#230]
Updated to 3.7.7 on foundry V9 build 255 and when the world loads in there is a black screen, the UI is still there but the map is black. Disabling PV fixes issue, reenabling causes same
![Screen Shot 2022-03-09 at 11 47 37 AM](https://user-images.githubusercontent.com/25595383/157510437-18eee8cf-4e80-4883-9574-d84cdde53741.png)
.

**Comment by dev7355608** [comment]
Please let me know whether there are any error messages in the console (F12 -> Console).

**Comment by mark-drury** [comment]
New to this console stuff, is this what you are looking for?

![Screen Shot 2022-03-09 at 12 03 06 PM](https://user-images.githubusercontent.com/25595383/157513099-59e3ab3c-17d0-4f7b-9d61-4916a32a7259.png)

**Comment by madcatprimary** [comment]
I'm seeing the same error since that last update.

**Comment by dev7355608** [comment]
This is probably a cache issue. This error shouldn't be possible with 3.7.7. Try CTRL+F5. If that doesn't work, uninstall and then reinstall PV.

**Comment by mark-drury** [comment]
Removing and reinstalling fixed the issue, thanks for the amazingly rapid service!!!!

**Comment by madcatprimary** [comment]
Also solved my problem. Thanks!
