### ISSUE TITLE
Foundry version 9, build 255 breaks with this mod enabled

### ISSUE THREAD

**Issue by DadCanDance** [dev7355608/perfect-vision#231]
After updating to the new stable build in the title, all maps are just a blank gray screen. Disabling this mod fixes the issue.

**Comment by dev7355608** [comment]
Make sure you update PV to the latest version (v3.7.7). This has been fixed already.

**Comment by DadCanDance** [comment]
Ah, didn't realize it was out of date. Many thanks!
