### ISSUE TITLE
Overhead tiles don't block weather effects

### ISSUE THREAD

**Issue by ianm32** [dev7355608/perfect-vision#233]
Per the title, overhead tiles no longer seem to block weather effects, specifically those provided by the FXMaster module.

**Comment by dev7355608** [comment]
That was an unfortunate bug in PV: it was never intended that FXMaster's weather layer is rendered below overhead tiles. Weather should be rendered above overhead tiles, both core and FXMaster weather. In what scenario do you prefer weather under overhead tiles? I assume for effects inside buildings?

**Comment by ianm32** [comment]
Ah, that's a pity.  I use them to build splash screens in my game, and it's useful for having backgrounds with weather effects, and foreground/"overhead" insert images that can appear above the weather effects.  My use case is admittedly a niche one.
