### ISSUE TITLE
Sight system worker & CSP?

### ISSUE THREAD

**Issue by sattvik** [dev7355608/perfect-vision#234]
Combing over some of my console logs I am noticing that I am seeing errors like:

> [Report Only] Refused to create a worker from 'https://<myhost>/modules/perfect-vision/scripts/core/sight-system-worker.js' because it violates the following Content Security Policy directive: "worker-src 'none'".

Here's the strange thing: I don't set a CSP on my server, so I don't know where that message came from.

This error occurs even if I do explicitly set `worker-src 'self'` on my proxy, so I have no idea where it's coming from or if it's breaking anything.

Grepping the network traffic from Foundry also doesn't show anywhere where that might be set.

**Comment by dev7355608** [comment]
A little bit of research leads me to believe that this could be caused by a browser plugin. Try it in private mode without browser plugins (and maybe in a different browser).

**Comment by sattvik** [comment]
I think you're right.  I did try in two different browsers originally, but they were both running a similar plug-in.  Disabling it made it go away.  I apologise for the trouble.  Thanks!
