### ISSUE TITLE
Issue with grey screen on Foundry V9 build 255, PV version 3.7.17

### ISSUE THREAD

**Issue by Medium-Kahuna** [dev7355608/perfect-vision#237]
Getting an issue where a map will initially load a small chunk, but moving off of that chunk slightly or scrolling out too much results in a grey screen. Uninstalling fixes the issue, and completely removing and reinstalling still has the issue occuring.

![error 1](https://user-images.githubusercontent.com/94126389/160211713-a2a2bf51-d5aa-4b2c-a1e4-9d4391c6aef6.jpg)
![Error 2](https://user-images.githubusercontent.com/94126389/160211715-f574a87b-5d3d-474f-bbe5-9efbc1d639ac.jpg)

These are the errors I'm getting.

**Comment by dev7355608** [comment]
It's a caching issue. Try CTRL+F5. If that doesn't do it, follow the guide below.

> **Caching Issues**
>
> There is a known issue for users updating from V8 to V9 related to caching which causes some errors, UI oddities, and trouble with canvas rendering which can be addressed quickly and immediately without support assistance. If a simple CTRL+F5 (CMD+SHIFT+F5 for Mac) does not resolve the issue:
>
> Steps to fix caching issues:
> 1. Open the DevTools using the F12 key (or cmd-shift-i for macOS)
> 2. Click the settings ⚙ icon
> 3. Below the heading 'network' check the checkbox for 'Disable Cache (when DevTools is open)
> 4. Leave the DevTools window open and refresh (f5) the Foundry VTT window
>
> *Note: Firefox users will see this checkbox under 'Advanced Settings' -> 'Disable HTTP Cache (when toolbox is open)'*
