### ISSUE TITLE
Potential conflict with Monk's Active Tile Triggers

### ISSUE THREAD

**Issue by rpganalyst** [dev7355608/perfect-vision#238]
Hello, after the recent new releases of P.V., when I access my game world, libwrapper send this warning (I took a screenshot in the console):
![image](https://user-images.githubusercontent.com/47994415/160250438-2ac02e68-e15f-432c-8455-60f3b388e946.png)
I don't know if the issue is on P.V.'s end or on the other module one.

Thank you.

**Comment by dev7355608** [comment]
This needs to be fixed on MATT's end. It likely works just fine even with the warning. Please report it on MATT's github.
