### ISSUE TITLE
Sight limit & Sequencer effects

### ISSUE THREAD

**Issue by DarKDinDoN** [dev7355608/perfect-vision#240]
Hello,

When the sight limit of token is reduced, he can still see Sequencer effets on the canvas outside his sight radius.

![image](https://user-images.githubusercontent.com/1687854/162337513-03d2c843-0e96-4220-89a7-4cb8e3e1fe8c.png)

**Comment by dev7355608** [comment]
Not a PV bug. The visibility binding in Sequencer is flawed. I submitted a PR to fix this.
