### ISSUE TITLE
[Feature Request] Blur the map already released from the fog of war, which is not in the field of view

### ISSUE THREAD

**Issue by GabrielOsvair** [dev7355608/perfect-vision#241]
Blur the map already released from the fog of war, which is not in line of sight. I've seen this feature on Fantasy Grounds and it's pretty interesting! Since a person wouldn't remember the map with all the details.

**Comment by dev7355608** [comment]
I'm not going to add this to PV. But V10 makes this easier to implement and it could be its own little module.
