### ISSUE TITLE
Pathfinder 1e and magical darkness

### ISSUE THREAD

**Issue by dmrickey** [dev7355608/perfect-vision#242]
Is there a way to configure a token with darkvision to see through an area of magical darkness?

I've got a light set up like so
> Create a light source and open the configuration and go to the Advanced Options tab. Set Luminosity to value below zero to create a dark light source. Then check the Enable box next to Sight Limit and set Sight Limit to 0. Now tokens won't be able to see though or inside the area of this light source.

I've got brightvision set to 60 per this chart

![image](https://user-images.githubusercontent.com/3664822/164072932-2445ad42-b1ef-4d5a-be84-6d50bf9c12f7.png)

The magical darkness blocks sight for tokens that have brightvision configured.

![image](https://user-images.githubusercontent.com/3664822/164073329-923c0ebe-fc03-4e34-988a-acaf9be57ba1.png)

Perfect Vision: 3.7.33
PF1: 0.80.15
Foundry: 9.268

**Comment by dev7355608** [comment]
Not yet. See #197.

**Comment by dmrickey** [comment]
Gotcha, I'd seen that one previously but I didn't realize it was related at all. I assumed that the request was more of a "Devil's Sight should see through magical darkness like darkvision does" and assumed it was a shortcoming with pf1.

**Comment by dev7355608** [comment]
The V10 release of PV is going to feature *Vision Limitation*. It the replacement for *Sight Limit*, and it is going to allow you to define different limits for vision and each Detection Mode. If your system implements magical darkvision, you'll be able to make exceptions for it.

![image](https://user-images.githubusercontent.com/31905376/187105119-b668017d-d559-4bbe-a7e7-33b740036c73.png)
