### ISSUE TITLE
[Feature Request] Token tone in monochrome vision

### ISSUE THREAD

**Issue by jello195** [dev7355608/perfect-vision#245]
Would it be possible to have a feature that allows certain tokens to have a different tone in monochrome vision? For instance this:
![perfect-vision-A](https://user-images.githubusercontent.com/83799020/164337678-3a4249f6-1bb9-4666-b205-d1f4627fc5bc.jpg)
could be turned to this
![perfect-vision-B](https://user-images.githubusercontent.com/83799020/164337722-004c3a9c-4594-46cc-9db7-c5e1adaa7379.jpg)

**Comment by dev7355608** [comment]
V10 adds basic support for this kind of thing. But PV is not going to mess with that. Implementing vision modes will be the system's responsibility most likely.
