### ISSUE TITLE
wfrp4e: Night vision can't be implemented.

### ISSUE THREAD

**Issue by kamypus** [dev7355608/perfect-vision#246]
I noticed that there is no good way to reproduce night vision in wfrp4e.

Rule: Each time you get night vision, the distance the light reaches appears to increase by 20yd.

Torchlight: 20yd bright light
Normal vision: 20yd bright vision (by torchlight)
Night vision 1: 20yd bright vision + 20yd bright vision
Night vision 2: 20yd bright vision + 40yd bright vision

I think I can achieve this if I can control normal vision with custom settings.

　　　　　　　Bright light / dim light / darkness
Normal vision : bright vision / darkness / darkness
Night vision 1 : bright vision / bright or dim vision(20yd) / darkness
Night vision 2 : bright vision / bright or dim vision(40yd) / darkness

Torch setting : 20yd bright light / lots of dim light

If you limit the light with sightlimit, you will not be able to see distant light sources.

**Comment by dev7355608** [comment]
This may be supported by Vision Modes in the future, but it didn't make in the initial V10 stable release unfortunately (it may or may not be implemented in later V10 release). PV is not going to implemented system-specific vision modes though. It should be the system's job to do so.
