### ISSUE TITLE
Drawngs don't respect elevation

### ISSUE THREAD

**Issue by Orionox** [dev7355608/perfect-vision#249]
If I put a drawing below something and set it to being dark it darkens everything above it instead of only making the area inside the specific height range dark. using this with levels.

**Comment by dev7355608** [comment]
There's just one lighting layer, which is 2D. A lighting drawing is only rendered if the current token is in the elevation range of the controlled token. Any token that would be outside of the elevation range of the drawings is affect by the same lighting like everything else on the canvas. A light source with elevation range also illuminates token outside of the light's elevation range for the same reason. Foundry is only build for 2D, and Levels can only do so much to make it as 3D as possible.
