### ISSUE TITLE
Older hardware sees a black screen for a scene if I am using Perfect Vision

### ISSUE THREAD

**Issue by zabu61** [dev7355608/perfect-vision#250]

**Comment by dev7355608** [comment]
Check the console for error messages (F12 / cmd+option+I -> Console tab). And if you see yellow warning messages with the word WEBGL in it, let me see those as well.

**Comment by dev7355608** [comment]
And Perfect Vision requires WebGL 2. Is there an error notification on the screen that mentions this?

**Comment by zabu61** [comment]
There certainly is an error for WebGL 2.  I believe the hardware is unable to support it.

**Comment by dev7355608** [comment]
It is required. Foundry itself does technically require webgl 2 as well (lights are not rendered entirely correctly with webgl 1). What hardware do you have? In case it's an iPad or iPhone:

> **Does Foundry Work on the iPad or iPhone?**
>
> Foundry does not explicitly support Safari on the iPad or iPhone but if your OS is on 14.5 or later you may be able to access Foundry after enabling an experimental Safari feature. Navigate to `Settings > Safari > Advanced > Experimental Features` and enable the `WebGL 2.0` setting. Modules such as Touch VTT and Mobile Improvements can make interacting with Foundry via touch much smoother.

**Comment by zabu61** [comment]
> Check the console for error messages (F12 / cmd+option+I -> Console tab). And if you see yellow warning messages with the word WEBGL in it, let me see those as well.

Presuming that's on the players pc with the older hardware, let me coordinate that and find out.

**Comment by zabu61** [comment]
Here we go - I also have error messages on the vtt screen itself as well as F12 console output:

![image](https://user-images.githubusercontent.com/30198757/167054197-10fbcb04-2c31-4e0b-ab0e-f9d84f60a109.png)

**Comment by zabu61** [comment]
![image](https://user-images.githubusercontent.com/30198757/167054275-9662482a-b29d-4840-944b-e2ccb0fd655e.png)
