### ISSUE TITLE
Feature Request: ability for lights to selectively upgrade light level

### ISSUE THREAD

**Issue by LebombJames** [dev7355608/perfect-vision#251]
In Starfinder, the [Portable Light Item](https://www.aonsrd.com/TechItems.aspx?ItemName=Flashlight&Family=Portable%20Light) increases the light level by one step (Dark -> dim. Dim -> Bright). There's no way to do this in core or PV, but I think it'd be a good fit for PV's more advanced lighting features.

**Comment by dev7355608** [comment]
The lighting levels changes by v10 vision modes is going to affect all light sources in the scene regardless of the vision range. So implementing this item would require some big changes to the vision modes system, which I'm not going to make.
