### ISSUE TITLE
Drawing Light Settings work not bugfree with Levels

### ISSUE THREAD

**Issue by R0TEAM** [dev7355608/perfect-vision#253]
Have an House with 3 Levels ->
ground
1st Level
Roof
Have on ground and 1st Level drawings with different light settings ...
It works "in" the level - but i can see the darker aera on the Roof ....
And after one of the last updates, walls dont block light from light sources to the drawing aera anymore ...
(have 2 doors that have a small light in front of it, to simulate, if the door is opened, a little light is going in the dark aera ..
have worked - now it is always bright)

**Comment by dev7355608** [comment]
Make sure that your roof tile's *Occlusion Mode* set to *Roof*. If that doesn't do it, I need to see screenshots of your tile / drawing configuration to figure out what's wrong.

**Comment by R0TEAM** [comment]
Thanks - musst have changed this unintentionally .. now the problem with the Roof is gone ;)
for the other i have make an screen shot ...
https://drive.google.com/file/d/1954-GQkkWDKR7QiWBbHaY2mG-3DMZTxZ/view?usp=sharing
you see on the right the light settings from the drawing
on the left the settings for the lights
the lights are near the doors - but its dont matter if the door open or closed .. or even if i move the lights to an wand .. its not blocking the brighten of the dark aera ....

**Comment by dev7355608** [comment]
I suspect the problem is the top/bottom range of your walls or the top/bottom range of your lights. The wall top/bottom range has to completely contain the top/bottom range of the light in order for the wall to block the light. (There was a change in Wall Height recently that changed the wall-light interaction.)

**Comment by R0TEAM** [comment]
nope - just checked .. walls are all (on the ground level) on 0-9 - doors 0-9 ... lights 0-9 .... all the same ...

**Comment by dev7355608** [comment]
Do the doors and windows block the lights if you disable Perfect Vision?

Also make sure Levels/Wall Height/Better Roofs/Perfect Vision are all up to date.

If you want to, you can export the scene and share it with me. Then I can take a closer look.

**Comment by R0TEAM** [comment]
Ha - found the problem ....
relax - not your mod make problems ...
it is the "Light/Sound Mask" mod .... have an issue entry over this already ...
Thanks for your Help ;)
(have disabled PerfectVision .. same problem ... mhh ... have drawing new light ... works perfect .. confused ... have open light settings ... change one zhing ... click light update ... bang ... walls now dont block this light anymore ... after testing i found it is even if you dont change any light settings .... only open it and click "update" the walls become "non functional" for this light ..)

**Comment by dev7355608** [comment]
I had a quick look at Light Mask and found the source of the problem. I left a comment on this issue. So hopefully it's fixed soon.
