### ISSUE TITLE
Switching to cached scene failes (remains black screen)

### ISSUE THREAD

**Issue by Fallayn** [dev7355608/perfect-vision#254]
Since a few weeks ago, I have the annoying issue that when Foundry has been running for some time, switching back to a previously loaded scene fails: the scene texture isn't loaded and remains black, and this failure also seems to irritate Foundry enough that mostly nothing else works, so a reload is required at this point.

The error in the console is
```
Uncaught (in promise) TypeError: Cannot read properties of null (reading 'source')
[Detected 1 package: perfect-vision]
    at TextureLoader.expireCache (foundry.js:23283:46)
    at TextureLoader.load (foundry.js:23071:29)
    at Function.loadSceneTextures (foundry.js:23034:24)
    at Canvas.draw (foundry.js:20107:27)
    at async Canvas.🎁Canvas.prototype.draw#perfect-vision (canvas.js:415:9)
    at async Scene.view (foundry.js:17859:7)
```

I can confirm disabling Perfect Vision seems to solve this, as the issue no longer seems to happen then.
It started happening a few weeks ago, somewhere around version 3.9.0 (or shortly before/after).
I can confirm this issue still happens with the most recent release 3.9.6.
This is on Foundry v9 Build 269 with DND 5E.

I've been using Perfect Vision for a long time, this only started happening recently. Thanks for the awesome module! :)

**Comment by dev7355608** [comment]
PV is only mentioned in the error because it overrides Canvas#draw, but that shouldn't cause this error. It looks like a false-positive.

Can you reliable reproduce this in every scene?

Are there more error messages in the console? Or warnings (yellow) that mention WebGL?

I discovered a huge memory leak in Foundry when I investigating this issue today related to scene switching. But this error seems to be something else.

**Comment by Fallayn** [comment]
> PV is only mentioned in the error because it overrides Canvas#draw, but that shouldn't cause this error. It looks like a false-positive.
> 
> Can you reliable reproduce this in every scene?
> 
> Are there more error messages in the console? Or warnings (yellow) that mention WebGL?
> 
> I discovered a huge memory leak in Foundry when I investigating this issue today related to scene switching. But this error seems to be something else.

Sorry, this seems to be indeed something else, it just happened without Perfect Vision enabled (no error message in console this time though). Sigh. Sorry for the false report :)

**Comment by dev7355608** [comment]
I recommend to use the module *Find the Culprit* to figure out quickly which module is causing this.
