### ISSUE TITLE
Perfect Vision is making the background image always visible, even when tokens do not have LoS

### ISSUE THREAD

**Issue by jmosq** [dev7355608/perfect-vision#255]
![PV_On](https://user-images.githubusercontent.com/29285713/169591859-bb9ccad5-8f9e-40ff-989a-45fed56dba18.jpg)
![PV_Off](https://user-images.githubusercontent.com/29285713/169591867-80c3ec6e-7970-4671-a17e-653f09af6b15.jpg)

The screenshots are from the GM's POV.

When PV is on, walls are not blocking LoS and so the Token can see areas of the background image they should not. Light grey in GM view.

When PV is off, the walls block LoS and the Token cannot see areas of the background image as normal. Dark grey in GM view.

**Comment by dev7355608** [comment]
Did you enable *Reveal Fog* in the scene settings?

**Comment by jmosq** [comment]
Thank you. It's been a few months since I last walled a map, and maybe missed when that setting when in. Thanks for the quick reply. Cheers!
