### ISSUE TITLE
Vision Rendering errors on drawn light maps

### ISSUE THREAD

**Issue by R0TEAM** [dev7355608/perfect-vision#256]
Have found another problem ....
I use levels (but this is imho no problem here) and the option to set with an drawing the light levels/behavor in an building.
Have in the floor windows, on this place i have not draw the shadow map - so it looks it come light from the windows in the building.
This works nice ...
Have creatures with nightvision ... here i have set the chrome color to an red tone ...
all is working nice .. except the range calculation IF(this is now speculation) an different light level is set with the drawing in the LOS of the creature AND another Token is in this LOS present.
To better visual clarify this - i have 2 pictures ....
Have after the screenshot drawn additional help lines here ...
Blue the place of the non shadow area of the light map direct on the window ...
Red the expected end of view range of the Token - but it is larger
https://drive.google.com/file/d/1kYRW31XVhOckItUADMmCXWjYati4LJ8o/view?usp=sharing
https://drive.google.com/file/d/1N597I2cGXzNrDo4Crf5xtuQRZJT7UGO0/view?usp=sharing

Regards

**Comment by dev7355608** [comment]
Could you export the scene and share it with me (I don't need the assets)? It's hard to tell what the problem is by looking at the screenshots.

**Comment by R0TEAM** [comment]
have send you an eMail ;)

**Comment by dev7355608** [comment]
![image](https://user-images.githubusercontent.com/31905376/169656184-8e5e2246-73eb-4f19-94a3-9cf205a1e3e7.png)

Sight rays lose energy while traveling through sight limited areas. So the rays do not lose energy while traveling through the indentation you created (because outside there's not limit set). In other words: the sight rays travel exactly a distance of 20 feet inside the drawing, but exit and re-enter at the indentation.

**Comment by R0TEAM** [comment]
mhh - this is for "me" (as i do proffesional raytracing) understandable .... but should not work like this in an setting where you define the range by an "natural sight range" ... as this have only the range in question ... not the "energy of an photon" ....

**Comment by dev7355608** [comment]
I'm not sure what you're suggestion. Without casting rays token standing outside of sight limited areas could see inside the area completely unrestricted. I think the concept of energy makes sense: like in real life fog absorb energy of a photon for each unit of distance it travels, until barley any energy is left.

The sight limit isn't darkvision range. Sight Limit limits the line-of-sight polygon, which is infinite normally. Your tokens have still 60 feet darkvision, but the line-of-sight range is reduced by the sight limits.

**Comment by R0TEAM** [comment]
ahh - o.k. - sorry - i try to better explain....
mhh ..... 
In my scene - the sight of this room is limited by an fog .... the fog is in the bright parts on the windows too ... so "in real", the bright part would not extend any range, you only need not darkvision to see here ... as the sight limiting fog is in the whole area ... it is only it have dark aeras and bright aeras - but the fog dont change at all ... why should the range change ?

**Comment by dev7355608** [comment]
You could place another drawing without indentations under the drawing and set the Sight Limit of it to 20 feet as well. This should to it.

![image](https://user-images.githubusercontent.com/31905376/169672748-65c3ecec-9149-4433-a043-c1d25f05a653.png)

**Comment by R0TEAM** [comment]
ahhh - i see .. my fault .. in the "bright" aearas - it is no sight limit, as it cancels the whole drawing out (and so the fog is canceled out here too..) ..... thanks ;)

**Comment by R0TEAM** [comment]
o.k. - after testing - dont work .... only from the upper drawing the settings are used ....

**Comment by dev7355608** [comment]
Make sure the Z-Index of your original drawing is higher than the Z-Index of the other drawing below it: 
![image](https://user-images.githubusercontent.com/31905376/169673220-f84f7eb6-b07c-4b08-8d2b-21c6850978c5.png)

It does work: 
![image](https://user-images.githubusercontent.com/31905376/169673225-5ef7e1bf-1ae4-4cb6-ae90-3897ca61d534.png)

**Comment by R0TEAM** [comment]
o.k. - it works - THANKS
(but the handling of the different drawings on the same location is a PITA .... ;) =

Regards

**Comment by dev7355608** [comment]
There's no way of knowing that you want the indentation to be handled differently without placing another drawing. That said, the problem here is that I need to come up with a technique that handles the doors and windows automatically to simulate light leaking in out or out without placing light sources. I ready thought about it a lot, but it's a very difficult problem to solve (and it needs to intuitive to the user).
