### ISSUE TITLE
Perfect vision has some compatibility problems with Automated Animations/Sequencer.

### ISSUE THREAD

**Issue by Zealouzy** [dev7355608/perfect-vision#260]
When PV is enabled alongside these modules, the animations disappear whenever a token is selected. Specifically persistent animations.

I've attached images to show what happens when PV is enabled in conjunction, and when it is not.
![EX1](https://user-images.githubusercontent.com/108196102/175788317-48c43d16-9088-4dd2-8652-a23d0e083350.PNG)
![EX2](https://user-images.githubusercontent.com/108196102/175788319-441fc585-9198-4860-a14a-a13b7256de65.PNG)

**Comment by dev7355608** [comment]
Thanks for the report! Fixed in 3.9.12.
