### ISSUE TITLE
Token Bright Vision Radius

### ISSUE THREAD

**Issue by V4leR05** [dev7355608/perfect-vision#262]
Hi, I have an issue with perfect vision in my pathfinder1e world. With the module active I can't modify Token Bright Vision Radius (which is costantly reset to 0, see picture below), Fun fact, it actually allows to modify the value directly from the actor prototype token but every you drag the actor in the scene the bug happens and resets the value to 0. 

Any fix? 

I have Foundry V9 build 269, pathfinder system v.0.81.0 and Perfect Vision v. 3.9.12.

https://gyazo.com/e6c05f4b6d965b8c5f69c899d871ca2f

**Comment by dev7355608** [comment]
I think the system itself is doing that. PF1e automatically fills the dim/bright vision radius fields in the token config according to the vision entries in the token's actor sheet. This automation has been added 1-2 months ago if I recall correctly. I think there's a way to opt-out of this automation if you don't like it. Ask in the pf1e discord channel for help. I'll close this issue, but should it be a PV problem after all, feel free to reopen this issue.
