### ISSUE TITLE
Canvas drawing failed for the Sightlayer

### ISSUE THREAD

**Issue by AetherianRPG** [dev7355608/perfect-vision#263]
Just made a new world. There is only Perfect Vision and lib-wrapper enabled and I'm getting this error:

![PV1](https://user-images.githubusercontent.com/68928934/177925988-15f93f24-b056-4764-ab3c-4ff8003d1e81.PNG)

![PV2](https://user-images.githubusercontent.com/68928934/177926019-c156056e-8b62-440c-8a6a-e823e02f7a51.PNG)

**Comment by dev7355608** [comment]
This is looks like a cache issue. Follow the following instructions (CTRL+F5 should to the trick). Let me know if that fixes it.

> **Caching Issues**
>
> There is a known issue for users updating from V8 to V9 related to caching which causes some errors, UI oddities, and trouble with canvas rendering which can be addressed quickly and immediately without support assistance. If a simple CTRL+F5 (CMD+SHIFT+F5 for Mac) does not resolve the issue:
>
> Steps to fix caching issues:
> 1. Open the DevTools using the F12 key (or cmd-shift-i for macOS)
> 2. Click the settings ⚙ icon
> 3. Below the heading 'network' check the checkbox for 'Disable Cache (when DevTools is open)
> 4. Leave the DevTools window open and refresh (f5) the Foundry VTT window
>
> *Note: Firefox users will see this checkbox under 'Advanced Settings' -> 'Disable HTTP Cache (when toolbox is open)'*

**Comment by AetherianRPG** [comment]
Yes, it does fixes it. Thank you!
