### ISSUE TITLE
Error Rendering PF2e game

### ISSUE THREAD

**Issue by moxperidot** [dev7355608/perfect-vision#265]
I've had to disable PerfectVision in my pathfinder game as I get rendering errors; screenshot of the console attached.
![console](https://user-images.githubusercontent.com/110789727/183311250-bfd0b312-c329-4317-bd3b-c4b6a870f0fd.png)

**Comment by dev7355608** [comment]
This is a cache issue. CTRL+F5 should fix it. If not, follow these instructions:

> **Caching Issues**
>
> There is a known issue for users updating from V8 to V9 related to caching which causes some errors, UI oddities, and trouble with canvas rendering which can be addressed quickly and immediately without support assistance. If a simple CTRL+F5 (CMD+SHIFT+F5 for Mac) does not resolve the issue:
>
> Steps to fix caching issues:
> 1. Open the DevTools using the F12 key (or cmd-shift-i for macOS)
> 2. Click the settings ⚙ icon
> 3. Below the heading 'network' check the checkbox for 'Disable Cache (when DevTools is open)
> 4. Leave the DevTools window open and refresh (f5) the Foundry VTT window
>
> *Note: Firefox users will see this checkbox under 'Advanced Settings' -> 'Disable HTTP Cache (when toolbox is open)'*
