### ISSUE TITLE
Grey screen in Pathfinder 1 scene

### ISSUE THREAD

**Issue by linkmaster2207** [dev7355608/perfect-vision#266]
Im not sure what happened but since updating Foundry, I haven't been able to get Perfect Vision to work. Whenever I enter the game, everything functions normally but when a scene loads I am unable to see or interact with it. Instead its this neutral void.
![image](https://user-images.githubusercontent.com/53383862/184796289-65170d06-73f3-4013-a0f1-5d6ad3daa9a3.png)
Its really hard to scan the console for errors, but it only happens when I activate Perfect Vision. Is this a problem others have had and if so how did you fix it?

**Comment by dev7355608** [comment]
Updated to which Foundry version? If you updated from v8 to v9, try CTRL+F5 or instructions below if that shouldn't work. There's no PV version available for v10 yet.

> **Caching Issues**
>
> There is a known issue for users updating from V8 to V9 related to caching which causes some errors, UI oddities, and trouble with canvas rendering which can be addressed quickly and immediately without support assistance. If a simple CTRL+F5 (CMD+SHIFT+F5 for Mac) does not resolve the issue:
>
> Steps to fix caching issues:
> 1. Open the DevTools using the F12 key (or cmd-shift-i for macOS)
> 2. Click the settings ⚙ icon
> 3. Below the heading 'network' check the checkbox for 'Disable Cache (when DevTools is open)
> 4. Leave the DevTools window open and refresh (f5) the Foundry VTT window
>
> *Note: Firefox users will see this checkbox under 'Advanced Settings' -> 'Disable HTTP Cache (when toolbox is open)'*

**Comment by linkmaster2207** [comment]
> Updated to which Foundry version? If you updated from v8 to v9, try CTRL+F5 or instructions below if that shouldn't work. There's no PV version available for v10 yet.
> 
> > **Caching Issues**
> > There is a known issue for users updating from V8 to V9 related to caching which causes some errors, UI oddities, and trouble with canvas rendering which can be addressed quickly and immediately without support assistance. If a simple CTRL+F5 (CMD+SHIFT+F5 for Mac) does not resolve the issue:
> > Steps to fix caching issues:
> > 
> > 1. Open the DevTools using the F12 key (or cmd-shift-i for macOS)
> > 2. Click the settings ⚙ icon
> > 3. Below the heading 'network' check the checkbox for 'Disable Cache (when DevTools is open)
> > 4. Leave the DevTools window open and refresh (f5) the Foundry VTT window
> > 
> > _Note: Firefox users will see this checkbox under 'Advanced Settings' -> 'Disable HTTP Cache (when toolbox is open)'_

It doesn't appear to have solved the issue. My Foundry version is still V9 
![image](https://user-images.githubusercontent.com/53383862/184939570-645794e9-3c20-4f00-9ad7-bd79b6ec8228.png)

I also tried the Cache thing and it didn't make a difference. I did find the error message in console though! Not sure how much it helps.
![image](https://user-images.githubusercontent.com/53383862/184939516-15256e03-af71-42fd-8686-660af93c4599.png)

**Comment by dev7355608** [comment]
Make sure PV is actually up to date. Maybe updating locked or stuck somehow. Uninstalling and then reinstalling PV gives you the latest version.

**Comment by linkmaster2207** [comment]
> Make sure PV is actually up to date. Maybe updating locked or stuck somehow. Uninstalling and then reinstalling PV gives you the latest version.

Hey, Thank you! Reinstalling actually fixed it! It's nice to return to Perfect vision after Months with this problem!
