### ISSUE TITLE
Forge: "Canvas drawing layer failed for LightingLayer"

### ISSUE THREAD

**Issue by KailynNeko** [dev7355608/perfect-vision#268]
Don't know why but every time I update this module on The Forge I keep getting the "Canvas drawing failed for the LightingLayer" error even after uninstalling and reinstalling it. It took days for the last update to not show it and I was hoping I could get some help since this keeps happening and I really like using this mod.

![Perfect Vision Error](https://user-images.githubusercontent.com/111794530/186003362-dc54e573-8f92-40ee-a978-7a29c3b7793c.png)
.

**Comment by dev7355608** [comment]
The Edge browser has feature called *Enhanced security mode* (https://support.microsoft.com/en-us/microsoft-edge/enhance-your-security-on-the-web-with-microsoft-edge-b8199f13-b21b-4a08-a806-daed31a1929d), which disables JIT compilation and WebAssembly (Wasm). You either need to disable this mode entirely in the settings, add an exception for the Forge and any other sites you use Foundry on, or use a different browser.

**Comment by dev7355608** [comment]
I added a more informative error notification including the Edge specific instructions on how to fix it to the v10 version of Perfect Vision.

**Comment by KailynNeko** [comment]
Yep, that fixed it. Thank you so much!
