### ISSUE TITLE
Monochromaticity turned off when Global Illumination is enabled but set to None

### ISSUE THREAD

**Issue by rsimoes** [dev7355608/perfect-vision#27]
Maybe this is as intended, but I would have expected the behavior to be the same as were Global Illumination disabled. If it is intended, could the documentation be updated to further explain what the None setting entails?

**Comment by dev7355608** [comment]
It's intended. It's indirectly documented in the description of _"Monochrome Vision Color"_ but frequently missed. Maybe I'll add _"None (monochrome)"_ as an option if this is requested.

**Comment by rsimoes** [comment]
What might a Perfect Vision use case be for having Global Illumination enabled but set to None?

**Comment by dev7355608** [comment]
With _None_ the scene is not filled with dim/bright light. In default Foundry with Global Illumination everything is fill with dim light (technically every token gets infinite dim vision) which makes dim light sources basically invisible. With _None_ everything is illuminated according to the Darkness Level only. No extra light is added. This way you have three instead of just two brightness levels, and the visuals of light sources say unaffected.

**Comment by rsimoes** [comment]
I get that's what "None" does by itself, but I'm wondering if there'd be any feature loss if Perfect Vision exhibited a consistent behavior regardless of light origin, be it an actual light source placed in the world or light coming from Global Illumination. At a high level it's all light or a lack thereof. Global Illumination set to None and no light source objects illuminating an area is functionally the same as Global Illumination disabled and no light source objects illuminating an area.

**Comment by dev7355608** [comment]
I had _None_ originally as _Scene Light_. Not sure if that is better. Global Illumination means everything in line-of-sight is visible, and PV's setting Global Illumination _Light_ determines what, or if, light fills the scene. But I chose to have it all in color always, reason being, if everything is visible, there must be some light, so it can't be monochrome.

**Comment by rsimoes** [comment]
I see now that Global Illumination still reveals everything even when it's set to None (an annoying undocumented side effect). I'm not sure what the solution is given that.
