### ISSUE TITLE
[FEATURE REQUEST] OSE SRD Compatibility

### ISSUE THREAD

**Issue by justinthejaguar** [dev7355608/perfect-vision#270]
I was wondering if there was a way to make it so that players using OSE Infravision could have the vision deactivated if they are in eyeshot of a light source?

![image](https://user-images.githubusercontent.com/38022481/187095892-901775b4-3d0e-42df-952d-53affa923683.png)
https://oldschoolessentials.necroticgnome.com/srd/index.php/Hazards_and_Challenges#Infravision

So, in this instance, the dwarf should not be able to see the red areas because the area they are in is lit. 
![image](https://user-images.githubusercontent.com/38022481/187095936-40416b29-aca7-49b7-90db-5b692a7cf0ba.png)

**Comment by dev7355608** [comment]
This kind of thing may be possible with V10's Vision Modes. But PV is not going to implement system-specific vision modes. It should be the system's job to do so.
