### ISSUE TITLE
Error in Foundry v10

### ISSUE THREAD

**Issue by Kharmans** [dev7355608/perfect-vision#271]
When used the module in Foundry v10, the maps don't load. The error bellow appears when you have the module active and try to load a map.

![image](https://user-images.githubusercontent.com/112586547/187784651-f8084337-e68c-4ada-8f21-8d33f8479ec8.png)

**Comment by dev7355608** [comment]
I haven't released the update for V10 yet. I'll release it in a couple of hours if nothing goes wrong.

**Comment by TheMathKing** [comment]
Will V10 render this module obsolete since it includes features very similar?

**Comment by l-pogson** [comment]
I thought this would be a module I would drop with V10, but unless there is a workaround in core, this is needed to have the whole scene lit, with a section (defined by a drawing) having different lighting conditions.

**Comment by dev7355608** [comment]
PV no longer needs to handle greyscale vision etc; that is all core now with the new Vision Modes. But PV still offers the Lighting Drawings and Vision Limitation features, which have been improved massively for V10.

I need some more time to make the PV V10 release as bug free as possible. I'll let you know when I release it, which should be in the next 24 hours.

**Comment by bearsy1** [comment]
I agree! PV is still necessary (at least for my _vision_ of the kinds of games I want to run) as it adds key features that won't be covered by v10 as far as I have read/know. Also, it's great to hear that you're already on top things. Looking forward to using this module in v10!

**Comment by Eagle0600** [comment]
I utterly love PV's lighting drawing feature, I can't imagine why something similar isn't the default. Having a map with combined indoor and outdoor areas is almost required for things like exploring a courtyard with several buildings in it, and that is very difficult to do without this feature. I thank you for all your hard work @dev7355608.

**Comment by dev7355608** [comment]
Perfect Vision 4.0.0 has been released! Enjoy!
