### ISSUE TITLE
In D&D 5e mode, don't totally hide invisibile tokens

### ISSUE THREAD

**Issue by benbarbour** [dev7355608/perfect-vision#272]
Not sure if this is something you want to handle if core doesn't, but take a look at: https://github.com/foundryvtt/dnd5e/issues/1647

**Comment by dev7355608** [comment]
PV won't add/modify system-specific vision modes/detection modes or likely any modes for that matter. (If I were to implement vision modes/detection modes, I'd submit them to the system or ship them in a separate module.)

A solution to this issue could be a module that allows the GM to target tokens for the player. I'm not sure if such a module exists already. The advantage is that it wouldn't (I think) require modifying Foundry's/D&D5e's vision modes/detection modes.

**Comment by dev7355608** [comment]
I created a module that allows the GM to target for their players.  When the player needs to target an invisible token for the automation workflow to succeed, the GM can step in and target the token. https://github.com/dev7355608/manage-player-targets
