### ISSUE TITLE
Canvas breaks when enabling a lighting drawing (Pathfinder 1)

### ISSUE THREAD

**Issue by jacobgrey** [dev7355608/perfect-vision#274]
# Issue Description
Enabling lighting override on a shape (e.g. rectangle) causing the canvas to stop updating. Tokens, shapes, and other objects can still be clicked on or moused over, and double clicking will open the appropriate dialogues, but the objects cannot moved and the canvas never updates visually (to show selection, or to reflect changes made to settings). Disabling lighting on the offending shape and reloading the scene results in normal operation. _(i.e. either by reloading application or simply switching to another scene and back)_

Scenes without a lighting-enabled shape can be switched to and used normally. Switching back to the scene with a lighting-enabled shape results in an empty gray scene (no canvas render). 

## Versions in use
- Using Foundry v10.284
- Using Pathfinder 1 (0.82.1)
- Using Perfect Vision 4.0

## Other Notes
- No other modules active (except libwrapper dependency)
- No actual lighting overrides enabled, just the top "enable" checkbox on the lighting tab for the shape
- Enabling lighting using the quick button (top left when right-clicking on shape) shows same behavior, i.e. scene render freezes when clicked
- Module remains awesome anyway, nice work!

**Comment by dev7355608** [comment]
Thanks for the report. It's an issue with the PF1e system. I filed a bug report here:
[foundryvtt_pathfinder1e/foundryvtt-pathfinder1#1652](https://gitlab.com/foundryvtt_pathfinder1e/foundryvtt-pathfinder1/-/issues/1652)

**Comment by Eagle0600** [comment]
The linked issue has been closed by commit, but not yet released. I can confirm that the commited change fixes the issue (players will need to reload, clearing cache with ctrl-F5).

**Comment by dev7355608** [comment]
PF1e 0.82.2 was released, which fixes this issue.
