### ISSUE TITLE
Compatibility Issue with Levels & Wall Heights

### ISSUE THREAD

**Issue by wickermoon** [dev7355608/perfect-vision#275]
### Expected Behavior

I click a character and everything works fine.

### Current Behavior

I click a character and get the following error
![image](https://user-images.githubusercontent.com/15907070/188191316-25d9fe9e-7acf-4621-ad48-3014d3bafa20.png)

Then the canvas freezes and I have to switch scenes in order to work with the canvas again

### Steps to Reproduce

1. install and activate perfect vision, levels, and wall-height modules
2. go to any scene, click on any actor
3. error in console

### Version

v4.0.1

### Foundry VTT Version

v10.284

### Operating System

Windows 10

### Browser / App

Native App (Electron)

### Game System

dnd5e (2.0.2)

### Relevant Modules

levels(3.0.9.5) wall-height(4.7.1)

**Comment by dev7355608** [comment]
Thanks for the report! Fixed in 4.0.2.
