### ISSUE TITLE
Error when opening Configure Vision Limitation on ambient light source

### ISSUE THREAD

**Issue by wickermoon** [dev7355608/perfect-vision#276]
### Expected Behavior

No error

### Current Behavior

An error:
![image](https://user-images.githubusercontent.com/15907070/188193352-f74f8ba4-323c-4fe3-b4b5-900a6a898647.png)

### Steps to Reproduce

1. create a light source
2. open configuration, open Configure Vision Limitation
3. Error in Console
4. Try to close Configure Vision Limitation dialog via xClose
5. 
![image](https://user-images.githubusercontent.com/15907070/188193578-dc93ccac-87fa-4789-b1a3-b82512a754b8.png)

### Version

v4.0.1

### Foundry VTT Version

v10.284

### Operating System

Windows 10

### Browser / App

Native App (Electron), Chrome

### Game System

dnd5e (2.0.2)

**Comment by wickermoon** [comment]
just for completion's sake: Closing the dialogs via "Update Vision Limitation" works without error.

**Comment by dev7355608** [comment]
Thanks for the report! Fixed in 4.0.2.
