### ISSUE TITLE
Everything is black on Foundry V9 with DND5e

### ISSUE THREAD

**Issue by JuIez** [dev7355608/perfect-vision#279]
### Expected Behavior

Well, normaly you would have vision as DM and can change stuff on the toolbar
![image](https://user-images.githubusercontent.com/44580956/188285380-301e39fb-bb60-4bce-8b4f-bb9c0a8ed469.png)

### Current Behavior

You can't select anything on the toolbar and the Map ist just black
![image](https://user-images.githubusercontent.com/44580956/188285403-b333b795-acbd-4fb0-a819-e621d4a638bb.png)

### Steps to Reproduce

1. Create a new World
2. Add any Map
3. Add Module Perfect Vision
4. The Map is black and you can't change anything on the toolbar

### Version

v3.9.12

### Foundry VTT Version

v9.280

### Operating System

Linux

### Browser / App

Chrome, Other

### Game System

dnd5e (1.6.3)

### Relevant Modules

No other moduls expect libWrapper (1.12.7.0)

**Comment by dev7355608** [comment]
The latest and final v9 PV version is 3.9.15. The final v9 update caused PV to break unfortunately. If you update PV, this should be resolved. Let me know. Shouldn't to update automatically for some reason, uninstall and reinstall PV.

**Comment by JuIez** [comment]
Yeah, this solved the problem. I thought I couldn't updated it since I only got the error with "You need version V10 for the next update" message. 
Thanks a lot :)
