### ISSUE TITLE
In 0.7.9 with Midi-QoL enabled monochrome filter is applied even within light sources

### ISSUE THREAD

**Issue by Zamrod** [dev7355608/perfect-vision#28]
The monochrome filter stays on even in light sources while running Foundry 0.7.9, Midi-QOL 0.3.39 and Perfect Vision 1.2.16

**Comment by dev7355608** [comment]
It's a Midi QOL bug. Disable _Players control owned hidden tokens_ for now.

**Comment by NorthernPlague** [comment]
Ah thank you - I had to search through Closed issues to find this. May consider putting section for _Conflicts_ in the README.
