### ISSUE TITLE
Vision Rules

### ISSUE THREAD

**Issue by AetherianRPG** [dev7355608/perfect-vision#283]
### Description

This is not a request. It is a question to resolve a doubt.

Will Perfect Vision for Foundry v10 keep any of the Vision Rules options? I play pathfinder 2e and was wondering if its vision rules will remain as part of the Perfect Vision module.

**Comment by dev7355608** [comment]
The PF2e system is going to implement the PF2e's vision rules with V10's Vision/Detection Modes. PV is not going to implement these for any system in V10, because the system can and should do it or possibly a separate module.
