### ISSUE TITLE
Not being able to see outside where unrestricted vision should be present

### ISSUE THREAD

**Issue by Cempres** [dev7355608/perfect-vision#288]
### Expected Behavior

Not sure if I'm able to describe the issue I'm having with words, so I'll try my best to explain it with added screenshots.

I'm not able to have the token to see outside of the drawing with unrestricted vision range. The token has 5 ft of vision inside of the drawing, and unless his vision circle colides with the door, he cannot see outside.

What I'm trying to accomplish:
![image](https://user-images.githubusercontent.com/90740197/189543652-c23b7dfa-0120-4658-a0ad-258afbb14e37.png)

What's happening to me:
![unknown](https://user-images.githubusercontent.com/90740197/189543758-cf8266cb-1959-4e52-a880-0dfc6d683c45.png)
![unknown](https://user-images.githubusercontent.com/90740197/189543771-ba1b5dca-3529-4a7c-8ab0-1c15dc4f428a.png)

I apologize in advance if this isn't a bug and my stupidity, but I've tried my best to figure it out!

### Current Behavior

Above

### Steps to Reproduce

1.Configure global illumination to be enabled, works outside of the drawing
2.Limit the drawing and override the features so there's only 5 ft of vision (as the house is unlit)

### Version

v4.0.12

### Foundry VTT Version

v10.284

### Operating System

Windows

### Browser / App

Native App (Electron)

### Game System

dnd5e (2.0.2)

### Relevant Modules

-

**Comment by dev7355608** [comment]
Vision Limitation is used for fog or magical darkness, for example: something that blocks or stops vision (or detection modes beyond a certain range. Ordinary darkness (the absence of light) lets light pass through unrestricted of course. Do you want to reduce/limit the effective of just darkvision? If so, you should leave everything at Infinity, but set Basic Sight (which is Darkvision) to 5 feet for example. The token might see more of the map (but not tokens) than it should in this configuration. I'll have to look into that.

**Comment by Cempres** [comment]
No dark vision involved. I just dont want him to see in the house well, but if the door is open to be able to see outside. Is it possible? It's the thing shown in this video at around 3:26 https://youtu.be/Ce2KeS4ww9o?t=206 if that helps show what I mean :)

**Comment by dev7355608** [comment]
The token in the video has 5 feet darkvision; no vision limitation used. That's what you have to do if you want a token to see in darkness at least 5 feet. PV doesn't have an option for "at least X feet darkvision inside this area".

**Comment by Cempres** [comment]
yeah, i misunderstood what darkvision is, but the token still can't see outside if he's not touching the "outside" with his vision range

**Comment by Cempres** [comment]
As of v10 and the new layout, I'm not sure which settings have to be turned on/off

**Comment by dev7355608** [comment]
You want to set Sight Limit to Infinity or better turn off Vision Limitation entirely. You just have ordinary darkness: nothing that reduces the tokens range of the token's ability to see light at any distance.

Vision Limitation defines the maximum range of vision/detection. So a Sight Limit of 5 feet could be very thick fog for example; so unless you are within 5 feet of the border of the fog, you won't be able to see out of it. Other use cases for Vision Limitation are
blizzards, sand storms, thick undergrowth, and magical darkness. Or you might want to use it to simply restrict all vision/ detection to a maximum of X feet in a scene for the simple reason that perception wouldn't be precise at all beyond a certain distance.

I admit the Vision Limitation config can look very complicated, but it needs it that way in order to allow to model all kinds of nonmagical or magical vision obstructions. I plan to add presets in the future, that should shed some light on how to use it and simplify/speed up the configuration.

**Comment by Cempres** [comment]
I understand that part, in v9, if we "had unrestricted vision range" on for the scene, and then we override it for the drawing and turn it off, and give the token 5 ft of darkvision, the token is going to have 5ft of dark vision within the drawing, but no matter how far he is from the edge of the drawing, the token was still able to have unrestricted vision range applied, and I can't get that to work anymore.

**Comment by Cempres** [comment]
This is what I just can't accomplish any more in v10
v9 example:
![v9 example](https://user-images.githubusercontent.com/90740197/189638688-b75240f5-c4dc-420d-ac75-de547d2f8cfe.png)

**Comment by dev7355608** [comment]
You're looking for Global Illumination. Unrestricted Vision Range was renamed to Global Illumination in v10. Enable Global Illumination outside and disable it inside.

**Comment by Cempres** [comment]
I have, but it's not working..
![image](https://user-images.githubusercontent.com/90740197/189654754-2433cf93-1334-4dd7-a79a-e564d79daccd.png)
![image](https://user-images.githubusercontent.com/90740197/189654849-c3e33d55-da90-44e2-b9d3-67d53de92290.png)
![image](https://user-images.githubusercontent.com/90740197/189654910-0d1d0d60-410c-4cb3-a326-16630c0dd50e.png)

**Comment by dev7355608** [comment]
Have you disabled Vision Limitation? Show me that configuration as well please.

**Comment by Cempres** [comment]
Same effect:
![image](https://user-images.githubusercontent.com/90740197/189661526-120b32a5-2bde-433b-8bd5-959ece7025ab.png)

**Comment by dev7355608** [comment]
What's the Vision Limitation configuration of the drawing?

**Comment by Cempres** [comment]
only the sight limit of 5ft
![image](https://user-images.githubusercontent.com/90740197/189683270-9073d7a7-835e-483d-a0d4-07a0cd08b86c.png)

**Comment by dev7355608** [comment]
You need to remove the Sight Limit / disable Vision Limitation / uncheck the Override boxes. Right now, sight (line of sight) is restricted to 5 feet like a very dense fog would the token can barely see through. In v9 a Sight Limit of 5 feet would have had the same effect as it does in v10 now. You need to give the token a 5 feet vision range, if you want the token to be able to see that much in darkness.

**Comment by Cempres** [comment]
Ah beautiful! Thank you so much, it worked! So sorry to waste your time on this!

Thanks for all the help, and keep up the great work with the module, it's a life changer!
