### ISSUE TITLE
When I make changes to the light, I can't see this light anymore when I'm GM (V10)

### ISSUE THREAD

**Issue by medeiros961030** [dev7355608/perfect-vision#289]
### Expected Behavior

When I make any change to a source of Light, whether it's changing the color, intensity, making that light a torch, or anything else, it stops illuminating for me, as if it had gone out. For the Player, it remains normal

![image](https://user-images.githubusercontent.com/112792783/189817271-ba4aaef8-aabd-4d91-8c38-a804acea2f1f.png)
Correct GM vision (light without alteration any parametes

![image](https://user-images.githubusercontent.com/112792783/189817312-e83a6ae4-c9b2-495c-b73e-76e2e1e07bd5.png)
Correct Player vision (light without alteration any parametes)

### Current Behavior

![image](https://user-images.githubusercontent.com/112792783/189817446-66c81612-70cf-402a-8ce6-1525d5117b19.png)
When I make any parameter change of the light (as an example making it a rainbow) in my GM view the light seems to go out

![image](https://user-images.githubusercontent.com/112792783/189817669-d1576b11-c51d-408f-a78c-9ad5498fa041.png)
in player view, the effect works normally

### Steps to Reproduce

n/a

### Context

n/a

### Version

v4.0.13

### Foundry VTT Version

v10 last version Builld 285

### Operating System

windows 10

### Browser / App

Chrome

### Game System

Pf2e 4.0.3

### Relevant Modules

Happen if only perfect vision On

**Comment by dev7355608** [comment]
Please check the console for error messages after the light goes out: F12 (or Option+Command+I on Mac) -> Console tab.

> Happen if only perfect vision On

Does it happen if Perfect Vision is the only active module? If not, use the Find The Culprit module to figure the conflicting module.

**Comment by medeiros961030** [comment]
After hours of testing the modules, it turns out that the problem occurs when 2 modules are active:
Perfect Vision and Levels

The levels module has 2 dependencies (wall height and lib wrapper) but when I disable the levels module and leave only the dependencies active along with perfect vision, this error does not occur, that is: the error is between the levels module and the perfect vision

the strange thing is that there is no error in the log

**Comment by dev7355608** [comment]
It should be fixed now (4.0.14). Make sure you also update Levels.

Thanks for the report!

**Comment by medeiros961030** [comment]
I just did an update, and the problem remains.

**Comment by dev7355608** [comment]
I fixed a similar issue (only in scenes without background image). But the actual source of this issue is Wall Height. PV just makes it more obvious. I'll make sure Wall Height gets fixed.

**Comment by dev7355608** [comment]
Fixed in Levels 3.1.4 / Wall Height 4.7.5.

**Comment by medeiros961030** [comment]
Thank you!! Now is fixed,
