### ISSUE TITLE
"Improved GM Vision" not rendering light correctly

### ISSUE THREAD

**Issue by DuskyVoltage** [dev7355608/perfect-vision#29]
I'm having an issue with Improved GM vision not correctly rendering lit-up areas and treating everything with the same improved visibility. All tested with only Perfect Vision active:

Scene normally, Darkness set to 0: https://i.imgur.com/7lpLUu5.png

Darkness set to 1, Improved GM Vision unchecked: https://i.imgur.com/O0ap0uK.png
Token's vision: https://i.imgur.com/YAlIkxA.png

Darkness set to 1, Improved GM Vision checked: https://i.imgur.com/5KjrHfz.png

I made a mockup in GIMP in how this kind of scene used to look to me: https://i.imgur.com/E2LYbRy.png

**Comment by dev7355608** [comment]
Thanks! Fixed it in v1.2.17.
