### ISSUE TITLE
Running a reset fow and close doors macro freezes the scene

### ISSUE THREAD

**Issue by Cempres** [dev7355608/perfect-vision#291]
### Expected Behavior

Trying to run the following macro ends in freezing the whole scene until reload.
Macro:
const updates = canvas.walls.doors.filter(i => i.data.ds < 2).map(i => ({_id: i.id, ds: 0}));
await canvas.scene.updateEmbeddedDocuments('Wall', updates);

canvas.fog.reset()

works without issues when turning off the module.

### Current Behavior

Screenshot of the error:
![image](https://user-images.githubusercontent.com/90740197/191592964-bd103440-5ec9-4a19-a979-a6f25ecadf47.png)

### Steps to Reproduce

1.Run the macro while moving a token
2. f12 will shrink the screen and the scene will be completely unsusable

### Version

v4.0.17

### Foundry VTT Version

v10.286

### Operating System

Windows

### Browser / App

Native App (Electron)

### Game System

dnd5e (2.0.2)

**Comment by dev7355608** [comment]
Thanks for the report! Fixed in 4.0.18.

**Comment by Cempres** [comment]
Hey, there seems to be a different issue now, as the fow doesn't reset somehow
![image](https://user-images.githubusercontent.com/90740197/192650688-398159e5-85c3-4488-8187-f349ea7ac09c.png)
