### ISSUE TITLE
Values are lost when saving Ambient Light Vision Limitation

### ISSUE THREAD

**Issue by strongpauly** [dev7355608/perfect-vision#294]
### Expected Behavior

Values should be kept when saving Vision Limitation from the Ambient Light dialog

### Current Behavior

Looks like the values are saved if the  Configure Vision Limitation dialog is closed and reopened whilst the Ambient Light dialog is open, but if the Ambient Light dialog is closed and reopened the values are lost.

### Steps to Reproduce

1. Create a new light
2. Open the configuration dialog and open the Configure Vision Limitation dialog from the Advanced Options tab
3. Click the Enable checkbox (and fill out other values too)
4. Click Save Changes
5. Click Update Light Source
6. Reopen the two dialogs

### Version

v4.0.26

### Foundry VTT Version

v10.287

### Operating System

Mac

### Browser / App

Native App (Electron), Chrome

### Game System

dnd5e (2.0.3)

### Relevant Modules

Disabled all modules except PV and libWrapper

**Comment by dev7355608** [comment]
Thanks for the report! Fixed in 4.0.27.

**Comment by strongpauly** [comment]
Thanks for the quick fix.  Can confirm this now works in the latest version
