### ISSUE TITLE
Automatic grayscaling not working anymore for low light settings

### ISSUE THREAD

**Issue by gsterling** [dev7355608/perfect-vision#296]
### Expected Behavior

When I first used Perfect Vision in FoundryVTT v9 everything with low light was grayish the darker it was. And complete black and white when you couldn't see something. It was a really nice effect and helped determine where it's really dark and where it only looked dark because of the map.

### Current Behavior

Low light looks like the core foundry light.

### Steps to Reproduce

1. Install Perfect Vision
2. Create a map with a medium to high darkness level
4. Create a light source
5. Place a token
6. Use it to walk around
7. See it's not grayish in dark areas

### Version

v4.0.28

### Foundry VTT Version

v10.288

### Operating System

Linux

### Browser / App

Chrome, Firefox, Other

### Game System

Splittermond 0.9.6

**Comment by dev7355608** [comment]
In V10 Perfect Vision isn't responsible for vision rules / how vision looks / grayscale / etc anymore. That's all core now and might be a bit different based on the system if it changes the default behavior. Experiment with Vision Modes and the Advanced Vision Options; either Darkvision or Basic Vision with Saturation set to -1 is probably want you want. By default the saturation is not gradually linked to the Darkness Level of the scene though (that can't be changed in with the UI; requires the system or a module to change that behavior).
