### ISSUE TITLE
Canvas drawing failed for the BackgroundLayer, see the console for more details.

### ISSUE THREAD

**Issue by NorthernPlague** [dev7355608/perfect-vision#30]
I don't see any erroneous behavior but get this error on first load of a scene:

![image](https://user-images.githubusercontent.com/76060635/102822024-30f61d80-43a6-11eb-8623-657e9122d0ab.png)

![image](https://user-images.githubusercontent.com/76060635/102822046-39e6ef00-43a6-11eb-9671-e7083b47ada6.png)

Points to:
PerfectVision._updateMonoFilter();

**Comment by dev7355608** [comment]
Thanks! Fixed in v1.2.18.
