### ISSUE TITLE
Custom Vision Rules Checkbox Cleared On Token Configuration Close

### ISSUE THREAD

**Issue by Tarbarian** [dev7355608/perfect-vision#301]
### Expected Behavior

When closing a token's configuration without updating (pressing the `X Close` button) the token settings should not be changed.

### Current Behavior

When closing a token's configuration without updating (pressing the `X Close` button) the Custom Vision Rules gets "unchecked", but only for the current user. That is to say that the system acts as if that box was not checked for that client, but on a refresh the box returns to being checked until the configuration is closed again without updating. Reopening the configuration and pressing the `Update Token` button without rechecking the box makes the unchecking "permanent."

### Steps to Reproduce

1. Create a token with "Custom Vision Rules" checked.
2. Open token configuration and close it without updating.

### Version

4.0.32

### Foundry VTT Version

v10.288

### Operating System

Windows

### Browser / App

Native App (Electron), Chrome

### Game System

pf1e 0.82.2

**Comment by dev7355608** [comment]
I'm able to reproduce this without any modules enabled: Custom Vision Rules is not reset back to the original state if the config is closed without saving. It's a pf1e system bug.

**Comment by Tarbarian** [comment]
I am unable to reproduce the issue without modules. Gifs for proof.
![Recording 2022-10-22 at 12 14 36](https://user-images.githubusercontent.com/76751079/197353578-bdd49b53-e838-42dc-a0ee-91a2041628fe.gif)
![Recording 2022-10-22 at 12 20 41](https://user-images.githubusercontent.com/76751079/197354038-e721a3a5-479c-4793-b28b-c29abb03241a.gif)

*Had to butcher the second gif to get it under 10MB*

**Comment by dev7355608** [comment]
The bug I discovered (no modules):

1. Open Token config.
2. Toggle Custom Vision Rules.
3. Close Token config (not Update Token).
4. Reopen Token config.

Result: Custom Vision Rules isn't reset to the state it was when the Token config was opened; it's still in preview state.

I assume this system bug just takes another form if PV is enabled, but the underlying source of the problem is in the system.

**Comment by Tarbarian** [comment]
Ah, yeah, that is indeed a core bug and I could see how that would take a new form under PV. I'll bring this to the PF1e devs. Thanks!
