### ISSUE TITLE
Vision limitation more limited then it should be

### ISSUE THREAD

**Issue by Iankid** [dev7355608/perfect-vision#302]
### Expected Behavior

Tokens that's are 2x2 or larger should still be visible on their edge spaces. Basic foundry detects by center point of token, but Levels module has the option to detect corners, which fixes this. This setting should still be in effect in lights with vision limitations.

### Current Behavior

Currently, if a large or larger token is within a light source with vision limitations of up to 7 (further for tokens diagonal), they are not visible to other tokens until they are on top of them.

### Steps to Reproduce

Create 2 tokens in a light source with vision limitation (limit of 5 in this test), One token 2x2 or larger, the other 1x1.

### Context

![vis](https://user-images.githubusercontent.com/60759323/198854039-05d251a9-1f1a-4c6c-ab99-6a8c253654ff.png)

### Version

v4.0.33

### Foundry VTT Version

v10.288

### Operating System

Windows

### Browser / App

Native App (Electron)

### Game System

SF (v0.20.3)

### Relevant Modules

Levels (v3.4)

**Comment by dev7355608** [comment]
Latest Levels/Perfect Vision should have finally resolved this issue.

Thanks for the report!
