### ISSUE TITLE
Fog Exploration tied to Scene Darkness color

### ISSUE THREAD

**Issue by OpticalShadows** [dev7355608/perfect-vision#303]
### Expected Behavior

Fog exploration color to only be tied in to the fog exploration color setting, not multiplied by the scene darkness setting. 

### Current Behavior

Fog exploration color is multiplied by the scene darkness color, making it impossible to use with a scene darkness color of black. 

### Steps to Reproduce

1. Leave all settings at default except scene darkness color change to #000000
2. Fog Exploration shows as black so it is not usable.

### Context

**Normal behavior:**
![image](https://user-images.githubusercontent.com/8631043/199821081-e4679622-76c7-4e8e-a2aa-9c99bbfabec1.png)

**Scene darkness at black:**
![image](https://user-images.githubusercontent.com/8631043/199821182-7b081842-560e-4db5-82c3-8bd3f5221c0d.png)

**Reason for running with scene darkness at black:**
Horror themed game where lighting is important and scene darkness at black gives a much more appealing visual gradient (especially with light attenuation maxed). Ideally would have a smooth gradient to whatever color is selected by the fog exploration setting. 

### Version

v4.0.34

### Foundry VTT Version

v10.288

### Operating System

Windows

### Browser / App

Chrome

### Game System

dnd55e

### Relevant Modules

none

**Comment by dev7355608** [comment]
Don't set the Darkness Color to black: the color is multiplied on top of everything, making everything black. The multiplicative behavior is core and not PV; the interaction with the explored fog as well. PV just exposes the darkness and daylight colors in the scene settings.

I should add a warning or disallow dark colors. Choose a gray instead, for example `#303030`. Let me know if that solves this problem for you.

**Comment by dev7355608** [comment]
I added a warning in 4.0.55 that is displayed if the Daylight/Darkness Color is `#000000`.
