### ISSUE TITLE
Bug with Better Roofs/Levels

### ISSUE THREAD

**Issue by ducky00** [dev7355608/perfect-vision#304]
### Expected Behavior

When you place a tile "inside" levels you're supposed to see it and walk below it with no problems like this:
![image](https://user-images.githubusercontent.com/80284558/200135919-905e5a4c-95b6-4397-82c0-15fa962883ac.png)

### Current Behavior

Currently I can't see the tile when its set up is to be "inside" levels
![image](https://user-images.githubusercontent.com/80284558/200135836-648049a0-3d83-43f8-9744-8ce5390a24fe.png)

### Steps to Reproduce

1. Have a scene created with at least two levels
2. Place a tile "inside" one of those levels
3. Select a token nearby and see how the tile is just flat black image

### Version

v4.0.37

### Foundry VTT Version

v10.286

### Operating System

Windows 10

### Browser / App

Native App (Electron)

### Game System

dnd5e 2.0.3

### Relevant Modules

Levels (3.5) - Better Roofs 1.7.6

**Comment by dev7355608** [comment]
Update to Levels 3.5.1. Make sure that *Is a Roof?* is unchecked and check *Allow Sight* (Animation tab).

I assume you don't need those arches to block sight. Let me know if that works for you.

**Comment by ducky00** [comment]
Updating to Levels 3.5.1 solved it, many thanks
