### ISSUE TITLE
Levels and Occlusion Mode: Vision

### ISSUE THREAD

**Issue by crcoughenour** [dev7355608/perfect-vision#305]
### Expected Behavior

I expect, with Levels and Perfect Vision enabled and two tiles placed down, one of which is a roof, for a token's vision to look something like this when Occlusion Mode is Vision and Occlusion Alpha is 0 (Screenshot taken with Perfect Vision disabled):
![Screenshot 2022-11-06 223502](https://user-images.githubusercontent.com/37161761/200224756-acbe8bd8-f10e-4f68-9d91-bbe731863906.png)

### Current Behavior

Instead, upon enabling Perfect Vision it looks like:
![Screenshot 2022-11-06 223345](https://user-images.githubusercontent.com/37161761/200224826-1febdfdb-c1c9-4bcc-9e16-928a172e76a3.png)

### Steps to Reproduce

1. Install Levels and Perfect Vision.
2. Create a Level.
3. Place a tile on the level.
4. Place a roof on the level.
5. Change the roof's Occlusion Mode to Vision.
6. Set the Occlusion Alpha to 0.
7. Use a token with vision to observe.

### Version

v4.0.39

### Foundry VTT Version

v10.288

### Operating System

Windows

### Browser / App

Native App (Electron)

### Game System

dnd5e (2.0.3)

### Relevant Modules

levels (3.5.2)

**Comment by dev7355608** [comment]
It's a core bug that's causing this issue. But I shipped a fix for in PV 4.0.40.

Thanks for the report!
