### ISSUE TITLE
Occlusion Mode: Vision - Recalculation Issue and Infinite Height Issue

### ISSUE THREAD

**Issue by crcoughenour** [dev7355608/perfect-vision#306]
### Expected Behavior

Vision should recalculate as a token moves around when looking at a roof with Occlusion Mode: Vision.

A roof should be visible despite the walls below it.
Edit:  This functionality is provided by Better Roofs

### Current Behavior

Roof occluded area does not recalculate upon moving (moved three squares to the left):
![image](https://user-images.githubusercontent.com/37161761/200691927-91954133-523f-49c4-97f4-a127123bdbc2.png)

### Steps to Reproduce

1. Levels + Perfect Vision
2. Create a level
3. Add a tile with levels
4. Add a roof with levels
5. Set roof to Occlusion Mode: Vision
6. Add some walls to block vision
7. View as a token and move around

### Version

v4.0.43

### Foundry VTT Version

v10.288

### Operating System

Windows

### Browser / App

Native App (Electron)

### Game System

dnd5e (2.0.3)

### Relevant Modules

levels (3.5.2)

**Comment by dev7355608** [comment]
Fixed roof occlusion not recalculating properly.

> A roof should be visible despite the walls below it.

Is there a difference compared to core in this regard? In the depicted scenario the behavior is the same for me when I disable PV, but I might have misunderstood that the issue is.

**Comment by crcoughenour** [comment]
So sorry that was me forgetting to turn Better Roofs back on.  Only the recalculation part of the bug report seems valid.
