### ISSUE TITLE
Light Source interface freezes when adding light animation effect

### ISSUE THREAD

**Issue by darthlunga** [dev7355608/perfect-vision#307]
### Expected Behavior

Add a light source, hit save and light source is added.

### Current Behavior

I can add a light source but once I go into the settings to adjust it and hit save the interface menu freezes, will not allow any changes to me saved and won't let me proceed. The rest of foundry is not frozen, just the light interface. 

### Steps to Reproduce

1. Click Lighting Controls from left menu
2. Drag Light source onto scene
3. Click light source to enter light configuration menu
4. Click save (you can make changes as well, but it freezes even if you just open the menu and save)

### Context

![Screenshot 2022-11-11 165703](https://user-images.githubusercontent.com/87379787/201442144-6cb1fd09-e948-4d09-8170-ef599051cf7a.png)
![Screenshot 2022-11-11 165730](https://user-images.githubusercontent.com/87379787/201442147-a4c3db8c-bf19-428c-ada2-752b97e78b7c.png)
![Screenshot 2022-11-11 165744](https://user-images.githubusercontent.com/87379787/201442149-0e7f3470-f052-4ff6-9aee-03def7608d96.png)

### Version

4.0.48

### Foundry VTT Version

v10 Patch 5 (Build 288)

### Operating System

Windows 11

### Browser / App

Chrome

### Game System

DnD5E

**Comment by dev7355608** [comment]
Thanks for the report! Fixed in 4.0.49.
