### ISSUE TITLE
Migration Process Won't Complete

### ISSUE THREAD

**Issue by jburrows127** [dev7355608/perfect-vision#309]
### Expected Behavior

I would expect that after migrating to version 10 of Foundry and running with Perfect Vision (PV) that the migration process that is initiated by PV wouldn't fail and log me out of the server.

### Current Behavior

After I upgraded to version 10 of Foundry and the latest version of Perfect Vision (PV) (4.0.49) I keep running into problems with the PV migration. It keeps failing with a "websocket.js:143 WebSocket connection to 'wss://<redacted>/socket.io/?session=<redacted session 1>=4&transport=websocket' failed: WebSocket is closed before the connection is established." error message and boots me out of the server. When I log back on the migration process begins again only to encounter the same problem.

### Steps to Reproduce

1. Update to foundry version 10 (any version)
2. Update PV
3. Logon to server
4. Click on migration button

### Context

"websocket.js:143 WebSocket connection to 'wss://<redacted>/socket.io/?session=<redacted session 1>=4&transport=websocket' failed: WebSocket is closed before the connection is established."

### Version

4.0.19

### Foundry VTT Version

v10.290

### Operating System

Raspbian GNU/Linux 10 (buster)

### Browser / App

Chrome

### Game System

dnd5e 2.0.3

**Comment by jburrows127** [comment]
Not sure if this is relevant but here is my module list:

Active Modules:
----------
About Time v;
Active-Auras v;
Active Token Effects v;
Advanced Macros v;
All Goblins Have Names v;
Always HP v;
Ambient Doors v;
Ammo Tracker v;
Arbron’s Improved HP Bar v;
Automatic Journal Icon Numbers v;
Backgroundless Pins v;
Compendium Folders v;
Crash's Automatic Blind Rolls (5e) v;
DFreds Convenient Effects v;
DFreds Droppables v;
DFreds Pocket Change v;
Dice Tray v;
Disable Mouse Wheel Control for Sliders v;
Drag Ruler v;
Dynamic Active Effects SRD v;
Dynamic effects using Active Effects v;
Easy Target v;
Encounter Statistics v;
Enhanced Terrain Layer v;
Follow Me! v;
Force Client Settings v;
Forien's Quest Log v;
Foundry Community Macros v;
Foundry Community Tables v;
FXMaster v;
GM Notes v;
Group Initiative v;
Health Estimate v;
Initiative Quick Change v;
Item Piles v;
Less Fog v;
lib - Color Settings v;
libWrapper v.0;
Maestro v;
Midi QOL v;
Monk's Active Tile Triggers v;
Monk's Little Details v;
Monk's TokenBar v;
Monk's Wall Enhancement v;
Party Overview v;
PopOut! v;
Quick Encounters v;
Quick Insert - Search Widget v;
✋ Raise My Hand v;
Shared Data v;
Simple Calendar v;
Smart Target v;
socketlib v;
Terrain Ruler v;
Tidy5e Sheet v;
Tidy UI - Game Settings v;
Times Up v;
Token Action HUD v;
Token Animation Tools v;
Token Auras v;
Token HUD Wildcard v;
Token Magic FX v;
Token Mold v;
User Latency v;
Weather Control v;

**Comment by maxphoenix01** [comment]
I'm facing the same issue as well.

**Comment by dev7355608** [comment]
@maxphoenix01 Does it also disconnect you once you click *Migrate Compendium Packs* but not before? Is your Foundry version 10.290 too?

How many (how big) compendium packs do you have in your world?

**Comment by dev7355608** [comment]
Please try 4.0.50 and let me know whether it fixes the problem.

**Comment by maxphoenix01** [comment]
The issue persists, unfortunately. The update didn't seem to change anything.

> Please try 4.0.50 and let me know whether it fixes the problem.

**Comment by dev7355608** [comment]
@maxphoenix01 Could you share the complete console log with me?

Also: could you execute this without PV enabled. Paste it in the console and enter. It loads all world compendium packs. I want to make sure loading the packs isn't the issue. Let me know whether that triggers web socket disconnect.
```js
for (const pack of game.packs) {
    if (pack.metadata.packageType !== "world") continue;
    console.log(`Loading ${pack.collection}...`);
    await pack.getDocuments();
    console.log(`Loaded ${pack.collection}!`);
}
```

**Comment by jburrows127** [comment]
> ```js
> for (const pack of game.packs) {
>     if (pack.metadata.packageType !== "world") continue;
>     console.log(`Loading ${pack.collection}...`);
>     await pack.getDocuments();
>     console.log(`Loaded ${pack.collection}!`);
> }
> ```

I ran this command without PV enabled, and I saw the same exact error where I get disconnected from the server.

In regards to the compendiums, I'm not sure how to quantify this, but I do have some pretty large packs. In particular, I have a large (~10,000) monsters in various packs.

**Comment by dev7355608** [comment]
@jburrows127 That leaves me wondering how the system's (dnd5e) migration even succeeded, which would have loaded the packs too. You didn't have problems with the system migration, correct?

**Comment by dev7355608** [comment]
So it turns out that dnd5e doesn't actually migrate world compendium packs at the moment because of a bug. I'm not quite sure what happens once that is fixed, but I assume either both dnd5e and PV successfully migrate or dnd5e's pack migration will trigger a disconnect too.

**Comment by dev7355608** [comment]
> > ```js
> > for (const pack of game.packs) {
> >     if (pack.metadata.packageType !== "world") continue;
> >     console.log(`Loading ${pack.collection}...`);
> >     await pack.getDocuments();
> >     console.log(`Loaded ${pack.collection}!`);
> > }
> > ```
> 
> I ran this command without PV enabled, and I saw the same exact error where I get disconnected from the server.
> 
> In regards to the compendiums, I'm not sure how to quantify this, but I do have some pretty large packs. In particular, I have ~10,000 monsters in various packs.

@jburrows127 Did you try this with all modules disabled?

**Comment by dev7355608** [comment]
If you haven't tried to run PV's migration with all other modules disabled, do that first. Let me know whether that succeeds.

If the migration failed with other modules disabled: You may manually run the dnd5e world compendium pack migration. **_Please make a backup before doing this!_** It should be safe; that's what the system would to at least if it wasn't for this bug. **But please make a backup just in case.**
```js
for (const pack of game.packs) {
    if (pack.metadata.packageType !== "world") continue;
    await game.dnd5e.migrations.migrateCompendium(pack);
}
```
Run this with _all_ modules disabled. If you try this, let me know whether it succeeds. If it doesn't, it confirms that this isn't a PV specific problem. Assuming it isn't limited to PV it would preferable to address this problem before dnd5e 2.1.0, which will run this migration and would therefore prevent you from updating to 2.1.0. If it succeeded, try to run PV's migration again and let me know the results.

**Comment by jburrows127** [comment]
Thanks for the recommendation on this. I did try originally to do the migration with all other modules disabled, and it still didn't work. However, it's no longer an issue because I ended up refactoring some of my compendiums so they are smaller, which resolved the problem.

**Comment by dev7355608** [comment]
Glad you have solved it. I tried to reproduce it by generating gigantic compendium packs. It took forever but I was unable to crash it. I tested it only locally though. I suspect a server with more limited resources and limited bandwidth might refuse/fail to process such a huge request.

**Comment by dev7355608** [comment]
dnd5e 2.1.0 was released, which fixed the broken compendium migration of the system. So, if PV's migration broke things for you, @maxphoenix01, it might break on the system level now. So make sure to _**backup your data**_ before you update the system in case it doesn't work (you should always backup before a system update anyway). This allows you do roll back and reduce the compendium size as @jburrows127 did.
