### ISSUE TITLE
[Request] Text Labels for Lighting Prototype

### ISSUE THREAD

**Issue by LonePaladin** [dev7355608/perfect-vision#310]
### Description

In a prior version of this module (or an older one that PV was based on), you could create a shape, give it a text label, then assign lighting conditions. On creation of subsequent shapes, the Prototype drop-down would include the text in the field along with the hex code -- so you could label a baseline drawing as "Indoor" and it would show up as such on the list, making it easy to have a single drawing influence the lighting in all the shapes without having to memorize the hex code.

Can we get that feature back?

**Comment by dev7355608** [comment]
Not ideal, but if you hover over the ID in drop down, it should tell you the text of the drawing. I think I removed it because the ID needs to be monospace, but the text of the drawing doesn't look nice as monospace and overflows quickly.

**Comment by LonePaladin** [comment]
I remember seeing that -- the overflow didn't really bother me, because I only put in a text label with the drawing I was using as a baseline for the lighting to copy. Having that name appear made it significantly easier to find, than having to scan an ever-increasing list of hex codes for the one that I started with.

Plus, if I need to use *two* such effects, I can easily tell which one to use later.

**Comment by dev7355608** [comment]
Perfect Vision is discontinued.
