### ISSUE TITLE
PF missing file, scripts/index.js, breaks the module and throws a critical error in Setup menu.

### ISSUE THREAD

**Issue by CatbotTsumi** [dev7355608/perfect-vision#313]
### Expected Behavior

Im expecting PF to just run smoothly :3

### Current Behavior

`[perfect-vision] Metadata validation failed for module "perfect-vision": The file "scripts/index.js" included by module perfect-vision does not exist.`
- #logPackageWarnings	@setup.js:141

Perfect Vision disappears from Add-on Modules list in setup.

### Steps to Reproduce

1. Install/update latest version.
2. Restart Foundry
3. ![image](https://user-images.githubusercontent.com/63572588/202601024-3816b7cf-a989-44ae-89db-e53a73dd7525.png)
4. ![image](https://user-images.githubusercontent.com/63572588/202601055-47a7d5da-09ef-4627-a7a1-192e52996217.png)

### Context

I've tried uninstalling and reinstalling with no luck.

### Version

v4.0.54

### Foundry VTT Version

Version 10 - Build 290

### Operating System

Windows N 10

### Browser / App

Native App (Electron)

### Game System

dnd5e (2.0.3)

**Comment by dev7355608** [comment]
No clue how what would happen. Did you try to manually delete PV from `%LocalAppData%\FoundryVTT\Data\modules` first before reinstalling?

**Comment by CatbotTsumi** [comment]
Hey that appears to work! Seems all functional again! Thanks!
_I feel dumb for not trying that before 🤦‍♀️_
