### ISSUE TITLE
Use darkness value from scene global illumination setting within a drawing if larger than drawings

### ISSUE THREAD

**Issue by diwako** [dev7355608/perfect-vision#314]
### Description

I do not set a vision range on tokens and use the global illumination setting to give tokens vision. The vision range setting is only used if tokens have a means of seeing in the dark (system is Cyberpunk RED, so night vision goggles or cybernetic eyes with upgrades).
While setting up scenes to be used during day or night I define indoor areas with their own darkness value using drawings.

This however means during night the global illumination darkness value for the scene is higher than the indoor areas and all drawings need manual updating, else the supposedly shaded area in the scene has suddenly become the brighter one.

As the current behavior has many use cases, the proposal should not be a new norm.
But I would like to request a check box or a drop down field to dictate drawings to use the scenes darkness levels if they are higher instead of the set one.

### Context

A mockup, to hopefully make more sense than my ramblings above
![image](https://user-images.githubusercontent.com/8259498/203590423-8a29ecdc-4119-4c07-8b82-7beb0041325f.png)

**Comment by dev7355608** [comment]
No new features are going to be added to Perfect Vision anymore (see #334).
