### ISSUE TITLE
Question/Inquiry:  How to set "lighting priority" via a macro?

### ISSUE THREAD

**Issue by karpana** [dev7355608/perfect-vision#315]
### Expected Behavior

Inquiry only: 

Looking to find out how I can modify this Foundry Community Macros to set the Lighting Priority in order to leverage caster level of magical light and darkness to set the various priorities when one type of magical light/darkness defeats another kind.
[https://github.com/foundry-vtt-community/macros/blob/main/token/light_picker.js](https://github.com/foundry-vtt-community/macros/blob/main/token/light_picker.js)

In short, I'd like to learn how to adapt this code to set the Perfect-Vision priority when the light source is updated via the macro.  Note: I've shortened the macro/code to only show two of the many buttons.

```js
function tokenUpdate(data) {
  canvas.tokens.controlled.map(token => token.document.update({light: data}));
}

let torchAnimation = {"type": "torch", "speed": 1, "intensity": 1, "reverse": false};

let dialogEditor = new Dialog({
  title: `Token Light Picker`,
  content: `Pick the light source the selected token is holding.`,
  buttons: {
    none: {
      label: `None`,
      callback: () => {
        tokenUpdate({"dim": 0, "bright": 0, "angle": 360, "luminosity": 0.5});
        dialogEditor.render(true);
      }
    },
    light: {
      label: `Light cantrip`,
      callback: () => {
        tokenUpdate({"dim": 40, "bright": 20, "angle": 360, "luminosity": 0.5, "animation": {"type": "none"}});
        dialogEditor.render(true);
      }
    },
    close: {
      icon: "<i class='fas fa-tick'></i>",
      label: `Close`
    },
  },
  default: "close",
  close: () => {}
});

dialogEditor.render(true)
```

### Current Behavior

See Expected Behaviour

### Steps to Reproduce

N/A.  See Expecdted Behaviour

### Context

As a Pathfinder 1E GM, there are all sorts of various competing priorities in light and darkness spells.
For example 

- any mundane lighting source defeats darkness (absence of light, not the spell)
- the darkness spell defeats mundane and mangical lighting sources
- daylight spell defeats darkness spell
- deeper darkness spell and daylight cancel each other out, but other sources fail to function

all told, it's super brutal.

I'm hoping to use Perfect-Vision's "lighting priority" with a modified version of the Community Macros `light picker` to set lighting priorities based on the source of the light's caster level.

### Version

v4.1.0

### Foundry VTT Version

v10.290

### Operating System

Client machine is windows; server machine is Rapsbian Linux

### Browser / App

Chrome

### Game System

pf1e (v0.82.2)

**Comment by dev7355608** [comment]
Priority is actually a core token/light flag and works without PV; PV just exposes it in the config.
```js
document.setFlag("core", "priority", 10);
document.update({ "flags.core.priority": 10 });
```
Do you just want to set the priority, or do you want to set vision limitation too?

**Comment by karpana** [comment]
For now, it's just the priority, but just in case, how does one set the vision limitation?

**Comment by dev7355608** [comment]
```js
let visionLimitation=  {
    enabled: true,
    sight: 30, // vision limit
    detection: { // detection mode limits (optional)
        // seeAll: 0,
    }
};
token.document.update({
    "flags.perfect-vision.light.visionLimitation": visionLimitation
});
light.document.update({
    "flags.perfect-vision.visionLimitation": visionLimitation
});
```

Daylight spell:
```js
let visionLimitation=  {
    enabled: true,
    sight: null, // null means infinity (no restriction)
};
// luminosity > 0
```
Darkness spell:
```js
let visionLimitation=  {
    enabled: true,
    sight: 0,
};
// luminosity < 0
```
Depending of the priority, one overrides the other where they overlap.

**Comment by karpana** [comment]
Thank you.
The assistgance is much appreciated.
I'll close this ticket.
