### ISSUE TITLE
Overall performance issue & Sight Limit Standalone

### ISSUE THREAD

**Issue by RudeCanine** [dev7355608/perfect-vision#319]
### Description

Sorry if this should be labeled differently, not really used to Github. 

Since updating to V10 I've been having a lot of performance issues with Perfect vision, mainly since I play with 150 degree vision, whenever my players need to turn the game stutters and adds overall lag to foundry. I realize this is because Foundry itself has a bunch of new shit from V9 and V10 that perfect vision essentially has to work around, that was not in previous versions.

Is there anyway to improve overall performance? I've checked with all of my other modules turned off, and it's only perfect vision stuttering. My computer is a beefy rig and Foundry runs cool, even with 5 players connected, it's just perfect vision.

For the record, I love perfect vision and what it did for me in the previous iterations. Limiting Vision is mainly what I use it for now, so it would be wonderful if there was just a standalone module for that. Thank you!

**Comment by RudeCanine** [comment]
By exporting one of the scenes, are you referring to the "Export Data" feature, or are we talking a bite-sized adventure import? Also I'm running 5e.

Sorry for slow response :-)

**Comment by dev7355608** [comment]
The .json file you get from Export Data.

**Comment by RudeCanine** [comment]
For sure, here's a zip; I ran some 50 modules in my campaign but I'm still having issues with all of them inactive. 

There'll be some tokens to the north of the map, and when I spin them around that's when it stutters; especially in that location.
[fvtt-Scene-death-house.zip](https://github.com/dev7355608/perfect-vision/files/10202708/fvtt-Scene-death-house.zip)

**Comment by RudeCanine** [comment]
Updated to latest version, I was apparently running 4.1.7, which might've been the issue (with foundry 10.288 & and 10.291) and apparently that fixed it. Most likely just an issue with foundry rather than the actual module, strange enough. 

FPS drops with PV are still happening, the game runs at 165FPS and when turning in that area it drops about 20-40FPS, but that's not that bothersome since it still runs well above 60fps; whereas with regular foundry it doesn't drop more than 10FPS.

Could be my machine, but I don't really tend to have any particular issues with performance lest I try running AAA games on ultra. Thank you for the chat though, it's been enlightening haha

**Comment by dev7355608** [comment]
Have you compared Fog Exploration On vs. Off both with PV enabled and disabled?

To measure the FPS more reliable, instead of rotating the token just select it and execute this script-macro. Keep the rotation the same for all benchmarks.
```js
globalThis._updateVisionTicker ??= canvas.app.ticker.add(() => {
    if (!_token) return;
    _token.updateVisionSource({ defer: true });
    canvas.perception.update({
        forceUpdateFog: _token.hasLimitedSourceAngle,
        refreshLighting: true,
        refreshVision: true
    }, true);
});
```
