### ISSUE TITLE
[Feature Request] Match Scene luminescence

### ISSUE THREAD

**Issue by roguedevjake** [dev7355608/perfect-vision#321]
### Description

It would be incredibly useful for interior/exterior shared scenes to have lights that could sync their luminescence with the current scene darkness value.

This would primarily be used for ambient daylight/moonlight filtering in through windows and open doorways into masked areas.

Another good option would be an offset slider, so it would match the scene's darkness  value and be adjusted up or down by the amount indicated by the slider (to a min/max of -1 or 1)

**Comment by dev7355608** [comment]
What do you mean by "luminescence"? The *Luminosity* value of the light source?

**Comment by Yuffyyy** [comment]
If Roguedevjake meant luminosity, I hundred percent agrees with him, I miss that possibility for my maps ♥
If the lights would sync though it would mean there is no need anymore for masking. Walls would do the trick with those lights being able to emulate sun/moon. In addition with smalltime and with global illumination turned off it would just make the combination indoor/outdoor, perfect

**Comment by dev7355608** [comment]
I'm still not sure what this issue is exactly about. So it's about simulating global light shining through windows into a dark building? I'm not sure what that has to do with Luminosity specifically. It would help if you described what you try to achieve and what your current solution is. Global light shining into the interior of buildings through windows without placing a bunch of light sources has been requested multiple times, and I hope I can offer a one-click solution for it in the future, but it isn't easily implemented.

**Comment by Yuffyyy** [comment]
I get that it's not easeliy implementable. It is about simulation global luminosity shining through windows into a dark building. But also being able to have that light synchronised so you don't have to change a bunch of lights each time. (PLacing them is one thinng but updating them each time the luminosity ischanged is a hassle.

To this day I'm using smalltime for the ability to have the global illumination change with the time of day and the calendar. And use the perfect visions masks without lights from windows fro mtimeto time if it really fits the scene.

**Comment by dev7355608** [comment]
I have big changes planned for PV for the next major release (5.0 / V11+); big changes on the UI level at least as I plan to move away from using drawings as means to define lighting areas. So there might be an opportunity to implemented placement for such special light sources that are sync'd with the associated area. We'll have to see.

**Comment by Yuffyyy** [comment]
That would be so cool ! ♥♥♥

**Comment by dev7355608** [comment]
Update: Perfect Vision isn't going to be updated for V11 (see #334 for more details).
