### ISSUE TITLE
Issue when downlading Stuck at 2-3%

### ISSUE THREAD

**Issue by Zarhog** [dev7355608/perfect-vision#322]
### Expected Behavior

Modual should downaload

### Current Behavior

Modual will get stuck when downlaoding

### Steps to Reproduce

Be Running F-VTT Version 10 - Build 290
Download current modual from install on Foundry
Watch as it dosnt downlad

### Version

1.1.14

### Foundry VTT Version

Version 10 - Build 290

### Operating System

Access computer = Win 11 / Server = Lynix

### Browser / App

Chrome, Other

### Game System

D&D 5e

**Comment by dev7355608** [comment]
Probably some temporary network problem. I just checked and it installs for me without issue. Is there an error message in the console (F12 -> Console tab) when you try to install it?
