### ISSUE TITLE
Hearing limit has no effect (PF2e)

### ISSUE THREAD

**Issue by DenMesh** [dev7355608/perfect-vision#323]
### Expected Behavior

Expected: if I set all senses limits to 30 ft, nothing outside this range should be visible.
![image](https://user-images.githubusercontent.com/9051037/213600171-338aacb0-3934-4dd5-b5c0-9e2ed0380e96.png)

### Current Behavior

Current: token outside senses range is detected as if by "imprecise sense".
![image](https://user-images.githubusercontent.com/9051037/213600333-a14c9523-6fcf-472a-8561-c4fd791c2bb4.png)

### Steps to Reproduce

1. Create a new scene
2. Set all vision ranges to 30 ft
3. Place a PC and an NPC more than 30 ft apart

### Version

4.1.14

### Foundry VTT Version

10.291

### Operating System

Windows

### Browser / App

Firefox

### Game System

pf2e (4.6.8)

### Relevant Modules

No modules other than Perfect Vision and libwrapper

**Comment by dev7355608** [comment]
Fixed in PF2e 4.8.0.
