### ISSUE TITLE
Conflict between Elevated Vision and Perfect Vision

### ISSUE THREAD

**Issue by baileywick** [dev7355608/perfect-vision#327]
### Expected Behavior

Expecting scenes to load normally when PV and EV are both active.

### Current Behavior

Scenes load to black and throw error messages. This is something that started happening recently.

### Steps to Reproduce

I'm not sure what settings I have that might be creating a conflict, but this is from Caewok (developer of EV)

There must be some setting in PV that is causing that. When I load PV and EV, I don't get any errors. But it is likely that some setting specific to your scenes triggers the conflict, and I just don't have that setting enabled in my testing. I recommend starting with filing an issue in the PV github (https://github.com/dev7355608/perfect-vision/issues) because none of those errors directly implicate EV. The PV mod developer will probably flag if there is something I should change in EV to accommodate it.

Errors are here. 
![image](https://user-images.githubusercontent.com/14203358/221430563-f0776199-6828-406a-9cdf-12df4506da89.png)

### Context

Most recent Foundry. Hosted in Oracle instance. Running Levels, EV, and PV. 

### Version

4.1.17

### Foundry VTT Version

v10.291

### Operating System

Windows

### Browser / App

Chrome

### Game System

dnd5e (2.0.3)

### Relevant Modules

elevated vision 0.4.0, levels 3.7.5

**Comment by dev7355608** [comment]
EV [0.4.1](https://github.com/caewok/fvtt-elevated-vision/releases/tag/0.4.1) should fix this issue.
