### ISSUE TITLE
DF Active Lights compatibility and light that don't "provide light"

### ISSUE THREAD

**Issue by jacksands** [dev7355608/perfect-vision#328]
### Description

first, tks for the amazing module and hard work!
I wish to ask about 2 features, if possible.

1- for the global light to be compatible with DF Active Lights (https://github.com/flamewave000/dragonflagon-fvtt/tree/master/df-active-lights)
With Active Light there a so many possibilities for animation, to use it with global light in perfect vision would be incredible!

2- For the global light to not "provide light" so it can be used to create Special Effects ambience, and that can be seen by the token that are able to see in the actual darkness level.
As an example 
on a darkness level 1 scene
the player 1 can see in darkness, so he can see an force field "light" on the ambient global light.
player 2 can't see in darkness, he sees nothing...

I don't know if there is any configuration that allow a light source to not provide "light", I don't even know if that is possible, but it would be amazing!

anyway tks for your time!

Erich

**Comment by dev7355608** [comment]
1. I'm not sure but I think Active Light would just need to animate the global light source, and I don't think I could add support for that from PV's side easily.
2. Light sources that do not shine light for just the pretty animations is a frequently requested feature: not requested from PV, but from core. That might be something that will be a core feature at some point. I'm not going to make this a PV feature though as it would require aggressive patching to make it work.

**Comment by jacksands** [comment]
thank you for your answer and effort! 

really appreciate!
