### ISSUE TITLE
Vision Delimiters are obtrusive

### ISSUE THREAD

**Issue by Monation** [dev7355608/perfect-vision#329]
### Expected Behavior

The Delimiters should relay information about vision without diminishing usability in the most critical areas of vision. Delimiters should be used for darkness, to better delimit shadows, not light. They should be black, and display a soft pattern on dim light, and a hard pattern on darkness, with no pattern on bright light. This way, they are as unobtrusive as possible.
![Vision](https://user-images.githubusercontent.com/9889274/230562279-dd368202-b3c0-463c-9503-d170581a5ece.jpg)

### Current Behavior

Currently, the Delimiters use a white pattern that gets in the way of seeing what's actually on the screen. It's most obtrusive in bright light, which should be the most easily visible.
![VisionCurrent](https://user-images.githubusercontent.com/9889274/230562173-7b76e5be-b170-457f-8f6d-93ebdbc45d08.jpg)

### Steps to Reproduce

1. Create a scene
2. In the scene's lighting options, set the scene's darkness level to 1
3. Place a token on the scene, and give it a torch or other source of light with both dim and bright light
4. Click on the Toggle Delimiters button

### Context

Many systems now use high amounts of attenuation for their lights, which make for realistic gradients in lighting, but which make it impossible to discern where bright light ends and dim light begins, and the same with darkness. Since attacks have miss chance from concealment depending on the target's level of illumination and the attacker's quality of vision, this becomes a problem.

This issue is solved by Vision Delimiters, which make it easy to know exactly where areas of light begin and end, but the issue is that they are currently *very* obtrusive, but a slight change can greatly improve usability.

### Version

4.1.19

### Foundry VTT Version

v10.291

### Operating System

W 10indows

### Browser / App

Firefox

### Game System

PF2

**Comment by dev7355608** [comment]
I agree: your suggestion looks much better. But Perfect Vision is not going to be updated for V11 and is not going to receive any more updates for V10 except critical bug fixes. I don't have plans to make Vision Delimiters its own module for V11 at the moment. That might change, but it might also not. Should I make its own module, I'll definitely consider your suggestion.
