### ISSUE TITLE
Players can't see terrain when Global Illumination is dark.

### ISSUE THREAD

**Issue by TenguGrib** [dev7355608/perfect-vision#330]
### Expected Behavior

Tokens should be able to see the terrain with darkvision, and even more so see terrain illuminated by lights. 

### Current Behavior

Player view:
![image](https://user-images.githubusercontent.com/93809766/230990975-63e1642e-d915-4bfa-a107-864ff9ce9656.png)
GM view without token selected:
![image](https://user-images.githubusercontent.com/93809766/230991121-eee9763b-416b-4ec3-96c6-79ff0a352562.png)
There's tons of lights, but all the tokens can see is other tokens. Might be conflict with Better Roofs or Levels? Disabling Perfect Vision fixes the behavior.

### Steps to Reproduce

1. using Better roofs, levels, perfect vision, and probably a few others that might be at fault. 
2. Problem only occurs with Perfect Vision enabled, without it, no issue.

### Context

Loading the scene generates these:
![image](https://user-images.githubusercontent.com/93809766/230993581-b1ccd067-9bdb-42ec-8fbc-e167408c9c1c.png)
![image](https://user-images.githubusercontent.com/93809766/230993652-8c0b7149-624b-4cce-83fa-abdd8373cc22.png)
![image](https://user-images.githubusercontent.com/93809766/230993709-ee06112c-f3b3-4fe5-9fc8-0b7fcdb0af8a.png)

### Version

v4.1.2

### Foundry VTT Version

v10.291

### Operating System

windows 10

### Browser / App

Native App (Electron)

### Game System

dnd5e 2.1.5

### Relevant Modules

levels 3.7.9, better roofs 1.7.6, Enhanced Terrain Layer 10.6, Wall Height 4.9.6

**Comment by TenguGrib** [comment]
Let me know if any other information would be helpful. Technically I don't strictly need this module, so going to disable it for now, but I like it.

**Comment by dev7355608** [comment]
The warnings are from Elevated Vision if I'm not mistaken. Are they not there if you disable Perfect Vision?

**Comment by TenguGrib** [comment]
I didn't notice them, but I might have just missed them. I'll check next time I'm at my computer. Would those be related to the issue or unrelated?

**Comment by dev7355608** [comment]
> Would those be related to the issue or unrelated?

I'm not sure. Perfect Vision + Elevated Vision hasn't been 100% compatible.

> Technically I don't strictly need this module, so going to disable it for now, but I like it.

FYI if you used PV mostly for GM Vision: I created a standalone module called *GM Vision*.

**Comment by TenguGrib** [comment]
confirmed that the issue only occurs while both Perfect Vision and Elevated Vision are both enabled, and stops when either one is disabled.

**Comment by dev7355608** [comment]
Perfect Vision is going to be updated for V11 and is not going to receive any updates that that would improve the compatibility with Elevated Vision in V10.
