### ISSUE TITLE
Can't open perfect vision settings

### ISSUE THREAD

**Issue by antoniohbmonteiro** [dev7355608/perfect-vision#332]
### Expected Behavior

I see tutorials with the settings to choose system 5e, but i cant see it!

### Current Behavior

I cant see settings to perfect vision

### Steps to Reproduce

install, active, cant see settings

### Version

4.1.20

### Foundry VTT Version

v10.291

### Operating System

Windows

### Browser / App

Native App (Electron)

### Game System

dnd5e

**Comment by dev7355608** [comment]
Those settings do not exist anymore, because V10 added Vision Modes, which made Perfect Vision's vision rules and monochrome vision obsolete.
