### ISSUE TITLE
Keeping Global Illumination Threshold

### ISSUE THREAD

**Issue by Oryan77** [dev7355608/perfect-vision#335]
### Description

When I install Perfect Vision, I lose the option for Global Illumination Threshold in the Scene Config. Any chance of this option remaining after install?
![image](https://github.com/dev7355608/perfect-vision/assets/49130820/bd29981d-93df-400f-be53-fde0be7e6d39)

**Comment by dev7355608** [comment]
Inside the Global Illumination Config you can set the Darkness Activation Range just like for any other light source. Behind the scenes it configures the Global Illumination Threshold. It's just exposed differently in the UI.
