### ISSUE TITLE
Bug: Vision not being changed when senses are added.

### ISSUE THREAD

**Issue by sharkbruhaha** [dev7355608/perfect-vision#34]
Tried adding to the main actor and to actors in a scene and no vision changes are made when sense(s) are added.

**Comment by dev7355608** [comment]
Are you talking about the senses configuration in the character sheet?
![image](https://user-images.githubusercontent.com/31905376/102989340-c237d200-4515-11eb-8051-643df7c6c1f6.png)

You have to set dim/bright vision in the token configuration.
