### ISSUE TITLE
add an option to force all tokens on a canvas to have a ruleset of vision.

### ISSUE THREAD

**Issue by ThingsCouldGetDicey** [dev7355608/perfect-vision#35]
please could you add the functionality of clicking a button on the settings to find and replace the ruleset box with the desired ruleset options for vision. as currently every token and anctor doesnt have the default mode enabled which for me would be 5e.

**Comment by dev7355608** [comment]
Every token starts with _Default_, and this means use module level settings, which should be the 5e rules in your case. No need to set each token's vision rules to 5e. Just leave it at _Default_.

**Comment by ThingsCouldGetDicey** [comment]
okay thank you. its kinda confusing to have a drop down menu to select tokens vision options on the tokens. maybe remove that to save confusion? just a suggestion.

**Comment by dev7355608** [comment]
It's now,  for example, _Default (Dungeons & Dragons 5e)_ instead of just _Default_ in v1.2.20. This should make it more obvious.
