### ISSUE TITLE
mookAI compatability issue

### ISSUE THREAD

**Issue by dwonderley** [dev7355608/perfect-vision#36]
Hey there!

I'm the developer for the [mookAI module](https://github.com/dwonderley/mookAI). Earlier today, someone raised [an issue ](https://github.com/dwonderley/mookAI/issues/15) about compatability issues between our modules. The issuer noted that the AI was planning attacks from NPCs to PCs that should be hidden from their vision.

I looked through my code, and the way vision is checked is through the following call to the FVTT API:
```
	canSee (id_)
	{
		// I have no idea how this works, but it seems to anyway
		return canvas.tokens.children[0].children.some (e =>
			{ return e.id === id_ && e.isVisible; });
	}
```
To be quite honest, I'm not entirely sure how the isVisible property ends up being set there, but I suspect that it isn't being updated for the change in vision rules. I plan to look into this some more tonight, and hopefully I can provide more information then.

**Comment by dev7355608** [comment]
```js
/**
   * Determine whether the Token is visible to the calling user's perspective.
   * Hidden Tokens are only displayed to GM Users.
   * Non-hidden Tokens are always visible if Token Vision is not required.
   * Controlled tokens are always visible.
   * All Tokens are visible to a GM user if no Token is controlled.
   *
   * @see {SightLayer#testVisibility}
   * @type {boolean}
   */
  get isVisible() {
```

`isVisible` returns true if the token is in line-of-sight of the selected token(s) and illuminated by a light source, i.e. in field-of-view of a light source. I'm not familiar with with mookAI, but you want to test for visibility from the point of view of the AI token surely. I copied & pasted something together from the Froundry code and modified it. It's not tested though. But with this code the AI wouldn't be able to see in global/universal lights outside of line-of-sight. Not sure if that is required. But I don't think this works on it's own yet, because `this._token.vision` is not initialized if it's not controlled, if I'm not mistaken.

```js
canSee(id_) {
    const token = canvas.tokens.get(id_);
    
    if (token.data.hidden) return false;
    if (!canvas.sight.tokenVision) return true;
    if (id_ === this._token.id) return true;

    const tolerance = Math.min(token.w, token.h) / 4;
    const point = token.center;

    // Determine the array of offset points to test
    const t = tolerance;
    const offsets = t > 0 ? [[0, 0],[-t,0],[t,0],[0,-t],[0,t],[-t,-t],[-t,t],[t,t],[t,-t]] : [[0,0]];
    const points = offsets.map(o => new PIXI.Point(point.x + o[0], point.y + o[1]));

    // Test that any point falls inside a line-of-sight polygon
    const los = points.some(p => this._token.vision.los.geometry.containsPoint(p));
    if (!los) return false;

    // Test the that the point is within some light source FOV polygon
    return canvas.lighting.illumination.lights.children.some(l => {
      return points.some(p => l.fov.geometry.containsPoint(p));
    });
  }

**Comment by dev7355608** [comment]
I had a closer look at mookAI code, and, since you take control of the AI token while acting, what I mentioned above shouldn't be an issue. And you can probably use `visible` instead of `isVisible`. It should hold the cached value of `isVisible`.

```js
canSee (id_)
{
     return canvas.tokens.get(id_).visible;
}
```

**Comment by dev7355608** [comment]
I'll reopen this issue if necessary.

**Comment by dwonderley** [comment]
Thanks for taking the time to look though my code and produce such a thorough response. I'm sorry for my own late reply. I completely forgot about this over the holidays.

I didn't know there was a visible attribute! I think it must have been added in the 0.7.* series of updates, and I never thought to look. I'll use that instead and see if it resolves the issue. 

Thanks again :)
