### ISSUE TITLE
Greyscale whole map

### ISSUE THREAD

**Issue by dmferd** [dev7355608/perfect-vision#38]
After updating last night, the whole map is in greyscale at night even if no token is clicked, except where I have a light source.  Before the map still had colour when no token was highlighted.

**Comment by dmferd** [comment]
But as the DM, if I have no taken/actor selected, why am I seeing the map as monochrome at night, I should still be seeing the map in colour

**Comment by dev7355608** [comment]
Changes in v1.6.0: With *Improved GM Vision* the map is now in color at night, but without it's still grayscale as intended.

**Comment by dmferd** [comment]
Awesome, thank you
