### ISSUE TITLE
Double dialogs?

### ISSUE THREAD

**Issue by mkahvi** [dev7355608/perfect-vision#4]
For some reason Perfect Vision is making configure game settings to open double dialogs for everything (opening permissions manager, configure audio/video, and any module and system specific dialogs).

I used Find the Culprit to narrow it down and the issue happens only with Perfect Vision enabled (double confirmed with test world where the only module is Perfect Vision).

Environment:  
> FVTT 0.7.7  
> PF1e 0.75.13  
> Chrome (Node.js hosted)

**Comment by dev7355608** [comment]
Fixed in v1.2.0.
