### ISSUE TITLE
Expansion of the Sight Settings to Include Monochrome Vision for Dim Light and Bright Light

### ISSUE THREAD

**Issue by kamatikos** [dev7355608/perfect-vision#43]
I am requesting this enhancement because I would like to be able to set the vision of tokens such that light does not except the monochrome vision produced by the filter.

____

Current behaviour that is unmodifiable:

- A token with monochrome vision (dim or bright) lends lights and their respectively illuminated areas (both dim and bright) to be rendered in polychrome.

Behaviour with expanded modification:

- A token with monochrome vision (dim or bright) lends lights and their respectively illuminated areas (both dim and bright) to be rendered solely in monochrome.

____

This request would require the implementation of (and configurability for) rules defining dim vision and bright vision each viewing both dim and bright light.

**Comment by dev7355608** [comment]
Do you just need a colorblind option (#16), or do really want to have vision that sees darkness in color but lights monochrome?

**Comment by kamatikos** [comment]
I'm requesting the ability to selectively have the monochrome filter applied to areas of light (in addition to the current ability to do so for darkness), based on token vision; not a colorblind option.

**Comment by dev7355608** [comment]
Do you want vision that sees light within X feet as monochrome, but beyond that light renders normally?

![image](https://user-images.githubusercontent.com/31905376/104089202-2922ee00-526d-11eb-83bd-6d39d01e21ad.png)

Or do you want all light sources to be completely monochrome?

![image](https://user-images.githubusercontent.com/31905376/104089372-c03c7580-526e-11eb-899a-070fcebad4b6.png)

**Comment by kamatikos** [comment]
For my specific use-cases, either would suffice.

**Comment by dev7355608** [comment]
What specific vision do you want to recreate? Are the rules part of a system or homebrew?

**Comment by kamatikos** [comment]
Homebrew.

**Comment by dev7355608** [comment]
I'm probably not going to add this. Closing for now.
