### ISSUE TITLE
Feature Request - Add Setting to Completely Obscure Areas of the Scene in Fog of War

### ISSUE THREAD

**Issue by OmnesPotens** [dev7355608/perfect-vision#44]
There is currently a setting called "Actual Fog of War" that overlays the fog of war with an effect. I would like a setting that completely obscures the underlying Scene so that any background images are hidden. 

This could likely be accomplished by adding a setting that simply overlays an opaque black color instead of a fog effect.

Thank you for all the great work you are doing!

**Comment by dev7355608** [comment]
Maybe I'm missing something but wouldn't that be the same as simply disabling Fog Exploration?

**Comment by OmnesPotens** [comment]
Hm, actually yes I think that accomplishes the same thing! Sorry for opening a ticket without considering all the alternatives :)
