### ISSUE TITLE
[FEATURE] Easy toggle Improved GM Vision

### ISSUE THREAD

**Issue by 9ryex5** [dev7355608/perfect-vision#45]
It would be really helpful to have an easy/fast way to toggle Improved GM Vision.
A shortcut key would be perfect, another option is a button here:
![image](https://user-images.githubusercontent.com/43207603/104052382-8d986b80-51e1-11eb-9533-4494d35aa248.png)

In my case I livestream sessions in the GM perspective, so it's useful to have Improved GM Vision disabled most of the time, but quickly enable it to see needed stuff.

**Comment by dev7355608** [comment]
I'm going to add a button to the lighting controls; that's a good idea. You can also use a script macro to toggle Improved GM Vision:

```js
game.settings.set("perfect-vision", "improvedGMVision", !game.settings.get("perfect-vision", "improvedGMVision"));
```

**Comment by dev7355608** [comment]
Added in v1.6.1.
