### ISSUE TITLE
FEATURE - point of vision setting

### ISSUE THREAD

**Issue by SomethingSimpl** [dev7355608/perfect-vision#47]
Hi, there used to be a module called point of vision, where you could specify which points cast the vision - center, corners etc. Unfortunately this doesn't seem to work correctly anymore and I figured it could be a good vision enhancement in your module here.

Ideally Id like to be able to set for example all corners to be sources of players vision, so they can "peek" around a wall instead of me moving the token back and forth. This is especially limiting with windows, where when you only cast vision out of the center of the token, it reveals only a tiny slice of the room for example.

**Comment by sharkbruhaha** [comment]
@SomethingSimpl there are still a couple that are supported for this. I'm out atm, but can get you names tonight if you don't find them beforehand.

**Comment by dev7355608** [comment]
Perfect Vision is never going to provide this feature.
