### ISSUE TITLE
Daylight color doesn't affect tiles and affects darkvision even with no light

### ISSUE THREAD

**Issue by Zamrod** [dev7355608/perfect-vision#48]
When changing the daylight color setting, it doesn't change any colors in the scene at all if global lighting is turned on at all. It only works with no light in the scene. That doesn't seem to make much sense.

**Comment by Zamrod** [comment]
After reviewing this a bit more, it appears to be because the tint doesn't affect tiles so scenes with a tile used as the background will not be affected.

**Comment by Zamrod** [comment]
It appears that the tint applies to greyscale vision, even with global illumination turned off and darkness set to 1. I was trying to create a scene where the sun shines in an orange tint but at night, change the darkness to 1, which disables global illumination. People with darkvision are still seeing in orange, however.

**Comment by dev7355608** [comment]
You are right, the scene color shouldn't affect vision in darkness. I'll fix that.

Could you send me a screenshot of the tiles problem? I'm not sure how it's possible that they are not affected by the daylight color.

**Comment by dev7355608** [comment]
Fixed the color issue in v1.6.1.

**Comment by dev7355608** [comment]
I assume the tiles problem is no longer an issue. If not, let me know.
