### ISSUE TITLE
Error being thrown in player clients on module settings lookup 

### ISSUE THREAD

**Issue by rsimoes** [dev7355608/perfect-vision#49]
E.g.: https://github.com/dev7355608/perfect-vision/blob/f58083b50fbc6d48b1fa861fe95951dc65ff6c42/perfect-vision.js#L610

Players have no module settings for Perfect Vision, so the `find` call is returning `undefined`.

**Comment by dev7355608** [comment]
Thanks. Fixed in v1.6.1.
