### ISSUE TITLE
When changing darkness level the level of brightness doesn't go down for a token selected

### ISSUE THREAD

**Issue by Zamrod** [dev7355608/perfect-vision#51]
Steps to reproduce:
1. Select a token
2. Go into the Configure screen for the scene you are in
3. Change the Darkness level.
4. Save the configuration
5. Click on any other token in the scene and their vision will be darker (or brighter) than the one you had selected while the changes were being made. You can switch back and forth and see the brightness go up and down.

The effects of this go away on a refresh or switch to another scene.

**Comment by dev7355608** [comment]
You discovered another problem related to [this issue](https://gitlab.com/foundrynet/foundryvtt/-/issues/4263). I'll describe the problem there later. I'm going add temporary fix as well in v1.6.2.
