### ISSUE TITLE
Tokens with a position value greater than 5000 are moved to 5000 on reload

### ISSUE THREAD

**Issue by Dr-KerbalMD** [dev7355608/perfect-vision#55]
So let me preface this by saying that I'm running [Knave](https://github.com/jrommann/knave) and I cannot reproduce it in 5e. If systems other than D&D and PF are simply unsupported, disregard.

If I have a token at a position greater than about 5000, on reload the token is moved to ~5000. Happens on both X and Y axes. It's not super precise about going right to 5000x5000, it seems to favor 5300x4700 specifically. It's like there's some invisible box around 5000x5000, and upon refresh every token outside that box is moved to the closest point within the box.

**Comment by Aarndal** [comment]
I am using the current version of the D&D 5e game system (v1.2.4), but Foundry VTT Version 0.7.8 and I have the same issues as reported above. Deactivating the module resets the tokens to their original position.

**Comment by dev7355608** [comment]
I'm not able to reproduce this. I tested it with 0.7.9. Does it happen when Perfect Vision is the only active module? Perfect Vision doesn't touch token positions. I can't think of anything that would cause this. It's quite odd.

**Comment by Aarndal** [comment]
I can reproduce the issue every time with Perfect Vision being the only module activated. But I only tested it with 0.7.8 so far.
