### ISSUE TITLE
Improved DM Vision dont work

### ISSUE THREAD

**Issue by yReneleon** [dev7355608/perfect-vision#56]
When i set the Scene light to Scene Darkness i dont see the map as DM.
There is no diffrent if i check the Improved DM Vision or uncheck it.

I set the Darknes color to full dark because i dont want that the player will see the map but as dm i want.

![Bild_2021-03-02_202241](https://user-images.githubusercontent.com/79937869/109702823-09d17e80-7b95-11eb-8f76-b5937ffaf604.png)
![Unbenannt](https://user-images.githubusercontent.com/79937869/109702910-253c8980-7b95-11eb-9894-004cd398d10e.JPG)

**Comment by dev7355608** [comment]
You must not set the Darkness Color to black. Darkness Color is just the color of dim/dark light or illuminated areas (if the Darkness Level is 1). Best to leave it at default. If you don't want players to see the map, disable Global Illumination.

**Comment by dev7355608** [comment]
I assume this issue is resolved. If not, let me know.
