### ISSUE TITLE
Devil's Sight

### ISSUE THREAD

**Issue by SaintVidar** [dev7355608/perfect-vision#57]
I really like Perfect Vision so let's start there.  I think you have Darkvision nailed.  However, Devil's Sight does not work as it should for D&D 5E.  RAW, bright light and complete darkness should be as bright light.  Dim light is unaffected.  Now if the creature has both darkvision and Devil's Sight, it's bright vision to the edge of darkvision (usually 60ft) and then dim unaffected and darkness as bright light to 120 ft.  Also, Darkness (which could be done in Foundry as a negative aura should block the darkvision and be ignored by Devil's Sight.

This module is so close to perfect.  Can we get one last push to live up to the name?

**Comment by dev7355608** [comment]
Devil's Sight should be working. It might be related to #58 if you tried to set up Devil's Sight to be non-monochromatic. I fixed that in v1.7.3. Let me know if it's still not working as you expect.

Regarding dark (negative) light sources: they block the visual effect of darkvision but don't block sight like walls. I assume you want those light sources to restrict sight, right?

**Comment by SaintVidar** [comment]
Man, we are SO close.

![image](https://user-images.githubusercontent.com/80364334/111884159-21cb3f80-8996-11eb-9173-42ffd0c32538.png)
In this picture, Hasp has Devil's Sight, Viskar has a light that throws bright light 10 ft and dim light 20 feet.  It is the only light in the room.  Teldrig has Darkvsion to 120ft.

- Viskar only sees bright to 10 ft, dim to 20ft.  Perfect Vision.
- Teldrig sees only bright light in the 20ft brightly and dimly lit areas and dimly lit in the normal darkness.  Teldrig can see Hasp standing in the darkness as dim light.  Perfect Vision.
- Hasp sees the entire room as bright light.  Not Perfect Vision.  Hasp does not have darkvision.  He has Devil's Sight.  Devil's Sight has no effect on Dim light.  So what Hasp SHOULD see is bright light where there is both bright light and darkness and dim light where there is dim light because his devil's sight has no effect.   There should be a ring of dim light around Viskar from 10-20ft where Hasp can see dimly.

If a negative light source is supposed to be magical darkness (and I think it is, because I'm not sure how you would use it otherwise), then devil's sight should see right through it, whether on the token with the vision or not.  Darkvision and normal vision should not be able to see it.  There are a lot of conditions based on spell casting level of a light spell or a Darkness, Hunger of Hadar, Maddening Darkness, etc spell that should determine how light overlaps interact.  But assuming it's an orb of magical darkness without a competing spell light source, only Devil's Sight should see through it.

**Comment by SaintVidar** [comment]
And I just checked the Darkness by putting a -15ft bright and dim light on Hasp.  With Hasp selected, it's inky black to 15ft and then brightly lit beyond that.  He shouldn't see it at all.

![image](https://user-images.githubusercontent.com/80364334/111884531-93a48880-8998-11eb-9708-0d6482ca36e3.png)

**Comment by dev7355608** [comment]
It's working for me . If you set *Dim/Bright Vision in Dim Light* to *Dim Light*, dim light stays dim light.
![image](https://user-images.githubusercontent.com/31905376/111888772-d2116600-89df-11eb-9113-bc5f44e919a8.png)
Maybe I'm missing something.

Negative lights blocking sight would be quite nice, but that isn't easily achieved by a module; it would be best if this feature was added to core Foundry. But I'm not sure if negative lights are supposed to be more than just a visual effect though.

**Comment by dev7355608** [comment]
I could add an option to allow vision to override negative light sources. But that won't be worth the effort as long as negative light sources don't block sight. It would be a rarely-used feature anyway.

**Comment by SaintVidar** [comment]
Ah.  I was using the Default DND 5e rules.  I'll try this.

**Comment by SaintVidar** [comment]
Confirmed.  PERFECT VISION!

**Comment by SaintVidar** [comment]
I'm not so sure about rarely used.  I have yet to play in a game of DND 5e where a Sorcerer or Sorlock was not gaining advantage using Devil's Sight and Darkness.

**Comment by geoidesic** [comment]
What does it mean in practical terms in Foundry to "have Devil's Sight"? Or in other words - how would I give a token "Devil's Sight"?

**Comment by dev7355608** [comment]
In the token configuration set *Vision Rules* to *Custom*. Then set *Bright Vision in Darkness* to *Bright Light* (or *Bright Light (monochrome)*, whichever you prefer) and *Bright Vision in Dim Light* to *Dim Light*. Then set *Bright Vision* to *120*. Then the token has Devil's Sight. Alternatively you can modify the behavior of *Dim Vision* instead.
