### ISSUE TITLE
Dim Vision in Darkness set as Dim Light is much darker than actual Dim Light

### ISSUE THREAD

**Issue by Fraxinus1753** [dev7355608/perfect-vision#58]
Hi, I love the module, but would rather not use monochrome vision. However, when I set "Dim Vision in Darkness" as "Dim Light" and not "Dim Light (monochrome)", the Dim Light created by Dim Vision in Darkness when Scene Darkness is set to 1 is actually much darker than regular Dim Light (e.g. Dim Light created by a token emitting light with Scene Darkness set to 1). 

It's so dark than it's actually very difficult to see anything, while I have no problem seeing anything when using the "Dim Light (monochrome)" option for Dim Vision in Darkness. 

This was tested with Perfect Vision as the only module enabled.

**Comment by Fraxinus1753** [comment]
Illustration: the screenshot below shows a regular dim light source on the left-hand side, and dim light as rendered by darkvision in darkness (with monochrome option disabled) on the right-hand side. The intersection is bright light, as per D&D 5e rules. 

![Perfect Vision Dim Vision in Darkness](https://user-images.githubusercontent.com/41876735/111771213-b4db7b00-88ab-11eb-9bd6-b1bfb1d35086.png)

The screenshot below shows the same situation, but with monochrome option enabled. This time, dim light as rendered by darkvision in darkness is the same brightness level as regular dim light. 
![Perfect Vision Dim Vision in Darkness monochrome option](https://user-images.githubusercontent.com/41876735/111771285-c91f7800-88ab-11eb-9b29-8801839077dd.png)

**Comment by Zamrod** [comment]
I can verify, having run tests that while Perfect Vision is installed Dim Vision is dimmer than Dim Lights and Bright Vision is dimmer than Bright Lights. As soon as PV is disabled, they go back to being the same brightness.

**Comment by dev7355608** [comment]
Fixed in v1.7.3.
