### ISSUE TITLE
Darkvision loses all it's color.

### ISSUE THREAD

**Issue by akkyo** [dev7355608/perfect-vision#59]
In the new version that today Perfect Vision was updated to, has the blueish tint been removed from Darkvision? I used to use Foundry VTT default settings for my Darkvision settings, and there was a blueish tint and it was dark, just how I liked it.

Now I need to use custom settings, with scene darkness in some fields and not even then I can get the blue color of night. It bugs out with torches, showing a blue outline like the previous version had.

Please bring back the older version. Now I don’t like how it looks. I would want to have that blue tint in the player’s darkvision as it gave it a true night tone as shown in the GM’s version of night. Now it’s just monochrome, and torches or lights have a blueish tint at the edge, making them ugly.

I'd make the player's version of night, in scene darkness, as seen in the GM's version. As a player, I would want to have that blue tone the GM has.

**Comment by akkyo** [comment]
![7a15d6d56fad3d5b9c46612c5a4daf66](https://user-images.githubusercontent.com/40145730/111888481-37178c80-89dd-11eb-938a-001717b73bda.png)

I think in this photo is noticeable. Vision in Dim Light is monochrome, but outside the vision is blue. I would like an option to enable seeing that blue on all the darkvision. Thanks for your time!

**Comment by Bobsson** [comment]
@akkyo I think this is intentional.  Take a look at the "Monochrome Vision Color" section on the main page.  If you want to have darkvision be blue-tinted, try changing that setting from white to something blue-ish?

**Comment by dev7355608** [comment]
In PV 2.0 the blue darkness tint is there, but the monochrome filter is now applied at the very end as it should be, removing the blue tint again basically. This is intended: grayscale vision shouldn't be blueish. If you want it blueish, you have to use the vision color setting.
