### ISSUE TITLE
5e vision doesn't work as intended

### ISSUE THREAD

**Issue by DarKDinDoN** [dev7355608/perfect-vision#6]
Hello,

Using 5e 1.1.1 & FVTT 0.7.7.

Configuration:

- Global illumination: true
- Token vision: true
- Fog of war: true

- Global illumination light: Dim Light
- 5e settings preset
- Monochrome token icons: true
- Monochrome special effects: true

A token should have infinite dim vision, although in the following scene it does not (no lights & no walls):
![image](https://user-images.githubusercontent.com/1687854/99452675-25858180-2924-11eb-99ff-adc639ef490a.png)

Token vision is always limited toward the edges of the scene.

Also, we can see the bright and dim radius with a token only set with dim vision on such a scene:
![image](https://user-images.githubusercontent.com/1687854/99453391-29fe6a00-2925-11eb-81ca-b8426c6c20b7.png)

**Comment by dev7355608** [comment]
This is actually a bug in Foundry's code. I reported the bug [here](https://gitlab.com/foundrynet/foundryvtt/-/issues/4136).

I fixed it anyway. So it should work now in v1.2.1.

**Comment by DarKDinDoN** [comment]
@dev7355608 confirmed. Thx!
