### ISSUE TITLE
Darkvision sight issue

### ISSUE THREAD

**Issue by cwrinn** [dev7355608/perfect-vision#62]
Foundry 0.7.9
Perfect Vision 1.7.3

In my 100% darkness scene, characters with 60ft of darkvision can see monsters over 60ft away.

Here are the scene settings.
![image](https://user-images.githubusercontent.com/46600/114118783-037aa480-98af-11eb-917a-6d1a81d32cff.png)

**Comment by dev7355608** [comment]
Disable *Global Illumination*. The *Scene Darkness* option makes the illumination darker, but it still reveals everything in line-of-sight.
