### ISSUE TITLE
Perfect Vision opens holes in walls

### ISSUE THREAD

**Issue by Opzehn** [dev7355608/perfect-vision#63]
I've tried to troubleshoot what is happening with the walls on larger maps, and I've noticed that if I have all modules disabled this is what the token in the top-left corner sees (observe the bottom-right).
https://i.imgur.com/5b5FXwS.png

This changes when I enable Perfect Vision, and only have that module enabled, and opens up a massive gap in the walls:

https://i.imgur.com/oTst2zk.png

Finally, this is how the walls have been drawn:

https://i.imgur.com/BvXns3h.png

**Comment by dev7355608** [comment]
The first image shows a hole in the wall as well. So Perfect Vision just makes it larger? The Foundry's sight code is buggy; in some situation it ignores parts of walls. See [here](https://gitlab.com/foundrynet/foundryvtt/-/issues/3909). No clue at the moment why Perfect Vision makes it worse. If you export the scene and share it, I can take a look.

**Comment by Opzehn** [comment]
I noticed some new results when enabling and disabling Token Vision Tweaks as well as Perfect Vision as well.
This is how the walls act when only Perfect Vision is enabled:
https://i.imgur.com/FvM9esT.png
https://i.imgur.com/vPFmYNS.png (Same as above, token is just moved one square downwards, opening up the wall massively.)

https://i.imgur.com/N6AwAWX.png (This is how the wall looks like with all modules disabled.)

The original pictures provided I always had Token Vision Tweaks on with these settings: https://i.imgur.com/Q8RAvIv.png

Finally, here's the scene: https://easyupload.io/45an9y

**Comment by dev7355608** [comment]
Closing this for now because sight computation received some changes in 0.8.*, but continues to have some major problems. Not sure if this in particular is still an issue.
