### ISSUE TITLE
Possible conflict between Perfect Vision and Your Tokens Visible

### ISSUE THREAD

**Issue by nulmas** [dev7355608/perfect-vision#64]
I update all my Foundry modules today and started getting a message from libWrapper saying there was a possible conflict between an unknown module and Perfect Vision.

After running a few tests, I realized the unknown module was Your Tokens Visible. This potential conflict wasn't showing up last weekend, so it must have been introduced with Perfect Vision's latest update.

As of right now, I haven't noticed any issue, but I thought I should warn you.

I've also posted about this issue in Your Tokens Visible's Github: https://github.com/David-Zvekic/TokensVisible/issues/6

**Comment by spirritus** [comment]
Have the same issue comming up.

**Comment by nulmas** [comment]
Issue seems solved after Your Tokens Visible added libWrapper support in the last update.
