### ISSUE TITLE
Perfect Vision does not work with sight angles under 360 degrees.

### ISSUE THREAD

**Issue by jeremiahbritt** [dev7355608/perfect-vision#67]
While it partilally works, some rotations of the token cause the sight origin point to drift extremely, and it causes issues with walls.
One clip is without any modules activated, the other one is just Perfect Vision and libWrapper/

https://user-images.githubusercontent.com/11531916/114979844-67b5df00-9e40-11eb-9460-c59df1e9b15f.mp4

**Comment by dev7355608** [comment]
Fixed in v1.8.3.
