### ISSUE TITLE
Monochrome vision and low light vision

### ISSUE THREAD

**Issue by Bobsson** [dev7355608/perfect-vision#68]
Currently, enabling low light vision for a token seems to also doubles the range of their monochrome vision.  Under Pathfinder 1e (at least), low-light vision should have no effect on darkvision.

Both of these images have the token configured for 10' bright light, 20' dim light, and 30' monochrome:

Without lowlight:
![Without lowlight](https://user-images.githubusercontent.com/2022339/115168150-f10b2280-a087-11eb-9f5a-31d17ce34754.png)

With lowlight:
![With lowlight](https://user-images.githubusercontent.com/2022339/115168152-f10b2280-a087-11eb-8daf-8bfe4db5aa8a.png)

**Comment by dev7355608** [comment]
Fixed in v1.8.4.
