### ISSUE TITLE
GM Vision doesn't work at Scene Darkness 1

### ISSUE THREAD

**Issue by Noshei** [dev7355608/perfect-vision#69]
With Scene Darkness set to 1, GM Vision doesn't work.  By moving Scene Darkness to 0.95, GM Vision will work.

The scene darkness is the only change between the below screenshots.

![image](https://user-images.githubusercontent.com/8866000/115486975-f649a800-a214-11eb-8aac-e2e8927158a5.png)
![image](https://user-images.githubusercontent.com/8866000/115487011-0792b480-a215-11eb-9795-8e27c1ecd076.png)

**Comment by dev7355608** [comment]
Don't set *Darkness Color* to `#000000`. It's not a valid option at the moment. I'll need to do something about this.

**Comment by dev7355608** [comment]
Fixed in v1.8.5.
