### ISSUE TITLE
LibWrapper conflict with grape_juice-isometrics

### ISSUE THREAD

**Issue by MS-PBS** [dev7355608/perfect-vision#70]
It looks like perfect vision conflicts with grape_juice-isometrics. I know GJ-Isometrics is in alpha and there is no hurry to fix this. However, I haven't seen this reported yet, so I figured I should. Isometric scenes are not rendered correctly, and LibWrapper detects a conflict. Here's the error libwrapper throws:

> libWrapper-notifications.js:64 libWrapper: Potential conflict detected between module 'grape_juice-isometrics' and 'perfect-vision'.
> Detected non-libWrapper wrapping of 'PointSource.prototype.initialize' by 'grape_juice-isometrics'. This will potentially lead to conflicts.
> 🎁console_ui	@	libWrapper-notifications.js:64
> 🎁conflict	@	libWrapper-notifications.js:83
> 🎁warn_classic_wrapper	@	libWrapper-wrapper.js:708
> 🎁set_nonproperty	@	libWrapper-wrapper.js:686
> 🎁PointSource.prototype.initialize#setter	@	libWrapper-wrapper.js:294
> (anonymous)	@	sight.js:151
> Hooks._call#hook=canvasInit	@	libWrapper-errors.js:190
> _call	@	foundry.js:2496
> 🎁call_wrapped	@	libWrapper-wrapper.js:441
> 🎁Hooks._call#lib-wrapper	@	libWrapper-errors.js:205
> 🎁Hooks._call#0	@	libWrapper-wrapper.js:142
> callAll	@	foundry.js:2456
> draw	@	foundry.js:10172
> async function (async)		
> draw	@	foundry.js:10145
> view	@	foundry.js:34080
> SceneDirectory.dfSceneNav_onClickEntityName.SceneDirectory._onClickEntityName	@	df-scene-enhance.js:3
> dispatch	@	jquery.min.js:2
> v.handle	@	jquery.min.js:2

This was tested with Foundry 0.7.9, LibWrapper 1.5.2, PV 1.8.7 and GJ-Isometrics 0.0.16

![How the scene is rendered](https://user-images.githubusercontent.com/68601994/116809728-cd43e400-ab3f-11eb-9969-a227673d016a.JPG)
![How the scene should be rendered (PV off)](https://user-images.githubusercontent.com/68601994/116809756-ff554600-ab3f-11eb-913a-2815a77d4e69.JPG)
![Conflict message](https://user-images.githubusercontent.com/68601994/116809897-e305d900-ab40-11eb-88b3-e366a66563c6.JPG)

Link to GJ-Isometrics issue: https://gitlab.com/jesusafier/grape_juice-isometrics/-/issues/48

**Comment by dev7355608** [comment]
It's GJ-Isometrics responsibility to use libWrapper, but I very much doubt that these two modules are compatible anyway. I assume a lot of Foundry code was replaced to make isometrics possible and I don't have access to the module in order to test it.

**Comment by its-grape-juice** [comment]
The module is publicly available at https://gitlab.com/jesusafier/grape_juice-isometrics/-/tree/0.0.16-stable and on foundry's package list.

In any case, a lot of work has been done by @theripper93 to add libWrapper to the module which should be added in 0.0.19 probably.

**Comment by dev7355608** [comment]
I thought it was Patreon-only for some reason. I had a look, and it was actually very little work to make the modules compatible. Check out PV v1.8.8. Let me know if you run into other issues. I haven't tested it extensively.
