### ISSUE TITLE
Scenes without Token Vision still affected by Perfect Vision if Force Monochrome selected

### ISSUE THREAD

**Issue by foxreinhold** [dev7355608/perfect-vision#73]
In the latest version (I don't recall this happening in previous versions) scenes that do not have  Token Vision turned on are suddenly being affected by monochrome vision.  This can be fixed by globally illuminating the scene with bright light, but I do not know if this was intended.

**Comment by dev7355608** [comment]
*Force Monochrome Vision* will be removed once you upgrade to PV 1.9.0 and FVTT 0.8.5+. You will be able to control the monochrome effect with the scene setting *Saturation Level*.
