### ISSUE TITLE
Conflict with Theatre Inserts

### ISSUE THREAD

**Issue by SeattleSasquatch** [dev7355608/perfect-vision#75]
#### Steps:
1. Open a foundry world with both [Theatre Inserts](https://github.com/League-of-Foundry-Developers/fvtt-module-theatre) and Perfect Vision enabled.
2. Add two actors to the stage.

#### Results
- The actor on the right side of the screen is not shown, as the canvas Theatre Inserts is created is only 800 px wide.
![image](https://user-images.githubusercontent.com/21186541/119222075-657e1a80-baa7-11eb-99e0-bb6793c76191.png)

#### Notes
1. This issue only occurs with both modules activated.

**Comment by SeattleSasquatch** [comment]
After some quick testing, it looks like the conflict is caused by [fix.js](https://github.com/dev7355608/perfect-vision/blob/main/scripts/fix.js) overwriting both "PIXI.AbstractRenderer.prototype.resize" and "PIXI.Renderer.prototype.resize". 

--- 
Result of just commenting out those functions. Hopefully this helps with your future fix.
![image](https://user-images.githubusercontent.com/21186541/119222992-e808d900-baab-11eb-9236-fa0a1ba357cd.png)

**Comment by dev7355608** [comment]
Thanks for the report. Fixed. Check out v1.9.0.
