### ISSUE TITLE
GM Visions Option Missing 

### ISSUE THREAD

**Issue by jsmith2500** [dev7355608/perfect-vision#76]
Hello,

I read in your documentation that the GM Vision option was moved to scene configuration screen under vision and lighting controls. I can't seem to find the GM option in that section.

**Comment by dev7355608** [comment]
It should be right here: 
![image](https://user-images.githubusercontent.com/31905376/120429834-60a64a00-c376-11eb-85c8-18c408f953a0.png)

Not the scene configuration, but scene *controls*.

**Comment by jsmith2500** [comment]
AH! Thank you! It's called "lighting controls"on my system. Thank you!
