### ISSUE TITLE
Module Incompatibility | Weather Blocker

### ISSUE THREAD

**Issue by webmaster94** [dev7355608/perfect-vision#79]
Hello, just giving you a heads up that your module is incompatible with the module Weather Blocker (https://github.com/theripper93/Weather-Blocker). Not sure what could be causing the conflict as I don't know all the changes that both modules make under the hood. But I thought I would let you and the other author know. 

No errors are presented in the console to indicate what the problem may be.

**Comment by dev7355608** [comment]
All Weather Blocker compatibility problems should be resolved in 2.0.0.
