### ISSUE TITLE
Enhancement: A Setting to Customize Fog of War Display

### ISSUE THREAD

**Issue by Dumbhuman** [dev7355608/perfect-vision#8]
First off... THANK YOU!  This module is what finally made me comfortable upgrading to 0.7.7.  I've only been playing around with it for about 20 minutes, but it's utterly fantastic so far.

One potential enhancement that I think might fall into the scope of this module is to add a setting which allows for customizing how Fog of War is displayed, being able to choose a custom color tint or even some sort of patterned overlay* would make it even easier to distinguish the boundary between grayscale darkvision and explored Fog of War, especially on maps that are already low in color saturation (like gray dungeons and such).

*I thought I saw a screenshot somewhere of your module being used showing a diagonal line overlay being applied to explored Fog of War, but maybe I just dreamt that.

**Comment by rapus95** [comment]
that would also be very nice for maps with ACTUAL fog. For example in foggy swamps! or at morning, generally white fog would be very fancy!

**Comment by JamzTheMan** [comment]
I was having issue with this as well. As a work around, for darkvision, I gave it a more blueish tint  (#cfe6f7) but it looks like darkness level of the map also affects FoW and Darkvision which gives varying results?

**Comment by Hydrall** [comment]
Seconding this request. It would be useful for "world map" scenes with fog used to track player exploration; having already explored areas be monochrome makes sense normally, but it would be nice to be able to disable it for "map" scenes.

**Comment by dev7355608** [comment]
@Hydrall This should be possible now (v1.3.0) with *Global Illumination* and *Sight Limit*. You don't have to give the word map token dim or bright vision. Try this:

![image](https://user-images.githubusercontent.com/31905376/103438899-80efa280-4c38-11eb-97fb-fb82dc24eea7.png)

Be careful though, if you disable Perfect Vision and click the token, the entire fog is revealed instantly. So be aware of this. It probably isn't the best solution, but it seems to work.

**Comment by dev7355608** [comment]
Added *Actual Fog of War* in v1.4.0.
