### ISSUE TITLE
Darkvision becomes less monochrome when changing darkness levels

### ISSUE THREAD

**Issue by trdischat** [dev7355608/perfect-vision#80]
Apologies if this has been reported previously, but I have noticed a subtle issue with the monochrome rendering of darkvision and wondered whether it was intentional.  I am using version 1.9.4 of Perfect Vision in FVTT 0.8.6 and dnd5e 1.3.3.  I set PF to use the dnd5e preset for darkvision and have all other modules disabled.  I placed a token with 5' of dim vision near a standard light with 5' bright and 15' dim radius in a scene with darkness set to 1.  If I select the token, this is what I see:

![before](https://user-images.githubusercontent.com/52774325/121785680-0b391c80-cb70-11eb-89bd-c3e9325ad56d.jpg)

If I now use the lighting controls to transition from night to day then back to night, this is now what I see:

![after](https://user-images.githubusercontent.com/52774325/121785701-2c9a0880-cb70-11eb-9cac-932a5f56bf87.jpg)

The change is very subtle, but the entire scene now has a slight bluish cast.  Comparing the barrels in the darkvision area to those in the dim light area, those in darkvision are clearly rendered in greyscale, but then have a blue tinge added to them.  It is almost impossible to tell, but even the bright areas are slightly affected.  If I select another scene, then return to this scene, the color cast disappears until I change the darkness level again.

Viewing the same scene with Perfect Vision disabled, the bluish cast is always present.  So it appears that PF may be blocking the color shift caused by the darkness layer when the scene loads, but then the default behavior takes over when darkness levels change.

**Comment by dev7355608** [comment]
Thanks for the report. Fixed in v1.9.5.

**Comment by trdischat** [comment]
Confirmed the fix. Thanks.
