### ISSUE TITLE
Fog of war not resets frequently.

### ISSUE THREAD

**Issue by benbarbour** [dev7355608/perfect-vision#81]
Foundry 0.8.7, Chrome Browser.

Here's a video showing first with Perfect Vision enabled, and then without.
https://user-images.githubusercontent.com/487715/122106860-4ab17400-cdcf-11eb-8a5e-401b2f4a95ff.mp4

Here are the scene settings:
![image](https://user-images.githubusercontent.com/487715/122106977-6c126000-cdcf-11eb-86bb-3c74e58a1e9c.png)

And the Perfect Vision settings:
![image](https://user-images.githubusercontent.com/487715/122107093-8cdab580-cdcf-11eb-980d-99f23c588427.png)

**Comment by dev7355608** [comment]
Thanks for the report. Fixed in v1.9.6.
