### ISSUE TITLE
Fog shifts slightly on token movement

### ISSUE THREAD

**Issue by oamsden** [dev7355608/perfect-vision#82]
This was an issue present in previous versions of Foundry, but now I can only replicate with Perfect Vision module active.  Tests were done with only the Perfect Vision Module Active version 1.9.6 on Foundry 0.87 Hotfix 1, and is reproducible.  Seemingly each adjustment of a token that causes a fog of war update shifts the existing fog up and to the left slightly.  After many movements it becomes very noticeable and causes issues.   

For reference, scene dimensions are 6001x6001, Gridless, but with grid of 100px, 5ft.  Underlying image is 4096x4096.

![image](https://user-images.githubusercontent.com/7940000/122186930-86464f80-ce5c-11eb-9d89-182dbdc80bf8.png)

**Comment by dev7355608** [comment]
Thanks for the report. I haven't tested it extensively. I assume it is fixed in v1.9.7. Let me know if it isn't.
