### ISSUE TITLE
"Assertion Failed" error when FXMaster and libWrapper are also enabled (FVTT 0.7.9)

### ISSUE THREAD

**Issue by Metacomet10** [dev7355608/perfect-vision#88]
Hi,

I've started seeing a new error in the past week or so and I've pinned it down to when libWrapper, Perfect Vision, and FXMaster are all enabled. If only 2 of them are enabled the error is not thrown.
Screenshot below with the error:
<img width="871" alt="Screen Shot 2021-06-24 at 8 07 47 PM" src="https://user-images.githubusercontent.com/6789837/123369741-31c56300-d533-11eb-94cc-0fea8ee0f187.png">

**Comment by dev7355608** [comment]
I suspect your FXMaster isn't up to date. Try reinstalling if it doesn't want to update. Let me know if that is indeed the problem.

**Comment by Metacomet10** [comment]
Ah, right. I'm on the latest version for 0.7.9, but not on the actually latest version.

**Comment by dev7355608** [comment]
Fixed in v1.9.11.
