### ISSUE TITLE
Perfect Vision Assumes Token.prototype.updateSource was not lib-wrapped in 'Init'

### ISSUE THREAD

**Issue by David-Zvekic** [dev7355608/perfect-vision#89]
patch.js seems to try to redefine Token.prototype.updateSource (see debugger log).

if this has been previously wrapped by another module (using libWrapper.register() in hooks.once('init') for instance) then it fails with only a debugger error. An in-game symptom is that templates are not visible in dim/bright vision, but only visible if illuminated by a light source.  It's not very easy to notice.

If the other module uses libwrapper AFTER perfect-vision redefines the method, then there is no error. 

Your Tokens Visible 2.5.3 can use used to replicate this issue.

Your Tokens Visible 2.5.4 will satisfying the Perfect Vision assumption so the modules can work together.

However I thought you may want to see if you might be able to remove this assumption, or if the assumption is critical to detect when the assumption is broken and possibly  include an informative message by checking to see if libwrapper can tell you which module has wrapped the method.   This will make is easier for other module developers and GMs to notice the issue, because the debugger really doesn't help a non-developer guess why perfect-vision is failing.
![Screen Shot 2021-07-18 at 4 06 35 AM](https://user-images.githubusercontent.com/32999490/126079393-e57cb966-f7ff-4d7d-9fc5-84ef303de4cf.png)

**Comment by David-Zvekic** [comment]
actually it's even worse.... it merely says patch.js and vision.js... so the average GM would have no clue which modules are conflicting at all.

**Comment by dev7355608** [comment]
Fixed in 2.0.0: libWrapper is now a required dependency.
