### ISSUE TITLE
Huge fps drop

### ISSUE THREAD

**Issue by Ecatombe86** [dev7355608/perfect-vision#9]
Hi, i'm trying Perfect Vision (Foundry 0.7.7), I'm having HUGE fps drops when zooming in while targeting a token with vision (GPU goes crazy, 100% usage on a RTX 2080), in the console I have "GL_INVALID_FRAMEBUFFER_OPERATION: Framebuffer is incomplete." spam

**Comment by dev7355608** [comment]
Hi! Does this happen when Perfect Vision the only active module and in a fresh scene? Any more detailed error messages in the console? OS, Browser, and is there something special about your setup?

**Comment by Ecatombe86** [comment]
I'm sorry for the lack of info on the first post.
I didn't have much time to make some switch on/off on other modules. However I think that I've found the problem, it's an incompatibility with Token Magic FX.
I've tried with both on = Huge fps drop while zooming
one of the 2 off = normal behaviour

**Comment by dev7355608** [comment]
While it is laggy, I cannot reproduce the error messages. Could you export and send me the scene that gives to trouble? I'm working on some performance improvements that should reduce the lag when panning and zooming, but the error messages seem to be a different problem. If there are any further details in the console, please let me know.

**Comment by dev7355608** [comment]
Ok, I think I reproduced it. The scene you tested it in is quite large and in smaller scenes you don't get errors, correct?

**Comment by Ecatombe86** [comment]
Yes, sorry for the late response.
In smaller maps the log doesn't show anything like you said.
Is there any way to make those two mods play together? I don't know about you, but for me it's like 30% gpu usage, 60 fps with one of the two enabled, to 100% gpu usage and 10 fps (with RTX 2080! Imagine my players playing with notebooks) while using both.
I'm having the issue on the server side, not tried using browsers. Win10. I have many other modules.
Thanks again for your work

**Comment by dev7355608** [comment]
Check out v1.2.4, and let me know if it solves the problem. At least the error messages should be taken care of now.

**Comment by Ecatombe86** [comment]
Seems to be fixed, also no stuttering. Thank you!
