### ISSUE TITLE
[Conflict] LibWrapper reports a conflict with Shared Vision

### ISSUE THREAD

**Issue by tagnullde** [dev7355608/perfect-vision#91]
Not sure if I should open an issue on SharedVision aswell. Picked you because your module was mentioned first.

![image](https://user-images.githubusercontent.com/44159008/127738181-b330d87d-8bf5-436b-814e-42ed81690f7a.png)

![image](https://user-images.githubusercontent.com/44159008/127738225-c316a7a5-c2c4-4370-b670-56feff529799.png)

![image](https://user-images.githubusercontent.com/44159008/127738236-6d8e8dc0-0b5b-486c-876a-57862bd046f2.png)

**Comment by mmacgibbon** [comment]
i noticed the same thing, and it happened with the latest version of perfect vision.    im guessing/wondering, since its an override, it might just make an incompatability with the two modules?

**Comment by dev7355608** [comment]
I'm looking into it how to resolve this problem. It's not impossible to make them work together.

**Comment by dev7355608** [comment]
With PV 2.1.0 it should work correctly as long as PV gets priority, which you can give in the libWrapper settings. But the error still shows, because it still sees two attempted overrides. I'll have to contact the author of Shared Vision to get rid of the error.

**Comment by tagnullde** [comment]
Thanks. :)

**Comment by dev7355608** [comment]
Conflict resolved in PV 2.4.0.
