### ISSUE TITLE
[Conflict] v2.0.1,  Splatter texture renders above all tokens when perfect-vision is enabled

### ISSUE THREAD

**Issue by OmerCora** [dev7355608/perfect-vision#92]
After the latest updates, whenever I enable perfect-vision, splatter texture is applied above the tokens instead of below.
Disabling perfect-vision makes the Splatter textures appear below tokens as expected. Here even if moved around, tokens stay below the texture making them hard to see. Console do not show me any specific error/warning.

Here is how it looks like when 

perfect-vision is enabled.
![splatter_error](https://user-images.githubusercontent.com/1075661/127738777-8e78bcfc-4b61-476e-b04d-87eda103e229.png)

perfect-vision disabled.
![whendisabled](https://user-images.githubusercontent.com/1075661/127738898-16918a76-6dc9-4ea3-ab0e-f14afc90cc4c.png)

**Comment by dev7355608** [comment]
Thanks for the report! Because of how PV changed in 2.0 to improve performance, I have to manually resolve these kinds of things. Fixed in v2.1.0.
