### ISSUE TITLE
Can't send to back with latest update

### ISSUE THREAD

**Issue by RavenknightDM** [dev7355608/perfect-vision#93]
Hi, thanks for the mod. I've just noticed that Perfect Vision forces things to the front with the latest updates. I can't reorder objects or characters on the canvas anymore. Unsure if this is a conflict with my many other mods but I didn't see this problem until PV 0.2.0

PV 2.0.1
Foundry 0.8.8

**Comment by dev7355608** [comment]
Thanks for the report. Found the a reorder problem (with tiles specifically) and fixed it in v2.1.2.

PV 2 messes a lot with the canvas layer order to improve performance. I have build my own separate canvas where I send only the things to that should get illuminated. This has the advantage that I have to apply monochrome effect filter only once, and not X times for each token/tile/etc, and control/display elements like the HP bar is not affected by lighting.  Unfortunately I have to resolve more module incompatibilities than before. I'm not sure if your experiencing problems with other modules, or it was just the tiles order not working. Let me know.
