### ISSUE TITLE
Drawing a template creates a second "Ghost" Template

### ISSUE THREAD

**Issue by Brimcon** [dev7355608/perfect-vision#97]
Using Foundry 0.8.8, D&D 1.4.1 Only Libwrapper and Perfect Vision is enabled

![image](https://user-images.githubusercontent.com/7198283/127750730-be74eaa0-e2cb-4441-ba57-052f8ad3a9bf.png)

**Comment by dev7355608** [comment]
Thanks for the report! Fixed it.
